### ISSUE TITLE
The manual installation for iOS is not available

### ISSUE THREAD

**Issue by pietgk** [wkh237/react-native-fetch-blob#104]
It would be great if the manual instructions for iOS where added to the readme.
rnpm has trouble correctly updating my xcode project, so i need the manual installation.

thx Piet

**Comment by wkh237** [comment]
The instructions will be added before 0.9.4 release, refer to #116 .

**Comment by wkh237** [comment]
Please refer to [the wiki](https://github.com/wkh237/react-native-fetch-blob/wiki/Manually-Link-Package), thank you !
