### ISSUE TITLE
XMLHttpRequest polyfill issue

### ISSUE THREAD

**Issue by wkh237** [wkh237/react-native-fetch-blob#106]
Derived #69

**Comment by wkh237** [comment]
@kdedakia, after the investigation, I've located a problem in our XMLHttpRequest implementation, when response header contains `Content-Type : application/json`, the `xhr.response` propertywill be converted to object (which simply JSON.parse xhr.responseText), this is based on my understanding to [W3C standard](https://www.w3.org/TR/XMLHttpRequest/#the-response-attribute). 

However, the WHATWG-Fetch implementation and those ones in many browsers seems not convert `xhr.response` to JSON object when response header has the `application/json` content type, and this is why `fetch` does not working after replacing the `XMLHttpRequest`. The following code snippet is the body parser of WHATWG-Fetch

```js
function Body() {
    this.bodyUsed = false

    this._initBody = function(body) {
      this._bodyInit = body
      if (typeof body === 'string') {
        this._bodyText = body
      } else if (support.blob && Blob.prototype.isPrototypeOf(body)) {
        this._bodyBlob = body
      } else if (support.formData && FormData.prototype.isPrototypeOf(body)) {
        this._bodyFormData = body
      } else if (support.searchParams && URLSearchParams.prototype.isPrototypeOf(body)) {
        this._bodyText = body.toString()
      } else if (!body) {
        this._bodyText = ''
      } else if (support.arrayBuffer && ArrayBuffer.prototype.isPrototypeOf(body)) {
        // Only support ArrayBuffers for POST method.
        // Receiving ArrayBuffers happens via Blobs, instead.
      } else {
        throw new Error('unsupported BodyInit type')
      }
```

Since it does not ever expect `xhr.response` would be an object, it always throws error. I've change our implementation to fit the spec. You can try install the beta version and see if that works properly.

```
$ rnpm install --save react-native-fetch-blob@beta
```

However, when the response is binary data it may not working properly, in this case, you can use our [network APIs](https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API) as an alternative 😏

**Comment by mlumbroso** [comment]
Working great for me now !
