### ISSUE TITLE
[IOS] UIDocumentInteractionController support

### ISSUE THREAD

**Issue by wkh237** [wkh237/react-native-fetch-blob#108]
In Android we can try to open a file by sending `ACTION_VIEW` intent, but there's no compensate API for IOS, maybe `UIDocumentInteractionController` is a good choice ?

**Comment by raminious** [comment]
when this feature will publish ?

**Comment by wkh237** [comment]
Hi @raminious , basically this is already finished but I was planned to release it with other features in `0.10.0`. If you need this feature urgently I can publish a `beta` version (something like 0.10.0-beta.1) once I have time (perhaps in 2~3 days). How do you think ?

**Comment by raminious** [comment]
Awesome
This release can save my time and also I can test this feature from many aspects and send feedback.

Thanks a lot @wkh237

**Comment by wkh237** [comment]
@raminious , I've published a `beta` release to NPM, this feature is now available in `0.10.0-beta.1`.

Upgrade the package via 

```
$ npm install --save react-native-fetch-blob@0.10.0-beta.1
``

**Comment by raminious** [comment]
Thank you for this update @wkh237

**Comment by raminious** [comment]
@wkh237 
I tested these functions today

RNFetchBlob.ios.openDocument: Not worked without throwing any error.
RNFetchBlob.ios.previewDocument: Directly opens file without showing action menu.

iOS: 10 (simulator)
react-native: 0.34.1
path: /Users/raminious/Library/Developer/CoreSimulator/Devices/AFCFB1EA-23C3-4B77-961C-CC431B55D4CF/data/Containers/Data/Application/324FD0EB-73B7-4EE7-9254-3C4B67857D92/Documents/myvid.mp4
