### ISSUE TITLE
In case of a redirect how do I get the URL I was redirected to?

### ISSUE THREAD

**Issue by SamSaffron** [wkh237/react-native-fetch-blob#111]
I tried to search and can not find how I would get the URL I ended up at from the promise resolution. 

.info() does not seem to provide the destination URL

Is there some other method?

**Comment by wkh237** [comment]
@SamSaffron , the library does not support for this. Perhaps we can try to add last response URL to resp.info()

**Comment by SamSaffron** [comment]
yes that would be awesome, my particular use case is checking if a site is HTTP or HTTPS, for cases where HTTP has rewrite going to pass all traffic to HTTPS

**Comment by wkh237** [comment]
This enhancement will launch in `0.9.4`, the `resp.info()` will look like this. 

<img width="434" alt="2016-08-29 1 41 41" src="https://cloud.githubusercontent.com/assets/5063785/18041725/6e2063ec-6dee-11e6-8f8d-cdaca58cc90a.png">

**Comment by SamSaffron** [comment]
wow awesome!

**Comment by wkh237** [comment]
@SamSaffron , I've published a prerelease version on npm `0.9.4-beta.2` which contains this fix. Please try update the package and see if it works properly, thank you 😄

**Comment by wkh237** [comment]
The fix has been released with `0.9.4` so I'm going to close this issue. Please feel free reopen the issue if there's any problem, thank you 😄
