### ISSUE TITLE
Introduce pattern for cleaner transition to background

### ISSUE THREAD

**Issue by SamSaffron** [wkh237/react-native-fetch-blob#115]
Per: http://stackoverflow.com/a/10319761/17174

When app transitions to background native blob should provide the hooks to extend execution until all downloads are complete (or properly timed out)

**Comment by wkh237** [comment]
@SamSaffron , Thanks for your information, I think this is a very improtant feature, and we've tried to implent background transmission mechanism, but it's not a easy task, perhaps still need some time.

**Comment by SamSaffron** [comment]
Recently I have been fighting super hard to get background fetch going. It seems https://github.com/SamSaffron/DiscourseMobile/commit/989c3a3eac40a5bc6b54dc700cccdf1fa7bbf62c may have done the trick but it took me days of debugging and I am still not certain. 

Cleanly dealing with transition to background is a great feature for RN to have, I will raise a separate ticket so core react networking networking deals with this as well

**Comment by wkh237** [comment]
Yeah, I'm agree with you. On Android, developer can use [Download Manager](https://github.com/wkh237/react-native-fetch-blob#android-media-scanner-and-download-manager-support) but there's no such a solution on IOS. 

It would be great to have this implemented, I'll look into it 👍

**Comment by SamSaffron** [comment]
I also opened this issue now to see if core should add something https://github.com/facebook/react-native/issues/9678

**Comment by wkh237** [comment]
related #141

**Comment by wkh237** [comment]
@SamSaffron , I've added `fetch.expire()` API so that you can handle expired request. Please try upgrade `0.10.0-beta.5` from npm if needed, thank you 😄

**Comment by eds101** [comment]
Hi guys,

This issue/PR is causing my app to be killed by iOS after 3 minutes in the background.

Specifically, if I comment out these lines, the problem goes away:
```
    // #115 handling task expired when application entering backgound for a long time
    UIBackgroundTaskIdentifier tid = [app beginBackgroundTaskWithName:taskId expirationHandler:^{
        NSLog([NSString stringWithFormat:@"session %@ expired", taskId ]);
        [expirationTable setObject:task forKey:taskId];
        [app endBackgroundTask:tid];
    }];
```

This is a big problem for our users -- three minutes is a very short time!

Any ideas?

We are on version `0.10.0`
