### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'RNFetchBlob[nativeMethodName]'

### ISSUE THREAD

**Issue by itinance** [wkh237/react-native-fetch-blob#12]
`RNFetchBlob.fetch('GET', mediaUrl, {})`

A promise is returned but .then() or .catch() will never being reached because of an exception:

`undefined is not an object (evaluating 'RNFetchBlob[nativeMethodName]')`

(tested in an iOS-project)

**Comment by wkh237** [comment]
Hi @itinance , thanks for reporting the issue. 

It looks like the native iOS module not linked to your iOS project, have you run `rnpm link` and recompile the project (simply run `react-native run-ios` again) after `npm install react-native-fetch-blob` ?  

I could only be able to reproduce this error when running an iOS project in [release mode](https://facebook.github.io/react-native/docs/running-on-device-ios.html#content) without link native modules. 

Another way to confirm if the library is linked is open `.xcodeproj` inside `ios` folder with XCode, and check if `RNFetchBlob.xcodeproj` is in `Libraries`

<img width="222" alt="2016-05-26 9 28 18" src="https://cloud.githubusercontent.com/assets/5063785/15561034/6a882ebe-2324-11e6-8979-50a01e2243d7.png">

also check if  `libRNFetchBlob.a` is in `Linked frameworks and libries`

<img width="739" alt="2016-05-26 9 29 00" src="https://cloud.githubusercontent.com/assets/5063785/15561045/8c4e457e-2324-11e6-925f-e0daf8918601.png">

**Comment by itinance** [comment]
Thank you for your fast reply. I already did rnpm link and everything seems to be okay, but i still get this error:

![screen shot 2016-05-26 at 13 15 30](https://cloud.githubusercontent.com/assets/1758597/15572945/13e345ce-2344-11e6-9924-d1bdf3e799a4.png)
![screen shot 2016-05-26 at 13 15 43](https://cloud.githubusercontent.com/assets/1758597/15572952/1cc381fe-2344-11e6-8ba2-397a3be65383.png)

**Comment by itinance** [comment]
Okay, i did a "clean" and re- "build" and this worked now for me! Thank you very match for your assistance!

**Comment by wkh237** [comment]
@itinance , you're welcome, please feel free to file an issue : )
