### ISSUE TITLE
Base64 APIs

### ISSUE THREAD

**Issue by adammenges** [wkh237/react-native-fetch-blob#127]
-- please provide the version of installed library and RN project.

0.32

-- a sample code snippet/repository is very helpful to spotting the problem.

actually it's a question about your readme, when you say
```markdown
// here's the body you're going to send, should be a BASE64 encoded string
// (you can use "base64" APIs to make one).
```

What ""base64" APIs" are you referring to?

**Comment by wkh237** [comment]
Hi, @adammenges it uses the library [base-64](https://github.com/mathiasbynens/base64), the instruction is moved to wiki so I'll add a link to [our wiki](https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#base64), thank you 😄

**Comment by adammenges** [comment]
Ah, thanks!

# Sent from iPhone, excuse brevity
