### ISSUE TITLE
Catch exception error but without http error code

### ISSUE THREAD

**Issue by leotu** [wkh237/react-native-fetch-blob#131]
Document say that when http response error would return statusCode (404, 304, 500,...)
i.e,
``` javascript
fetch('GET', url, headers)
      .then((response) => {  // when response status code is 200
         ...
      })
      .catch((errorMessage, statusCode) => {   // Status code is not 200
                            ^^^^^^^^^^^^
          ...
      }
```
But I always get undefined for variable:  "statusCode".

Additional Information:
react-native:  0.29.2
react-native-fetch-blob: 0.9.4
iOS: 8.X & 9.X

**Comment by wkh237** [comment]
@leotu , thank you for the information, I'll try to add the missing part and update the status in this thread : )

**Comment by wkh237** [comment]
@leotu , after some investigation I think this is a design error on IOS, a response with status code other than 2xx should not cause a promise rejection. Therefore I've changed the implementation and published a new version `0.9.5-beta.3`. Please try install this version and you should be able to handle the request status code directly in `then` block instead of `catch` block.

```js
RNFetchBlob.fetch('GET', 'http://www.example.com')
.then((res) => {
    let statusCode = Math.floor(res.info().status)
})
```

Thank you !

**Comment by leotu** [comment]
Ok, I will try it.
Catch http status code is very important that I need to control my cache design.
i.e, use Etag & If-None-Match communicate with "Images Web Server".
for example:  return 404 for using default image, 304 for using local cache image.

**Comment by wkh237** [comment]
@leotu , thanks for your information 👍 Specifying `path` in config, that will force the response body write to the location regardless the original one, when the response is 304 the response body is empty so the original file becomes an empty file. 

Perhaps you can try use the following workaround with `0.9.5-beta.3`

```js

import RNFB from 'react-native-fetch-blob'
const {fetch, fs} = RNFB

RNFB.config({
    fileCache : true
})
.fetch('GET', url, headers)
.then((res) => {
    let status = Math.floor(res.info().status)
    switch(status) {
        // replace the existing file with the new one
        case 200 : 
        fs.mv(res.path(), existPathFile).then(() => {  callback(res.path()) })
        break
        // resource not modified
        case 304 :
        callback(res.path())
        break
        // hanlding HTTP request error
        default :
        callback(defaultImageSrc)
        break
    }
})
// handle network and socket errors
.catch((err) => { ... })
```

**Comment by leotu** [comment]
It works. 
"0.9.5-beta.3" 

Thanks.

**Comment by DazChong** [comment]
`res.info().status` is useful but not documented. Could you add it to the `README.md` as a comment? thanks!
