### ISSUE TITLE
Delete entire folder?

### ISSUE THREAD

**Issue by yaronlevi** [wkh237/react-native-fetch-blob#132]
Hi!
Is there an fs API call that can delete an entire folder?
Iterating over an calling unlink() many times seems bad )-: (slow?)

**Comment by wkh237** [comment]
Hi @yaronlevi , I think this is exactly what we're doing in native `unlink` implementation, you can delete a folder in a single call

```js
RNFetchBlob.fs.unlink('/path/to/a/folder')
```

However, if the folder contains lot of files the process might take some time.

**Comment by yaronlevi** [comment]
thanks it worked! thanks
Maybe the docs could be updated "delete file or entire folder". just to be clear

**Comment by wkh237** [comment]
@yaronlevi , thanks for the advice I'll update the document once I have time 😄

**Comment by esmelov** [comment]
Please tell me, how i can delete all files in a folder without foreach?
