### ISSUE TITLE
Fetch returns path - but no file is downloaded

### ISSUE THREAD

**Issue by sudham** [wkh237/react-native-fetch-blob#133]
I check and add permissions for read/write to external storage in using  react-native-android-permissions at runtime. The following code returns the path but the image is not downloaded to the path.
   componentWillMount() {
          var url = 'http://SKM:5000/user.png';     
          let dirs = RNFetchBlob.fs.dirs
          RNFetchBlob
            .config({
              path : dirs.DocumentDir + '/user.png',
              fileCache : true
          }
            )
           .fetch( 'GET', url )
            .then((res) => {     
                console.log( res );       
                return(res.path);
            })
            .then(this.onAfterLoad) // Success callback registration
            .catch(function(e) {    // Failure callback registration
                alert('Failure fetching data');
                console.log(e)
            });
}
On success set the state --
onAfterLoad = (resp) => {
            this.setState({
                data : resp
        });
      };
Use in render as follows
    <Image style={styles.mark} 
                       source={this.state.data} 
                      defaultSource={require('../images/default.png')} />

What am I missing ?

**Comment by wkh237** [comment]
Hi @sudham , if you are going to download the file to specific location you don't need `fileCache` option, please try the following usage 

```diff
RNFetchBlob
.config({
    path : dirs.DocumentDir + '/user.png',
-   fileCache : true                                                                                                                                                                                                                    
})
.fetch( 'GET', url )
.then((res) => {
    console.log( res );
    return(res.path);
})
.then(this.onAfterLoad) // Success callback registration
.catch(function(e) { // Failure callback registration
    alert('Failure fetching data');
    console.log(e)
});
```

**Comment by sudham** [comment]
RNFetchBlob.fetch( 'GET', url ).then((response) => {   
              let base64Str = response.data;
              fs.writeFile(imageLocation, base64Str, 'base64');
              console.log("FILE CREATED!!");
              RNFetchBlob.fs.scanFile([ { path : imageLocation } ]).then(() => { 
                  console.log("scan file success"); return( 'success' ); 
                })
                .catch((err) => { console.log("scan file error"); });
              })

Removed the filecache and added this code - works now.
