### ISSUE TITLE
Type annotations.

### ISSUE THREAD

**Issue by nicholasstephan** [wkh237/react-native-fetch-blob#134]
I'm getting the following error with v0.9.4 and React Native 0.31.0. 

> SyntaxError /node_modules/react-native-fetch-blob/polyfill/Blob.js: Type annotations must come before default assignments, e.g. instead of  age = 25:number use age:number = 25 (227:50)

**Comment by wkh237** [comment]
@nicholasstephan , thank you for reporting the bug, I've fixed it and published a `beta` release `0.9.5-beta.4`, please try use this version instead 😄

**Comment by kenny1har** [comment]
tested, and working.

**Comment by nicholasstephan** [comment]
I've just updated, and it's working perfectly. Thanks for the quick turnaround. Awesome work.
