### ISSUE TITLE
Question- Creating a Blob from base64 data in memory. (IE: From Camera)

### ISSUE THREAD

**Issue by ChristianTucker** [wkh237/react-native-fetch-blob#135]
Hello, I'm attempting to use your polyfill implementation to allow my React-native application to upload images to my Firebase Storage. However, the implementation is a bit confusing. It seems to me like the only way to build a blob is for the file to be stored on disk, or remotely somewhere. 

When obtaining information from the camera, we get it in a Base64 encoded string, so for example, it may look like this:

```
Hardware.Camera.takePicture(base64EncodedImage => {
    // TODO: Create a Blob from base64EncodedImage
}, error => {

})
```

Perhaps I'm missing something like this in the examples.

**Comment by ChristianTucker** [comment]
For anyone curious, I found the solution after digging around in the Blob.js file, considering the Blob polyfill doesn't have any documentation on the README.

```
    const data = 'iVBORw0KGgoAAAANSUhEUgAAAEsAAABLCAQAAACSR7JhAAADtUlEQVR4Ac3YA2Bj6QLH0XPT1Fzbtm29tW3btm3bfLZtv7e2ObZnms7d8Uw098tuetPzrxv8wiISrtVudrG2JXQZ4VOv+qUfmqCGGl1mqLhoA52oZlb0mrjsnhKpgeUNEs91Z0pd1kvihA3ULGVHiQO2narKSHKkEMulm9VgUyE60s1aWoMQUbpZOWE+kaqs4eLEjdIlZTcFZB0ndc1+lhB1lZrIuk5P2aib1NBpZaL+JaOGIt0ls47SKzLC7CqrlGF6RZ09HGoNy1lYl2aRSWL5GuzqWU1KafRdoRp0iOQEiDzgZPnG6DbldcomadViflnl/cL93tOoVbsOLVM2jylvdWjXolWX1hmfZbGR/wjypDjFLSZIRov09BgYmtUqPQPlQrPapecLgTIy0jMgPKtTeob2zWtrGH3xvjUkPCtNg/tm1rjwrMa+mdUkPd3hWbH0jArPGiU9ufCsNNWFZ40wpwn+62/66R2RUtoso1OB34tnLOcy7YB1fUdc9e0q3yru8PGM773vXsuZ5YIZX+5xmHwHGVvlrGPN6ZSiP1smOsMMde40wKv2VmwPPVXNut4sVpUreZiLBHi0qln/VQeI/LTMYXpsJtFiclUN+5HVZazim+Ky+7sAvxWnvjXrJFneVtLWLyPJu9K3cXLWeOlbMTlrIelbMDlrLenrjEQOtIF+fuI9xRp9ZBFp6+b6WT8RrxEpdK64BuvHgDk+vUy+b5hYk6zfyfs051gRoNO1usU12WWRWL73/MMEy9pMi9qIrR4ZpV16Rrvduxazmy1FSvuFXRkqTnE7m2kdb5U8xGjLw/spRr1uTov4uOgQE+0N/DvFrG/Jt7i/FzwxbA9kDanhf2w+t4V97G8lrT7wc08aA2QNUkuTfW/KimT01wdlfK4yEw030VfT0RtZbzjeMprNq8m8tnSTASrTLti64oBNdpmMQm0eEwvfPwRbUBywG5TzjPCsdwk3IeAXjQblLCoXnDVeoAz6SfJNk5TTzytCNZk/POtTSV40NwOFWzw86wNJRpubpXsn60NJFlHeqlYRbslqZm2jnEZ3qcSKgm0kTli3zZVS7y/iivZTweYXJ26Y+RTbV1zh3hYkgyFGSTKPfRVbRqWWVReaxYeSLarYv1Qqsmh1s95S7G+eEWK0f3jYKTbV6bOwepjfhtafsvUsqrQvrGC8YhmnO9cSCk3yuY984F1vesdHYhWJ5FvASlacshUsajFt2mUM9pqzvKGcyNJW0arTKN1GGGzQlH0tXwLDgQTurS8eIQAAAABJRU5ErkJggg=='
    var blobEvent = new Blob(data, 'image/png')
    var blob = null
    blobEvent.onCreated(genBlob => {
        blob = genBlob
        var uploadTask = firebase.storage().ref('rn-test').child('test-img').put(blob, { contentType: 'image/png'})
        uploadTask.on('state_changed', function(snapshot) {

        }, (error) => {
            console.warn('Upload Error: ' + error)
        }, () => {
            console.warn('Completed upload: ' + uploadTask.snapshot.downloadURL)
        })
    })
```

**Comment by wkh237** [comment]
@ChristianTucker , thanks for the information 👍  It is possible to create a blob from memory, simply  append `;base64` to the content type, please [see our wiki](https://github.com/wkh237/react-native-fetch-blob/wiki/Web-API-Polyfills-(experimental)#builddata-optionspromise) ). I suppose it should work correctly 😏

**Comment by ChristianTucker** [comment]
@wkh237  I completely missed the Wiki somehow, I was wondering where the extra documentation was hiding. Works perfectly, sorry for the false issue.

**Comment by arminsal1** [comment]
I'm having the same issue still with the newest release. @wkh237 My code looks like this:

```
const Blob = RNFetchBlob.polyfill.Blob
const fs = RNFetchBlob.fs
const XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest

uploadImage = (uri, imageName, mime = 'image/jpg') => {
    return new Promise((resolve, reject) => {
      const uploadUri = Platform.OS === 'ios' ? uri.replace('file://', '') : uri
        let uploadBlob = null
        const imageRef = firebase.storage().ref('selfies').child(imageName)
        console.log("uploadUri",uploadUri)
        fs.readFile(uploadUri, 'base64').then((data) => {
          console.log("MADE DATA")
          var blobEvent = new Blob(data, 'image/jpg;base64')
          var blob = null
          blobEvent.onCreated(genBlob => {
            console.log("CREATED BLOB EVENT")
            blob = genBlob
            firebase.storage().ref('selfies').child(imageName).put(blob).then(function(snapshot) {
              console.log('Uploaded a blob or file!');
              firebase.database().ref("selfies/" + firebase.auth().currentUser.uid).set(0)
              var updates = {};
              updates["/users/" + firebase.auth().currentUser.uid + "/signup/"] = 1;
              firebase.database().ref().update(updates);
            });
          }, (error) => {
            console.log('Upload Error: ' + error)
            alert(error)
          }, () => {
            console.log('Completed upload: ' + uploadTask.snapshot.downloadURL)
          })
        })
      }).catch((error) => {
          alert(error)
      })
  }
```

The uri passed into the uploadImage function is from the path of the image captured with react-native-camera. It displays on the <Image/> component I have and successfully turns into a base64 string in the data variable, but the process seems to fail when attempting to "put" the blob. 

I don't know if this part is related, but I noticed most people use the "window.Blob" and "window.XMLHttpRequest" syntax instead of making Blob and XMLHttpRequest constants, but when I try to do so, I receive this alert:

![img_5419](https://cloud.githubusercontent.com/assets/8769537/24325695/bc601abe-1174-11e7-9fbc-e637adb0da50.PNG)

**Comment by wkh237** [comment]
@arminsal1 , you need to replace `window.Blob` and `window.XMLHttpRequest` so that firebase SDK use our implementation.

**Comment by arminsal1** [comment]
@wkh237 `window.Blob` doesn't cause any problems but `window.XMLHttpRequest` gives me that alert in my screenshot

**Comment by cedricholz** [comment]
In case anyone comes here on a google search, I was able upload an image, imageData, from the react-native-camera to firebase using react-native-firebase like this:

`    const UUID = require('uuid-js');
    const uuid4 = UUID.create();

    const uploadTask = storageRef.ref('/images/').child(uuid4).put(imageData.uri, {contentType: 'image/png;base64'});

    uploadTask.on('state_changed', function (snapshot) {
        console.log(snapshot);
        console.log(snapshot.downloadURL)
    }, (error) => {
        console.warn('Upload Error: ' + error)
    })`
