### ISSUE TITLE
Stream an audio file using react-native-tcp

### ISSUE THREAD

**Issue by franrios** [wkh237/react-native-fetch-blob#136]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. You may want to take a look on that page :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.

======

I am  reading text files properly and sending them as they are, but this mp3 file appears to be 170% times bigger than the original when using this configuration.

```
      socket.on('data', (data) => {
        this.updateChatter('Server Received: ' + data);
        RNFetchBlob.fs.readStream('/storage/sdcard1/Music/elpisito.mp3'/*'sdcard/Audio/tone.mp3'*/, 'ascii')
        .then((stream) => {
          let data = ''
          stream.open()

        //  socket.write("HTTP/1.0 200" + "\r\n" + "Content type: audio/mpeg" + "\r\n")
          stream.onData((chunk) => {
            data += chunk
//            console.log(stream)
  //          console.log(chunk)
            socket.write(chunk)
          })
          stream.onEnd(() => {
            console.log('LECTURA TERMINADA')
            //socket.write(data)
            socket.end()

          })
            })

      //  var RNFS = require('react-native-fs')
        console.log('here1')
      /*  RNFS.readFile('/storage/sdcard1/Music/elpisito.mp3').then(data =>{
          socket.write(data)
        })*/
      })
```

**Comment by wkh237** [comment]
@franrios , thanks for reporting this issue, I'll look into it and update my progress here 👍

**Comment by wkh237** [comment]
@franrios , after some test, I think the `readStream` is working correctly. 

I've noticed in the code snippet you've provided 

```js
stream.onData((chunk) => {
            data += chunk
            socket.write(chunk)
})
```

may having some problem since the `chunk` is an Array when reading stream using `ascii` encoding. You may replace it with this


```diff
stream.onData((chunk) => {
-            data += chunk                                                                                                                                                         
-            socket.write(chunk)                                                                                                                                                         
+            data = data.concat(chunk)                                                                                                                                                         
+            socket.write(chunk.join(''))                                                                                                                                                         
})
```

I think this will give you correct file size 😏 

Besides, the `ascii` encoding is somehow slower than other encoding, please refer to the [Performance Tips](https://github.com/wkh237/react-native-fetch-blob#performance-tips) and #118 😄

**Comment by franrios** [comment]
Thanks for your response @wkh237, at the end I needed to use 206 Partial content status code so I  used `socket.write(chunk,'ascii')` in order to allow streaming instead of a full download.

**Comment by wkh237** [comment]
@franrios , does it working properly ? If it's not please feel free leave any feedback 😄
