### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by shahen94** [wkh237/react-native-fetch-blob#137]
I'm using React-native 0.33;
react-native-fetch-blob 0.9.5;

I can't build my android app.
It's starts work when i added this line below into my `build.gradle` file.

`compile 'com.squareup.okhttp3:okhttp:3.4.1'`

**Comment by slavikmanukyan** [comment]
+

**Comment by wkh237** [comment]
@shahen94 , thank you for reporting this issue 😄  I'm not sure if it's okay to add OkHttp dependency by default, because it cause app crash on some versions. 

I'll leave this issue open for reference until I figure it out

**Comment by mihirk** [comment]
+

**Comment by aubreywahl** [comment]
If it's of any consolation, I was able to build without a problem on Android (platform 23) with RN 0.34, Ubuntu 16.04

**Comment by mihirk** [comment]
@wkh237 
Ok I am still getting a build failure even after upgrading React-Native to RN 0.34.
Also I don't understand if the library is using okhttp3 why is it not in the dependencies.

More info 
Mac OS X El Capitan
RN 0.34
RNFetchBlob 0.9.6
Java 1.8 (Tried with 1.7 too)

P.S: Thanks for this library, its pretty awesome.

**Comment by Deevent** [comment]
I have the exact same issue. Impossible to run on Android and adding `compile 'com.squareup.okhttp3:okhttp:3.4.1'` doesn't fix the error.

RN : 0.39.2 RNFB : 0.10.0

**Comment by lll000111** [comment]
I'll close this since there also is #217 and [also quite a few closed ones](https://github.com/wkh237/react-native-fetch-blob/issues?utf8=%E2%9C%93&q=compile%20okhttp3%20).
