### ISSUE TITLE
Could add home dir in RNFetchBlob.fs.dirs ?

### ISSUE THREAD

**Issue by siyuan** [wkh237/react-native-fetch-blob#138]
Sometimes I need home dir:
/storage/emulated/0/
Could this be added to RNFetchBlob.fs.dirs ?
Thanks.

**Comment by wkh237** [comment]
@siyuan , thank you for the advice, I think it's reasonable. 

I'll try add this constant to `fs.dirs` , also feel free to make a PR if you have any idea on this 😄
