### ISSUE TITLE
How to decode the base64 to native binary data?

### ISSUE THREAD

**Issue by itinance** [wkh237/react-native-fetch-blob#14]
I download mp3 files from a remote source with [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) and store them in local filesystem with [react-native-fs](https://github.com/johanneslumpe/react-native-fs).
However, the data is stored in base64 encoded then.

Is it possible to store the files directly in its binary format on local storage that i can play these files with this library [react-native-sound](https://github.com/zmxv/react-native-sound)? Or is there another way?

**Comment by itinance** [comment]
Ah i think this relates to https://github.com/wkh237/react-native-fetch-blob/issues/2

**Comment by wkh237** [comment]
Hi @itinance , as you may know, I'm still working on it ( on v0.5.0 branch ) 😃

**Comment by itinance** [comment]
Sounds really nice! Can you tell some details of this upcoming feature? In my case i think about a method "downloadFileToLocalStorage( uri, destination )" and the file would be downloaded from remote uri and placed in local storage. 
Would your new feature be the same more or less? :)

**Comment by wkh237** [comment]
@itinance , I planned to add a `config` API so that you can do this 

```js
RNFetchBlob.config({
    path : 'path-to-local-storage'
})
.fetch('GET', ... ,{...})
// it will be a file path rather than BASE64 string
.then( (pathOfDownloadedFile) => ... )
```

I'm also consider whether add some other APIs that simply wraps the original ones, such as

```js
RNFetchBlob.downloadToStorage(config, path)
RNFetchBlob.uploadFromStorage(config, path)
```
but these wrapper APIs may not be added in v0.5.0.

**Comment by itinance** [comment]
That sounds really great!

**Comment by fredbt** [comment]
Was this developed after all? I have exactly this use case here :)
(instead of dowloading the file, I actually receive a binary of a mp3 in the response of an HTTP request, then save to react-native-fs, and I want to play it later with react-native-sound).
