### ISSUE TITLE
How to move file from app Document folder to Iphone's document folder using RNFB

### ISSUE THREAD

**Issue by ignivaankushrishi** [wkh237/react-native-fetch-blob#148]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. You may want to take a look on that page or find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.

**Comment by wkh237** [comment]
@ignivaankushrishi , not sure if I'm reading this right, from my understanding every IOS app running inside a sandbox, so they're not be able to access folders outside their app's home folder.
