### ISSUE TITLE
support multi connection download

### ISSUE THREAD

**Issue by raminious** [wkh237/react-native-fetch-blob#149]
Is it possible add core feature to support multi connection per host ? (like aria2 with -x command)
It will increase download speed and make the module more powerfull

**Comment by wkh237** [comment]
On Android OkHttp uses thread pool, I assume it already supports multiple connections, as for iOS I will take some time to investigate :)

**Comment by raminious** [comment]
Thank you
Android OkHttp works by default or should we config something ? 
If yes, is documented somewhere ?
