### ISSUE TITLE
Allow passing unparsed response body to error handler

### ISSUE THREAD

**Issue by blackxored** [wkh237/react-native-fetch-blob#154]
I've this specific backend that returns 400 but also a payload (i.e body) indicating the errors. Dropping this library into the project prevents me from doing further processing of that body as I would do with native fetch's catch right before parsing. Error handler only seems to be given a message (since `respInfo` is broken, as you need to add it as a property or make a custom Error class), and even then no response body that I can continue processing on after checking the status code (i.e calling .json() on it).

**Comment by wkh237** [comment]
@blackxored , thanks for the suggestion. I'll try to fix this bug once I have time 👍

**Comment by wkh237** [comment]
@blackxored , I've change the error handling on native side, I think it should works as expected now. Please try upgrade to `0.10.0-beta.2` and see if it works propery 😄
