### ISSUE TITLE
IOS can not connect to https SSL certificate with config trusty:true but Android can

### ISSUE THREAD

**Issue by eggeggeg** [wkh237/react-native-fetch-blob#159]
"react-native": "0.33.0",
"react-native-fetch-blob": "^0.9.6",
XcodeVersion 7.3.1

as title, 

and I checked didRectiveChallenge function in RNFetchBlob.xcodeproj/RNFetchBlobNetwork.m

When I connect to HTTPS with using trusty:true , didRectiveChallenge will not be entered , so I get failed result.

But if I remove the if block , 

`if ([options valueForKey:CONFIG_TRUSTY] != nil)
{
        completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust]);
}
`

it will connect successfully,

I find out the function does not work because of this code

`NSURLSessionAuthChallengePerformDefaultHandling`

I change this it can work

`NSURLSessionAuthChallengeUseCredential`

Can someone tell me why?  Plz

**Comment by wkh237** [comment]
@eggeggeg , after some tests I think this is a bug. I'll fix this part and release a `beta` version in these days, thank you 👍

**Comment by wkh237** [comment]
@eggeggeg , I've published `0.10.0-beta.4` which should fix this bug, please upgrade the package and verify the fix, thank you 😄

**Comment by eggeggeg** [comment]
@wkh237 , after my test, it work for me,thank you
