### ISSUE TITLE
Reorganize to match other react-native repos

### ISSUE THREAD

**Issue by tuckerconnelly** [wkh237/react-native-fetch-blob#164]
Hey, I'm trying to get this to compile with webpack (for a project with `react-native-web`), which needs the source to be compiled to ES5.

This is pretty simple in other react-native module repos, which have a top-level directory with a package.json, the ios and android folders, and then the javascript either also in the top-level, or in a `src` folder (check out https://github.com/react-native-community/react-native-blur).

Could you move this project over to that structure? It would get rid of the duplicate `README.md` and `package.json` files. I already have a commit for this (https://github.com/tuckerconnelly/react-native-fetch-blob/commit/ede33f8cdbd8f516537ea665bd6360865f5e8988) if you'd accept a PR :)

**Comment by wkh237** [comment]
@tuckerconnelly , thanks for the advice. After `0.9.6` I push the files in `src` folder to an [archive repo](https://github.com/wkh237/react-native-fetch-blob-package),  could you please see if that fulfills your need ? 😏

**Comment by tuckerconnelly** [comment]
It doesn't. It's messy IMO. But I've got my own fork so I'm good.
