### ISSUE TITLE
[actionViewIntent] Add callback when activity ends

### ISSUE THREAD

**Issue by Meshz** [wkh237/react-native-fetch-blob#165]
Hello @wkh237,

I'm downloading a file (XLS, DOC, ...) in local storage and opening it through `actionViewIntent`. I would like to upload it back once the user has finished editing it. Is there any callback available when the activity is ended or when the user comes back to the RN app? Thanks!

**Comment by wkh237** [comment]
Okay, I'll work on this issue 👍

**Comment by wkh237** [comment]
@Meshz , I've released a beta release to npm `0.10.0-beta.5`, you should be able to know if the action view is dismissed by simply use promise pattern 

```js

RNFetchBlob.android.actionViewIntent(path, mime)
.then(() => {
    // action view is dismissed !!
})

```

please upgrade the package and verify the fix, thank you 👍

**Comment by Meshz** [comment]
Hello @wkh237, I updated to `0.10.0-beta.7` and the callback is not triggered (Android 4.4.4). Any information I can give you to solve this?

**Comment by wkh237** [comment]
@Meshz , I've corrected the statement in 8215f07 , I think it should work now. Please upgrade to `0.10.0-beta.8` and see if it works for you, thank you 👍

**Comment by Meshz** [comment]
@wkh237, I can confirm this is perfectly working now (on Android). Thank you! 👍

**Comment by wkh237** [comment]
Great! I'll close this issue once 0.10.0 release 😄
