### ISSUE TITLE
Implement previewDocument on Android

### ISSUE THREAD

**Issue by raminious** [wkh237/react-native-fetch-blob#166]
Is it possible to add previewDocument (file chooser) for Android too ?
I searched on Github and found a code doing this job

``` java
    @ReactMethod
    public void open(String fileArg, String contentType, Promise promise) throws JSONException {
        File file = new File(fileArg);
        if (file.exists()) {
            try {
                Uri path = Uri.fromFile(file);
                Intent intent = new Intent(Intent.ACTION_VIEW);
                intent.setDataAndType(path, contentType);
                Intent i = Intent.createChooser(intent, "Open File");
                i.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                getReactApplicationContext().startActivity(i);
                promise.resolve()
            } catch (android.content.ActivityNotFoundException e) {
                promise.reject("Error !!!!");
            }
        } else {
            promise.reject("File not found");
        }
    }

```

Thank you

**Comment by wkh237** [comment]
@raminious , we've already introduced this feature in `0.9.0`. Please check [the doument](https://github.com/wkh237/react-native-fetch-blob/wiki/Android-API#androidactionviewintentpath-mimepromise) 👍

**Comment by raminious** [comment]
Thanks @wkh237 
Sorry for late response
I see ```android.actionViewIntent``` before. it should use for both open and openWith scenarios ?

**Comment by wkh237** [comment]
@raminious , when using `actionViewIntent`, it shows a menu contains lists of apps which can open the file. If there's only one, it opens the file directly using the app.
