### ISSUE TITLE
Uploading picture - [Error: unexpected end of stream

### ISSUE THREAD

**Issue by faisalkanji** [wkh237/react-native-fetch-blob#169]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. You may want to take a look on that page or find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.

Hi 
I'm trying to upload a picture taken from the camera in my android app. This is my code: 
RNFetchBlob.fetch('POST', 'http://192.168.0.15:3000/api/containers/images/upload', {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    // Change BASE64 encoded data to a file path with prefix `RNFetchBlob-file://`.
    // Or simply wrap the file path with RNFetchBlob.wrap().
  }, JSON.stringify({"file" : RNFetchBlob.wrap('/storage/emulated/0/Pictures/IMG_20161028_094032.jpg')}))
  .then((res) => {
    console.log(res.text())
  })
  .catch((err) => {
    console.log(err)
  })

and I keep receiving [Error: unexpected end of stream

**Comment by wkh237** [comment]
@faisalkanji , if you intended to upload a file from storage I think you should use it this way 

```js
RNFetchBlob.fetch('POST', 'http://192.168.0.15:3000/api/containers/images/upload', {
'Content-Type': 'application/octet-stream',
}, RNFetchBlob.wrap('/storage/emulated/0/Pictures/IMG_20161028_094032.jpg') )
.then((res) => {
console.log(res.text())
})
.catch((err) => {
console.log(err)
})
```

**Comment by faisalkanji** [comment]
Thank you for your help. That returns {"result":{"files":{},"fields":{}}} and doesn't upload the file

**Comment by faisalkanji** [comment]
I also tried sending it as a multipart, but that also didn't work handlePressDocument = () => {
    this.toggleDrawer()
    RNFetchBlob.fetch('POST', 'http://192.168.0.15:3000/api/containers/images/upload', {
    //'Accept': 'application/json',
    'Content-Type': 'multipart/form-data',
    // Change BASE64 encoded data to a file path with prefix `RNFetchBlob-file://`.
    // Or simply wrap the file path with RNFetchBlob.wrap().
  }, [
  { name : 'test', filename : 'test.jpg', data: RNFetchBlob.wrap('/storage/emulated/0/Pictures/IMG_20161028_094032.jpg')},
    ])

produces: 
ReactNativeJS: {"result":{"files":{},"fields":{"null":["ï¿½ï¿½ï¿½ï¿½ï¿½\nExif\u0000\u0000MM\u0000*\u0000\u0000\u0000\b\u0000\t\u0001\u000f\u0000\u0002\u0000\u0000\u0000\t\u0000\u0000\u0000z\u0001\u0010\u0000\u0002\u0000\u0000\u0000\u0007\u0000\u0000\u0000ï¿½\u0001\u001a\u0000\u0005\u0000\u0000\u0000\u0001\u0000\u0000\u0000ï¿½\u0001\u001b\u0000\u0005\u0000\u0000\u0000\u0001\u0000\u0000\u0000ï¿½\u0001(\u0000\u0003\u0000\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u00012\u0000\u0002\u0000\u0000\u0000\u0014\u0000\u0000\u0000ï¿½\u0002\u0013\u0000\u0003\u0000\u0000\u0000\u0001\u0000\u0001\u0000\u0000ï¿½i\u0000\u0004\u0000\u0000\u0000\u0001\u0000\u0000\u0000ï¿½ï¿½%\u0000\u0004\u0000\u0000\u0000\u0001\u0000\u0000\r\u0014\u0000\u0000\r:Motorola\u0000\u0000XT1064\u0000\u0000\u0000\u0000\u0000H\u0000\u0000\u0000\u0001\u0000\u0000\u0000H\u0000\u0000\u0000\u00012016:10:28 09:40:31

**Comment by wkh237** [comment]
@faisalkanji , I'm little confused. From my understanding, this problem may also related to the implementation of the server's upload API.

**Comment by faisalkanji** [comment]
Sorry, you're right it was a problem with my upload api thank you for your help
