### ISSUE TITLE
v0.5.0 release preparation

### ISSUE THREAD

**Issue by wkh237** [wkh237/react-native-fetch-blob#17]
v0.5.0 features are almost finished, before it release we still got something to do.

- [x] Documentation
- [x] More test cases
- [x] System directory API  improvement
- [x] Memory and file cache release

**Comment by vince-rowe** [comment]
This is fantastic, looking forward to using the direct save / temp location to be more memory efficient in our particular use cases. Do you have an idea on timings for the release of this? Or a method of us installing the 0.5.0 branch with react native while this is still work in progress at all?

Many thanks

**Comment by wkh237** [comment]
Hi @vince-rowe , please take a look on [v0.5.0 milestone](https://github.com/wkh237/react-native-fetch-blob/milestones). 

v0.5.0  functions and tests are almost finished, but I still prefer to publish on the scheduled date (say, June 12). 

Before that, if you're going to install v0.5.0 from the source. you can just clone or download the source, then `npm install` the `src` folder. 

For example 

```shell
$ npm install --save ~/some-file-path/react-native-fetch-blob/src
```
And don't forget to add file storage permissions on Android if needed (see [v0.5.0 README](https://github.com/wkh237/react-native-fetch-blob/tree/0.5.0#user-content-installation)). As for the new API usages, you may reference [the tests](https://github.com/wkh237/react-native-fetch-blob/tree/0.5.0/test) before the document finished.

**Comment by vince-rowe** [comment]
Thats perfect, all up and running this end and looks great. Many thanks for your quick response.

Vince
