### ISSUE TITLE
Upgrading from 0.9.6-beta.2 to 0.10.0.beta.1 throws error

### ISSUE THREAD

**Issue by shilpan** [wkh237/react-native-fetch-blob#170]
`
RNFetchBlob.enableUploadProgressReport was called with 3 arguments, but expects 1. If you haven't changed this method yourself, this usually means that you versions of the native code and Javascript code are out of sync. Updating both should make this error go away.
`

I tried uninstalling/installing the package and doing a clean start. But the error still remains. How do I resolve this?

**Comment by wkh237** [comment]
@shilpan , on `0.10.0` we've changed native API. Acoording to the error message, looks like you're using 0.9.6 JS module with 0.10.0+ native modules. Did you restart the packager after upgrade the package ?

**Comment by shilpan** [comment]
Yes I did, I even cleared the cache, did a fresh install etc. The interesting thing is that it works just fine on Android but fails on iOS. Is there some manual change I would need to do in the `ios` folder?

**Comment by shilpan** [comment]
Uninstalling/Installing app from the emulator or app does the trick. Closing this issue.
