### ISSUE TITLE
On Android, appendExt is not being added to the localPath

### ISSUE THREAD

**Issue by shilpan** [wkh237/react-native-fetch-blob#171]
Here is my code:

``` javascript
export function downloadFile(file, url, contentType, size) {
  return (dispatch, getState) => {
    return RNFetchBlob
      .config({
        session: SESSION_NAME,
        fileCache: true,
        appendExt: 'mp4'
      })
      .fetch('GET', url)
      .then(res =>
        dispatch(addFile(file, res.path(), contentType, size)))
  }
}
```
The resulting file path on Android is: `/data/user/0/com.stitchapp/files/RNFetchBlobTmp_faadb355-e693-45ef-aa6e-f5d18926bfc2`.

Notice that `.mp4` is missing. This issue does not occur on iOS.

**Comment by wkh237** [comment]
@shilpan , thanks for reporting this issue. I've noticed this problem days ago, I'll publish a beta release contains the fix 😄

**Comment by shilpan** [comment]
I'll be waiting :) it causes an issue when downloading a file locally and  trying to run it with `react-native-video`

**Comment by wkh237** [comment]
@shilpan , the fix is included in `0.10.0-beta.5` please upgrade the package and verify if it's fixed, thank you 👍

**Comment by Timehello** [comment]
@wkh237  Still not work on 0.10.0-beta.5

**Comment by wkh237** [comment]
@Timehello , is it happenns on Android or IOS ?

**Comment by Timehello** [comment]
@wkh237  Android, ios is ok

**Comment by shilpan** [comment]
works on `0.10.0-beta.6`

**Comment by Timehello** [comment]
yes, it works on beta6 !
