### ISSUE TITLE
Fail to compile 0.10.0-beta.5 react-native-fetch-blob in android

### ISSUE THREAD

**Issue by francisco-sanchez-molina** [wkh237/react-native-fetch-blob#172]
This is the fail:

`
_node_modules/react-native-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlob.java:9:_ error: cannot find symbol
import com.facebook.react.LifecycleState;
                         ^
  symbol:   class LifecycleState
  location: package com.facebook.react
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-fetch-blob:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
`

I solve it removing the import

Thanks!

**Comment by wkh237** [comment]
@francisco-sanchez-molina , thanks for the information. 

I think this is caused by the changes for solving #165. `import com.facebook.react.LifecycleState;` only supported on RN 0.35+, I'll try if it can be backward compatible.

**Comment by wkh237** [comment]
@francisco-sanchez-molina , I've fixed the bug. Looks like the statement is unnecessary you can simply upgrade to `0.10.0-beta.6` and see if it works properly, thank you.

**Comment by francisco-sanchez-molina** [comment]
It works properly!! Thanks a lot!
