### ISSUE TITLE
FileSystem SDCard constant on Android is undefined

### ISSUE THREAD

**Issue by camlahoud** [wkh237/react-native-fetch-blob#174]
RNFB: 0.9.6
RN: 0.33.0

RNFetchBlob.fs.dirs.SDCardDir is undefined since the native class exposes the constant as SDCard, but the JS code reads SDCardDir

RNFetchBlobFS.java (line: 195)
`
res.put("SDCard", Environment.getExternalStorageDirectory().getAbsolutePath());
`

fs.js (line 32)
`
SDCardDir : RNFetchBlob.SDCardDir
`

**Comment by wkh237** [comment]
@camlahoud , I've corrected this problem in `0.10.0-beta.8`, please upgrade your package and verify it. Thank you 😄

**Comment by camlahoud** [comment]
@wkh237 Just checked the update. 
RNFetchBlob.fs.dirs.SDCardDir is still undefined. If you just change RNFetchBlobFS.java line 203 from 
`res.put("SDCard", Environment.getExternalStorageDirectory().getAbsolutePath());`
to
`res.put("SDCardDir", Environment.getExternalStorageDirectory().getAbsolutePath());`
it will work.
Thank you for the fast feedback :)

**Comment by zhixueyong** [comment]
Please update the document: https://github.com/wkh237/react-native-fetch-blob/wiki/File-System-Access-API#dirs, it still mentions SDCard, should be SDCardDir now. Thanks.
