### ISSUE TITLE
Progress only called once/one time on multipart/form-data?

### ISSUE THREAD

**Issue by kwnzak** [wkh237/react-native-fetch-blob#177]
I'm having an issue where the upload progress is only called once in my console.log.

The file is uploaded fine however, and params are all passed correctly.
I've also tried setting the interval to no luck.

I am using 'Content-Type' : 'multipart/form-data' like below:

```
RNFetchBlob.fetch('POST', endpoints.profile.picture.upload, {
      Authorization : 'Bearer ' + auth.token,
      'Content-Type' : 'multipart/form-data'
    }, [
      {
      name : 'picture',
      filename : 'picture.png',
      data:  RNFetchBlob.wrap( this.state.picture )
      },
    ])
    .uploadProgress({ interval : 250 }, (written, total) => {
      console.log('uploaded', written / total)
    })
etc.
```

"react-native-fetch-blob": "^0.9.6",
"react-native": "0.34.1",

Wondering if anyone could please steer me in the right direction? Thanks!

**Comment by wkh237** [comment]
@kwnzak , if the file is small and the interval is large the progress event will only trigger once. Could you try use a smaller `interval` or try a larger file instead ?

**Comment by kwnzak** [comment]
Understood, thank you!

**Comment by ming436534** [comment]
I have this issue too, my file is not small and interval is long enought but the uploadProgress only triggered once

**Comment by bronco** [comment]
Same issue.
Using 0.10.4, even set the interval to 50, the uploadProgress only triggered once.

**Comment by tuandt** [comment]
Hi,
I go the same problem on android. The uploadProgress only triggered once.

Any solution for this?

**Comment by RSSfeed** [comment]
+1

**Comment by dioxide** [comment]
+1

**Comment by rad182** [comment]
+1
