### ISSUE TITLE
Cancel download

### ISSUE THREAD

**Issue by YusufBesim** [wkh237/react-native-fetch-blob#178]
Hi! I am downloading file at componentDidMount. I want to cancel downloading when user tap button.

Example:
componentDidMount(){
   var task = RNFetchBlob
      .config({
        // add this option that makes response data to be stored as a file,
        // this is much more performant.
        fileCache : true,
        path : dirs.DocumentDir + '/1.pdf'
      })
      .fetch('GET', 'URL', {

      })
      .progress((received, total) => {
          thiz.setState({percent:{recieved:received,total:total}});
      })
      .then((res) => {
        console.log('The file saved to ', res.path())
        thiz.setState({"pdf":res.path()})
      })
}
onCancel(){
    // HERE I WANT TO CANCEL DOWNLOAD WHEN USER TAP CANCEL BUTTON
}

* 35.0 RN version

**Comment by wkh237** [comment]
Hi @YusufBesim , have you tried [the API](https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#fetchcanceleventlistenerpromisernfetchblobresponse) ? perhaps it's what you need ?
