### ISSUE TITLE
Android upload TypeError

### ISSUE THREAD

**Issue by eggeggeg** [wkh237/react-native-fetch-blob#186]
"react-native": "0.33.0",
"react-native-fetch-blob": "^0.10.0-beta.4",

```
export const fetchUsersInfo = ({
  userIdList=[],
}) => {
  return () => {
    return RNFetchBlob.config({
      trusty : true
    })
    .fetch(
      'POST',
      '${HOST}/getUsers',
      {
        'Content-Type': 'application/json'
      },
      [
        {
          name:'userIds',
          data:userIdList
        }
      ]
    )
    .then(response => response.json())
    .then(json => {
    }).catch(error => {
      console.warn('fetchUsersInfo-error', error);
    });
  };
};
```

I think it should be similar to this #102 , but my data type is array

IOS is no problem, but the Android

**RNFetchBlob failed to create request multipart body:TypeError:expected dynamic type string,but had type 'array'**

**Comment by wkh237** [comment]
@eggeggeg , could you try `JSON.stringify()` the request body ?

**Comment by eggeggeg** [comment]
@wkh237  
Thanks,It work

`data:JSON.stringify(userIdList)
`
