### ISSUE TITLE
Fetch Replacement evalues to object, not function

### ISSUE THREAD

**Issue by rwillemsandroid** [wkh237/react-native-fetch-blob#190]
RN version: `0.35`
RNFetchBlob version: `0.10.0`
Platform: Android & iOS

I tried using the fetch replacement functions as documented here: 
https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#fetch-replacement

```
import RNFetchBlob from 'react-native-fetch-blob';

const Fetch = RNFetchBlob.polyfill.Fetch;
// replace built-in fetch
window.fetch = new Fetch({
    // enable this option so that the response data conversion handled automatically
    auto : true,
    // when receiving response data, the module will match its Content-Type header
    // with strings in this array. If it contains any one of string in this array,
    // the response body will be considered as binary data and the data will stored
    // in file system instead of in memory.
    // By default, it only store response data to file system when Content-Type
    // contains string `application/octet`.
    binaryContentTypes : [
        'image/',
        'video/',
        'audio/',
    ]
});
```

However, when I do this and use `fetch()`, I get the following error:

```
fetch is not a function
TypeError: fetch is not a function
```

Logging the replacement fetch function yields the following:

`console.log("RNfetchblob fetch: " , fetch);`

![screen shot 2016-11-21 at 12 42 00](https://cloud.githubusercontent.com/assets/13900476/20481551/04bf014c-afe8-11e6-9a50-851cd8e33f45.png)

The original fetch function looks like this:

![screen shot 2016-11-21 at 12 30 35](https://cloud.githubusercontent.com/assets/13900476/20481580/2928cc0c-afe8-11e6-990f-b7dd4d6ba300.png)

Any help into solving this issue is greatly appreciated.

**Comment by wkh237** [comment]
@rwillemsandroid , thanks for reporting this issue. I think this is an mistake on document, please reference to the [test case](https://github.com/wkh237/react-native-fetch-blob/blob/master/test/test-0.9.2.js#L16) for proper usage.
