### ISSUE TITLE
Cannot run test app according to wiki instructions

### ISSUE THREAD

**Issue by superquest** [wkh237/react-native-fetch-blob#191]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. You may want to take a look on that page or find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.

I am trying to follow wiki instructions to run the test app: https://github.com/wkh237/react-native-fetch-blob/wiki#run-and-install-test-app

Problem 1: `npm test` points at a `test.sh` file ... but no `test.sh` exists.

Problem 2: The wiki says I should modify `test/tests.js`. That file also doesn't exist. Should I create it?

I was using a fresh clone of the master branch.

**Comment by stockninja** [comment]
The test.sh file exists on branch "0.9.7" ... so I'm going to proceed testing over there. 

Looks your package.json "test script" needs an update, though.

**Comment by stockninja** [comment]
OK I couldn't get test app running on "0.9.7" branch. I'm just going to wait for an update from you folks :)

**Comment by wkh237** [comment]
@stockninja , thanks for point out this problem, the test script has been moved to `scripts` folder. I've change the npm test script and commit to master branch.
