### ISSUE TITLE
[readStream] encode to base64

### ISSUE THREAD

**Issue by shahen94** [wkh237/react-native-fetch-blob#192]
How i can read video file and encode it to base64 ?

```
return fs.readStream(source.uri, 'base64')
      .then((readStream) => {
        // open stream
        readStream.open();

        // save chunks on every function call
        readStream.onData((chunk) => base64Arr.push(chunk));
        readStream.onError((err) => AlertMessage.systemError(err));
        /**
        * When streaming is done start posting
        * */
        readStream.onEnd(() => {
        this.initSources(base64Arr.join(''))
         .then(() => this.togglePostDoneModal())
         .catch((e) => AlertMessage.fromRequest(e));
        });
      })
```

It returns invalid base64 string, and it's not a video.
I'm doing it with `readFile` and it works fine !
But what if i need to encode big video file ? Can i do it with `readFile` ?

Thanks !

RN version: 0.36
FetchBlob version: 0.10
OS: MacOS Sierria

**Comment by wkh237** [comment]
@shahen94 , thanks for reporting this issue. I'm a little confusing, if you're going to encode a big file to BASE64 string you still need lot of memory to keep the string, and that's just like use `readFile`.  

I'd like to know more detail  😄

**Comment by shahen94** [comment]
Hi @wkh237.
Yes I need to convert video file to Base64.
I need to upload it to AWS, and it want the base64 encoding of the file.
Video file can be 10-100mb.

Library works fine when I'm using readFile.
But with readStream it gives me wrong base64.

**Comment by wkh237** [comment]
@shahen94 , I've write a test case which reads a 24MB image in chunks and write these base64 chunks into a file then decode it. Looks like it's working properly, here's my code :

```js

let writeStream
// create empty file for write
fs.createFile(dest, '')
  // prepare test image
  .then(() => {
    return fs.readStream(sourcePath, 'base64', 4095)
  })
  .then((readStream) => {
    // write chunks into file
    readStream.onData((chunk) => {
      writeStream.write(chunk)
    })
    readStream.onEnd(() => {
      writeStream.close()
      fs.readFile(dest, 'utf8')
      .then((base64) => {
            // here's the image
      })
    })
    // open write stream
    fs.writeStream(dest, 'utf8').then((stream) => {
      writeStream = stream
      readStream.open()
    })
  })
```

If the file is large, you may need set a larger `bufferSize` and an appropriate `interval` to the stream.

See also, [the document](https://github.com/wkh237/react-native-fetch-blob/wiki/File-System-Access-API#readstreampath-encoding-buffersize-intervalpromisernfbreadstream)

**Comment by shahen94** [comment]
I'm getting wrong base64 encoding even from 5MB video file.
When i want to play that i got an error that's not a video file

What if i want to read 30MB file ?
How much larger should i set the `bufferSize` for it ?

**Comment by shahen94** [comment]
@wkh237 Hi Bro.
It works ! Really i don't understand why but it works when i add `bufferSize`.
I'm going to close this issue.

**Comment by profecialinks** [comment]
if you are using base 64 for video use readFile method instead readStream
