### ISSUE TITLE
Feature: ios.previewDocument/openDocument custom action button

### ISSUE THREAD

**Issue by blackburnian** [wkh237/react-native-fetch-blob#198]
We are downloading an opening a PDF via this code in our RN application:
```
RNFetchBlob.config({
    path: dirs.DocumentDir + '/test.pdf'
})
    .fetch('GET', `https://www.ets.org/Media/Tests/TOEFL/pdf/SampleQuestions.pdf`)
    .then((res) => {
                RNFetchBlob.ios.openDocument(res.path());
    })
```
This works beautifully:
![img_0671](https://cloud.githubusercontent.com/assets/6427749/20635974/f8c182b8-b319-11e6-9c74-c7370a05a5cd.PNG)

However, in our scenario, we need to prevent the user from sharing the PDF or doing anything else with it besides viewing it. We do however want to offer them the option to save it locally to their phone which we can also use your plugin for. Is there a way to pass some options to the `openDocument` method which would allow us to put a 'Save' button (instead of that action icon 
![image](https://cloud.githubusercontent.com/assets/6427749/20636005/73df0344-b31a-11e6-907b-032648047d9b.png))
 and give us a callback that we can fire when they click on it? Something like: 
```
RNFetchBlob.config({
    path: dirs.DocumentDir + '/test.pdf'
})
    .fetch('GET', `https://www.ets.org/Media/Tests/TOEFL/pdf/SampleQuestions.pdf`)
    .then((res) => {
                RNFetchBlob.ios.openDocument(res.path(), {
                    actionButtonText: 'Save',
                    actionButtonCallback: () => {
                                
                    }                
                });
    })
```

**Comment by blackburnian** [comment]
Oh, by the way, on your documentation, I think you need to switch the `openDocument` and `previewDocument` methods. It shows the `openDocument` method as the method that brings up the options menu:
![image](https://cloud.githubusercontent.com/assets/6427749/20636059/f98f0d2c-b31a-11e6-9ddb-09d1b27fc495.png)
when in fact it's the `previewDocument` method that does that.

**Comment by wkh237** [comment]
@blackburnian , thanks for the advice, but I'm not sure if this is possible because looks like a platform limitation, it there's any information we can try to do this 😄

**Comment by dwilt** [comment]
@wkh237 I noticed in your [documentation](https://github.com/wkh237/react-native-fetch-blob/wiki/iOS-API), that the `UIDocumentInteractionController` is used. I did some quick googling about that and found [this](http://stackoverflow.com/questions/35116820/uidocumentinteractioncontroller-remove-actions-menu). If we can set the button to `nil`, could we also have it provide a value?

**Comment by dwilt** [comment]
I'm subscribed to it. Just left a comment FYI.

**Comment by wkh237** [comment]
@dwilt , I've tried the approach mentioned in the SO thread but it does not work for me, on the other hand, it needs to change `AppDelegate.m` so I think we are not be able to add this feature to this package.
