### ISSUE TITLE
Can I use fetch-blob replace React Native Image uri ?

### ISSUE THREAD

**Issue by eggeggeg** [wkh237/react-native-fetch-blob#200]
```
<Image
   style={{width: 100, height: 100}}
   source={{uri: 'https://192.168.x.x.png'}}  // or  source={fetch blob result} 
/>

return RNFetchBlob.config({
      trusty : true
    })
    .fetch(
      'GET',
      `https://192.168.x.x.png`,
      {
        'Content-Type': 'application/x-www-form-urlencoded' //I'm not sure to use this
      }
    )
    .then(response => {
    })
    .catch(error => {
    });
```
I use React Blob trusty props ,but React Native Image uri does not support trusty, how do I use React Blob access to the image and stored in React Image ?

**Comment by wkh237** [comment]
@eggeggeg , if you're going to use an image in storage be sure to add `file://` prefix on Android (ios does not need the prefix).

**Comment by eggeggeg** [comment]
@wkh237
My image is from the network, because the server certificate is private, so the default Image uri will be blocked off

My final solution is to convert the image to base64
http://stackoverflow.com/questions/29380265/does-react-native-support-base64-encoded-images

Thanks you
