### ISSUE TITLE
Documentation for RNFetchBlob.fs.readStream has arguments in the wrong order.

### ISSUE THREAD

**Issue by AC-FTW** [wkh237/react-native-fetch-blob#204]
The readStream method is documented with arguments in the following order: encoding, file path, buffer size.

The actual order should be: file path, encoding, buffer size. Otherwise users will get an error saying that their a file named <whatever they set encoding to> is not found.

**Comment by wkh237** [comment]
@AC-FTW , thanks for point out this problem, I'll change the document 😄

**Comment by stobe1** [comment]
@wkh237 
you should actually fix that. Just spent 30 mins trying to figure out whats going on
