### ISSUE TITLE
Android Post 'Content-Type': 'multipart/form-data' issue

### ISSUE THREAD

**Issue by BernardDoherty** [wkh237/react-native-fetch-blob#208]
Hi,

I've been using the RNFB successfully for ios devices but have run in to a problem getting the same code to work on Android. When I do a Post, 'Content-Type': 'multipart/form-data' the format of the parameters are different on Android then ios. 

//ios
"consumer_id"=>"45555000"

//Android
 "consumer_id\r\nContent-Type: text/plain\r\n"=>"45555000"

What can I do to remove:   "\r\nContent-Type: text/plain\r\n" 

//example code

  RNFetchBlob.fetch('POST', path ,{
    'Authorization': access_token,
    'Content-Type': 'multipart/form-data'
  },[
    {name: 'api_attachment', filename: 'new_100001.jpg', type: 'image/jpeg', data: RNFetchBlob.wrap(file_path)},

    {  name : 'consumer_id',  data :  '45555000',},

  ]).uploadProgress((written, total) => {

**Comment by wkh237** [comment]
@BernardDoherty , which version of react-native-fetch-blob you're using ? I'm  not be able to reproduce this problem on my end. It'd be helpful if you can provide a working sample 😄

**Comment by BernardDoherty** [comment]
I was using 0.10.0 and on Friday I updated to 0.10.1-beta.3. I have the same issue with both versions. Here is a code sample below.  Thanks for looking.  

async function uploadAttachment(consumer_id, original_filename, file_path, title, description, categories_text=[], callback) {
  var path = Constants.SERVER_PATH_V2 + '/attachments'
  var auth = Authentication.getAuth()
  var tags = categories_text.toString()
  if (auth != null) {
    access_token = auth.token_type + ' ' + auth.access_token
  }
  RNFetchBlob.fetch('POST', path ,{
  'Authorization': access_token,
  'Content-Type': 'multipart/form-data'
},[
  {name: 'api_attachment', filename: 'new_100001.jpg', type: 'image/jpeg', data: RNFetchBlob.wrap(file_path)},
  {name : 'consumer_id', data :  '45555000'},
  {name : 'title', data : title},
  {name : 'message_content', data : description},
  {name : 'tags', data : tags},

]).uploadProgress((written, total) => {
  // console.log('uploaded', written / total)
}).then((resp) => {  
  callback(null, resp)
}).catch((err) => {
  console.log(err)
  alert("error = " + err)
}) 
}
module.exports.uploadAttachment = uploadAttachment

**Comment by BernardDoherty** [comment]
Hey, I resolved my issue related to my server code. Thanks.

**Comment by stinju** [comment]
@BernardDoherty, I'm hitting the same issue, so I might have a similar setup.  Any insight would be greatly appreciated.  Thanks!

**Comment by BernardDoherty** [comment]
@stinju  I upgraded to the latest react-native-fetch-blob@0.10.1-beta.3.  Looks like this issue was resolved in version v0.10.1-beta.1.

**Comment by stinju** [comment]
Thanks @BernardDoherty, react-native-fetch-blob@0.10.1-beta.3 resolves the issue for me as well.
