### ISSUE TITLE
Download progress reporting can be flakey (ios)

### ISSUE THREAD

**Issue by Thomas101** [wkh237/react-native-fetch-blob#210]
Version: 0.10.0

I've been playing with the library and I've noticed that sometimes (maybe 50% of the time) download progress doesn't get reported. This is re-testing with the same url. I've tested on the simulator (ios10) and on an physical iPad (ios9). Here's the code I was using...

```js
RNFetchBlob
    .config({path : dirs.DocumentDir + '/path-to-file.anything'})
    .fetch('GET', 'http://www.example.com/download', {})
    .progress((received, total) => {console.log('progress', received / total)})
```

After digging through the code I noticed that `RNFetchBlob.m` makes a call to `RNFetchBlobNetwork +enableProgressReport:config:`. This call can sometimes happen before `RNFetchBlobNetwork -init` which means `progressTable` inside `RNFetchBlobNetwork` has not been initialized.

Have you thought about using a singleton for the `progressTable` fields to ensure they're always available? This might help to resolve this issue

**Comment by wkh237** [comment]
@Thomas101 , thanks for the suggestion, will fix this bug and update the status here.
