### ISSUE TITLE
Error: The network connection was lost.(…)

### ISSUE THREAD

**Issue by chrbradley** [wkh237/react-native-fetch-blob#213]
Hello,

I can't get an image uploaded to Cloudinary. When the upload is almost finished it gets interrupted and an error is returned:

```
err:  Error: The network connection was lost.(…)
```

Here are the particulars:
```
"react-native": "^0.38.0",
"react-native-fetch-blob": "^0.10.0",
```

```
    RNFetchBlob
    .config({timeout: 60000})
    .fetch(
      'POST',
      'https://api.cloudinary.com/v1_1/***/image/upload',
      {
        upload_preset: '***',
        'Content-Type': 'application/octet-stream'
      }, RNFetchBlob.wrap(testFile.uri))
    .uploadProgress((written, total) => {
      console.log('uploaded', written / total)
    })
    .then((res) => {
      console.log('res: ', res)
    })
    .catch((err) => {      console.log('err: ', err)
    })
```

![image](https://cloud.githubusercontent.com/assets/5009163/21210229/4ba0c8cc-c247-11e6-8a8c-dad62de41421.png)

I didn't see anything similar in the TS guide but I've been able to upload to the api using `fetch`. I tried `.config({timeout: })`. Low values, < 5000 or so, work, but larger values don't. The error typically appears just before upload completion or immediately after.

**Comment by wkh237** [comment]
@chrbradley , thanks for reporting the issue. Could you try adding this header and see if it works ?

```diff
RNFetchBlob
    .config({timeout: 60000})
    .fetch(
      'POST',
      'https://api.cloudinary.com/v1_1/***/image/upload',
      {
        upload_preset: '***',
        'Content-Type': 'application/octet-stream'
+       'Transfer-Encoding' : 'Chunked',                                                                                                               
      }, RNFetchBlob.wrap(testFile.uri))
    .uploadProgress((written, total) => {
      console.log('uploaded', written / total)
    })
    .then((res) => {
      console.log('res: ', res)
    })
    .catch((err) => {      console.log('err: ', err)
    })```

**Comment by chrbradley** [comment]
I've experimented with different timeout values including 60000. Larger
values don't help.  The connection always closes right around 99%
 completion. I can upload using fetch without issue.

**Comment by wkh237** [comment]
@chrbradley , sorry about late responding. I've made some tests on Cloudinary upload API and can successfully upload a large image (~2MB) using `multipart-formdata` request.

```js
    let task = RNFetchBlob.fetch(
      'POST',
      'https://api.cloudinary.com/v1_1/xeipsnjp/image/upload',
      [{
        name : 'file',
        filename : 'cat.png',
        data: RNFetchBlob.wrap(res.path()),
      }, {
        name : 'upload_preset', data: 'jrkbliez'
      }])

    task.uploadProgress((written, total) => {
      console.log('uploaded', written / total)
    })

    task.then((res) => {
      console.log('res: ', res)
    })
    .catch((err) => {
      console.log('err: ', err)
    })

```

here's the logs 

<img width="905" alt="2016-12-30 10 45 46" src="https://cloud.githubusercontent.com/assets/5063785/21558922/41890de4-ce7d-11e6-8e58-9db6f1a4636a.png">

Could not find information about how to use`octet-stream` upload images, also when I use the code you provide, the request fails around 99% but it gives me different error message. 

<img width="603" alt="2016-12-30 10 33 28" src="https://cloud.githubusercontent.com/assets/5063785/21558935/7a5a63a2-ce7d-11e6-8622-2559e01d2d05.png">

Could you help confirm this ? Thanks

**Comment by chrbradley** [comment]
@wkh237 I finally got an opportunity to try this and can confirm that it works. Thank You!

**Comment by ashusdn** [comment]
@wkh237 / @chrbradley ,

I have also got same error when uploading file, I am trying same way as describe above but after 
uploaded 0.22847261926343237
  Error: The request timed out.

Can you please provide me any solution regarding this.
