### ISSUE TITLE
Cached images don't display in iOS

### ISSUE THREAD

**Issue by klinkov** [wkh237/react-native-fetch-blob#216]
```
    "react": "15.4.1",
    "react-native": "0.38.0",
    "react-native-fetch-blob": "0.10.0-beta.4",
```

this is my cache class 
https://gist.github.com/klinkov/31ec7a84de141ae1f1cc7a360daa99a3

this is my render code
```
<CachedImage
   key={'img_' + item.id}
   style={{width: 50, height: 50, resizeMode: 'contain'}}
   defaultSource={placeholder}
   source={item.previewImages.length ?
    {uri: 'https://i.imgur.com/vKRaKDX.png'} :
   false}
/>
```
cache path code
`let target = (Platform.OS === 'ios' ? RNFetchBlob.fs.dirs.CacheDir : RNFetchBlob.fs.dirs.CacheDir) + '/' + md5.hex_md5(request_options.uri);`

On Android i see images from Cache
http://take.ms/MFD9i

but on IOS i see default image, but cached image exist
http://take.ms/7vkJv

PS
This is console log
```
this.props { style: { width: 50, height: 50, resizeMode: 'contain' },
  defaultSource: 1,
  source: { uri: 'https://i.imgur.com/vKRaKDX.png' } }
source { uri: '/Users/shade/Library/Developer/CoreSimulator/Devices/8AF7DE65-D6F1-42E5-BBF3-C54A850B47B3/data/Containers/Data/Application/78141712-5FC0-4E03-9258-4E0F4542B529/Library/Caches/38e7ca9375809b4ef096d278707e45aa' }
```

**Comment by wkh237** [comment]
@klinkov , try to append extension to the file, for example `.png` or `.jpeg` and see if that works 😄

**Comment by klinkov** [comment]
@wkh237 That is magic :)
Thank you!
