### ISSUE TITLE
Manual Instalation

### ISSUE THREAD

**Issue by kingadrianzghibarta** [wkh237/react-native-fetch-blob#219]
I can not find any manual installation instructions for Android and iOS, could you please add this in git/npm description?

**Comment by wkh237** [comment]
@kingadrianzghibarta , does the [Manually Link Package](https://github.com/wkh237/react-native-fetch-blob/wiki/Manually-Link-Package) page fits your need ?

**Comment by kingadrianzghibarta** [comment]
@wkh237 yes, it's what I am looking, thanks for the link. By the way, it's a very good exemple of how to write a documentation.
