### ISSUE TITLE
Set Content-Length on POST (body as-is, iOS)

### ISSUE THREAD

**Issue by jbrodriguez** [wkh237/react-native-fetch-blob#221]
@wkh237 awesome work !

The library is only growing more useful every day.

I do have to say that I'm having a problem with x-www-form-urlencoded POST operations on iOS (running 0.10.1-beta.2, Android works fine), since I'm not receiving the query params on the server side.

In this line, https://github.com/wkh237/react-native-fetch-blob/blob/master/src/ios/RNFetchBlobReqBuilder.m#L145

size is unused.

As soon as I set Content-Length with size, I start getting the query params.

```objective-c
size = [body length];
[request setHTTPBody: [body dataUsingEncoding:NSUTF8StringEncoding]];
[request setValue:[NSString stringWithFormat:@"%u", [body length]] forHTTPHeaderField:@"Content-Length"];
```
This works for me.

It's a small change, but I was wondering if you deliberately weren't setting the length for some reason

**Comment by wkh237** [comment]
@jbrodriguez , thanks for reporting this issue, from my understanding the `Content-Length` header will automatically added when the body is added when `request:setHTTPBody` (see #94), I'll do some test and report result here.

**Comment by jbrodriguez** [comment]
@wkh237 great !

I'm posting some query params sent to the library as a string (not a multipart post).

I'll double check as well.

Just a note, on the Android side, you do set content-length explicitly (even if they are different libraries and all)

https://github.com/wkh237/react-native-fetch-blob/blob/master/src/android/src/main/java/com/RNFetchBlob/RNFetchBlobBody.java#L75

**Comment by wkh237** [comment]
Yeah, on Android we have to set `Content-Length` ourself but on IOS it's automatic. I've run some test but unable to replicate the problem you addressed. Any idea ?

**Comment by jbrodriguez** [comment]
Thanks wkh237.

Not many ideas, I'll wait for the update to RN 0.40 and try again.

Closing this one for now.
