### ISSUE TITLE
Multipart/form-data request for file upload

### ISSUE THREAD

**Issue by plkt1792** [wkh237/react-native-fetch-blob#222]
Hey @wkh237,
I was implementing file upload in my app as per
https://github.com/wkh237/react-native-fetch-blob#user-content-multipartform-data-example--post-form-data-with-file-and-data

The issue is with any other element **without** `filename` field. 
In the request, it appends `\r\nContent-Type: text/plain\r\n` in the keyname. 
Like if my element is `{ name: "userName", data: "Jon"}`
It gets converted to `"userName\r\nContent-Type: text/plain\r\n"=>"Jon"` in the request.

This is causing the key extraction on server side difficult.
I need to know, is this behavior expected and how it should be parsed.

Any help is greatly appreciated.

Thanks.

**Comment by wkh237** [comment]
@plkt1792 , will look into this issue, does it happens on both IOS and Android ?

**Comment by plkt1792** [comment]
I'm working on Android only.

**Comment by wkh237** [comment]
It's similar to #208 , could you try upgrade to `0.10.1-beta.3` ?

**Comment by plkt1792** [comment]
Great! Works fine now. 
Thanks a lot. 
👍
