### ISSUE TITLE
[RN 0.40] Update iOS header imports

### ISSUE THREAD

**Issue by jpgarcia** [wkh237/react-native-fetch-blob#223]
The headers are now under a directory called "React" that is in the compiler's include path.

This is a RN breaking change as described [here](https://github.com/facebook/react-native/releases/tag/v0.40.0) so consider this to bump a new version.

**Comment by wkh237** [comment]
@jpgarcia , Thanks for the heads up, have also noticed this change and considering if there's a better way to make the change backward compatible 😏

**Comment by jpgarcia** [comment]
Great! 

I forked the repo to perform the update (at least to be able to update the package on my side for now) but it was a PITA to get it running I think that could be related with the 0.10 `dev` status of the package :( will wait your update then.

**Comment by wkh237** [comment]
Have already published a release `0.10.2-beta.2` to npm, upgrade the package 

```sh
$ npm install --save react-native-fetch-blob@0.10.2-beta.2
$ react-native link
```

The fix should make RNFB compatible to 0.40 and existing projects, please verify if it works as expected 👍

**Comment by binchik** [comment]
@wkh237

In RNFetchBlob.h:

```
#import "<React/RCTBridgeModule.h>"
```

I think double quotes should be removed.

**Comment by binchik** [comment]
@wkh237 Hi! It worked when I removed double quotes from every import having "<" or ">"

**Comment by binchik** [comment]
@wkh237 Thanks for the patch! It works if only you remove double quotes from every import with "<...>"

**Comment by wkh237** [comment]
@binchik , thanks for the remind, have fixed and published `0.10.2-beta.3` to npm, please help verify the fix.

**Comment by mrKlar** [comment]
Hi, I tested the beta 3, but no luck, it does not work for me.

Duplicate interface definition for class 'RCTBridge'

**Comment by wkh237** [comment]
@mrKlar , thanks for the test, just applied a fix and tested on 0.40 project, please try use the latest version on npm `0.10.2-beta.4`

**Comment by mgiachetti** [comment]
It's working fine for me but only when commented the def line like mrklar said.
You should leave that line commented for next version.

**Comment by leesolway** [comment]
Tested 0.10.2-beta.4

node_modules/react-native/React/Base/RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge'

**Comment by leesolway** [comment]
Tested with "react-native-fetch-blob": "0.10.2-beta.4",

/node_modules/react-native/React/Base/RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge'

**Comment by wkh237** [comment]
@leesolway , thanks for the feedback. I have tested the on pure RN 0.40 project for several times and it's working good on my end. 

```sh
$ react-native init rn040
$ npm install --save react-native-fetch-blob@beta
$ react-native link
```

If you have installed previous versions before, please remove it ( both react-native-fetch-blob folder in `node_modules` and the entry in `package.json` ). If there's another good way to make it backward compatible please let me know, thanks 👍

**Comment by mgiachetti** [comment]
@wkh237 thanks.
I removed the folder and called react-native link again and it worked.

**Comment by mgiachetti** [comment]
@wkh237 it's working fine.
But with this change we'll have to call react-native link every time we update this library or after a clean instal. This is something we are not doing. We only call react-native link once for new libraries.
I think you could change the code replacing OLD_IMPORT to NEW_IMPORT then in prelink.js you check the version <40 not >= 40 and remove NEW_IMPORT in the same way as now.
Doing this you have backward compatibility without breaking the new versions of react native.

**Comment by wkh237** [comment]
@mgiachetti , thanks for the advice, sounds pretty reasonable 👍  I'll change this part and release another version.

**Comment by wkh237** [comment]
I have changed the prelink script in `0.10.2-beta.6` please verify the fix, thanks.

**Comment by jsappme** [comment]
I still get /RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge' with 0.10.2-beta.6

**Comment by mgiachetti** [comment]
@wkh237 In 0.10.2-beta.6 you still need to call react-native link every time you update the library.
please check if #235 works for you.

**Comment by DylanVann** [comment]
For projects with multiple team members requiring a call to `react-native` link on every install is an issue.

I think:

1. Checkout project.
2. `yarn` or `npm install`
3 `react-native run-ios`

Is a common workflow that should be supported.

**Comment by wkh237** [comment]
Already published to npm, please upgrade the packge to `0.10.2-beta.7` and verify if it works, thanks !

**Comment by wkh237** [comment]
`0.10.2-beta.7` is broken, please use 0.10.2-beta.8 instead

**Comment by plougsgaard** [comment]
@wkh237 having no issues with beta8 on 0.40 👍
