### ISSUE TITLE
uploadProgress it's no called on first upload

### ISSUE THREAD

**Issue by neiker** [wkh237/react-native-fetch-blob#225]
First upload after open the app don't fire uploadProgress callback. We fix it be doing this: `RNFetchBlob.fetch('GET', 'https://localhost');`. after RNFetchBlob include. This happen on iOS at least.

**Comment by wkh237** [comment]
@neiker , thanks for the heads up, I have applied fix to this issue in `0.10.2-beta.5` please upgrade and verify if it's fixed 👍

**Comment by neiker** [comment]
Awesome! I'll try it.

Thanks!

**Comment by neiker** [comment]
Works like a charm!
