### ISSUE TITLE
RNFetchBlobStat `lastModified` date is incorrect

### ISSUE THREAD

**Issue by cooperka** [wkh237/react-native-fetch-blob#227]
I'm getting very old dates from `fs.stat` for `lastModified`, such as `130216976` (which is [`Sat, 16 Feb 1974 03:22:56 GMT`](http://www.onlineconversion.com/unix_time.htm) in unix time). Any idea why this might be occurring?

Update: Actually this number `130216976` is **always** returned, no matter when the file was actually modified. Very weird.

My specs:

- fetch-blob `v0.10.1`
- iOS 10.1 simulator
- OSX

It seems to work perfectly fine on Android (though it's in milliseconds instead of seconds).

---

Side note: The [wiki docs](https://github.com/wkh237/react-native-fetch-blob/wiki/Classes#rnfetchblobstat) showed that the values returned are numbers, when in fact they are strings. There's no way to make a PR to the wiki, so I've updated it directly. Hope that's okay!

**Comment by wkh237** [comment]
@cooperka , thanks for the heads up. I'm already working on this issue, will also change the type of `lastModifed` to number as it's easier to use.

**Comment by cooperka** [comment]
@wkh237 thanks for the update, good to know 👍
