### ISSUE TITLE
Is it possible to declare NSURLIsExcludedFromBackupKey when using fs.mkdir()

### ISSUE THREAD

**Issue by aforty** [wkh237/react-native-fetch-blob#229]
I don't see this documented or in the source. Is there any way to do this after the fact?

If not, would you accept a PR for this? I'm thinking an optional options that could be passed to `fs.mkdir(path: String, options: Object?)`. I'm not familiar with Android, so I'm not sure if there is something equivalent to this flag but if not the object could just be ignored there.

`fs.mkdir('/some/path', { NSURLIsExcludedFromBackupKey: true })`

Thoughts?

**Comment by wkh237** [comment]
@aforty , there's no way to do this so far, it'd be great if you can make a PR 😄

**Comment by wkh237** [comment]
@aforty , I've added an IOS only API `RNFetchBlob.ios.excludeFromBackupKey`, please upgrade to `0.10.2-beta.8` to verify it.
