### ISSUE TITLE
[iOS] Config option: requestCachePolicy

### ISSUE THREAD

**Issue by Meshz** [wkh237/react-native-fetch-blob#249]
I'm trying to auth my user to SharePoint. It is working fine in Android but I'm facing a problem in iOS.

One of the requests for auth uses several redirects which set cookies. The first time I sign in, all the redirects are followed but the second time, I'm going straight to the last redirect and then some cookies are not set. I can confirm this by cleaning the iOS simulator (`xcrun simctl erase all`) and it is working fine again the first time only.

I found this [link](http://blog.gregfiumara.com/archives/234) exposing the `requestCachePolicy` parameter (also this [one](https://blackpixel.com/writing/2012/05/caching-and-nsurlconnection.html) describing a bit more). I tried to set `defaultConfigObject.requestCachePolicy = NSURLRequestReloadIgnoringLocalCacheData` in _RNFetchBlobNetwork.m:250_ but it does not seem to work. As I have never used Objective-C I may be missing something.

Thank you for your help and time.

**Comment by wkh237** [comment]
Try add Cache-Control : no-store to headers.

**Comment by Meshz** [comment]
@wkh237 Thank you for that suggestion but this doesn't solve my problem.

After deeper tests, I saw that the fedAuth cookie received on first login is kept and resend when logging back again. This is why the redirects are different. This behavior is not the same than in Android.

Is there any way to get/remove the cookies stored in RNFB? If not, I can check the last redirect and switch to the last part of auth if user already have a token. So this issue can be marked as solved.
