### ISSUE TITLE
readFile on android

### ISSUE THREAD

**Issue by naviocean** [wkh237/react-native-fetch-blob#252]
Hello,
I got a trouble when using fs.readFile with encoding is utf8.
```
RNFetchBlob.fs.readFile(path, 'utf8').then((data) => {                
      socket.emit('Upload', { 'Name' : filename, Data : data });
})
```
It read file to string and then send to server via socket io.
On server, Im using fs.write(filename,data,null,'binary') to storage file.
ps:It only works fine on ios.
Thanks,

**Comment by wkh237** [comment]
@naviocean , I think this is similar to #247. As an alternative, you can read the file into `base64` encoded string and write the string this way on server  

```js
fs.write(dest, base64Str, {encoding: 'base64'}, function(err) {
  // callback
})
```

**Comment by naviocean** [comment]
I've just change to base64
```
RNFetchBlob.fs.readFile(source.uri, 'base64').then((data) => {
              socket.emit('Upload', { 'Name' : filename, Data : data });
            });
```
and backend change to
`fs.write(path, data['Data'], {encoding: 'base64'}, function(err) { .. });`
However, the new image file is incorrect, can not see.

**Comment by naviocean** [comment]
I've change a litte on my backend and now it works fine.
Thanks for your support
