### ISSUE TITLE
How to cancel the HTTP Request on a button click

### ISSUE THREAD

**Issue by nehalahmad** [wkh237/react-native-fetch-blob#258]
Hi,

In my react native application, I am sending request to insert data into server db in a promise. And on screen, there is one cancel button also. When user click on it, I have to cancel the HTTP request and on callback, I have to perform some logical operations to manage something locally on mobile.

And also when click on cancel button, I have to call Actions.pop() after doing some logical operations.

Please suggest that how can I do that if I use React Native Fetch Blob.

Thanks in advance.

**Comment by wkh237** [comment]
@nehalahmad , have you checked our wiki? You can do this with [StatefulPromise.cancel](https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#fetchcanceleventlistenerpromisernfetchblobresponse).
