### ISSUE TITLE
react-native-code-push update check fails

### ISSUE THREAD

**Issue by atlanteh** [wkh237/react-native-fetch-blob#259]
Hi,
we've just tried to upgrade rnfb to from (0.9.5) to latest version (0.10.2) and suddenly our react-native-code-push stops working and emits the following error: 
Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.

react-native-code-push checks for updates on app load, and your latest version somehow breaks it.
When reverting back to 0.9.5, react-native-code-push starts working again.

react-native: 0.41.2

**Comment by wkh237** [comment]
@atlanteh , I think this is the same issue as #205 and it only happens when debug mode is turned on. The error is from the packager, still finding the solution.

**Comment by josehernandezv** [comment]
@wkh237  when you say it only happens when debug mode is turned on you mean debug Js remotely mode? I have try it with debug mode turned off and I still get the error
