### ISSUE TITLE
Responses come back but callback is never called

### ISSUE THREAD

**Issue by PimDeWitte** [wkh237/react-native-fetch-blob#26]
Hey, I'm seeing a strange issue on Android when I try to use this lib.
<img width="1261" alt="screen shot 2016-06-14 at 9 59 44 am" src="https://cloud.githubusercontent.com/assets/8763534/16051957/d9340710-3216-11e6-9795-83e7a551ab43.png">

I'm working on an application that needs to download images from the web, and store them on device. However, as you can see, the process is completed by AsyncHTTP, but the callback itself is never called. 

My code:

RNFetchBlob
                            .config({
                                fileCache: true,
                                path : fileName
                            })
                            .fetch('GET', tile.url, {})
                            .then((res) => {
                                console.log("Saved to " + res.path())
                                processedTiles++;
                                if (processedTiles >= tilesToBeProcessed) {
                                    parent.onTileProcessed(card, index);
                                }
                            });

**Comment by wkh237** [comment]
Hi @PimDeWitte , thanks for your informing. I am looking into this issue, but I need some time. Besides, I noticed that your `config` have both `fileCache` and `path` property, if you're going to save the file to an absolute path, the `fileCache` property won't be necessary. `fileCache` property means it will use a temp path, by design, it will be ignored when `path` has value : )

**Comment by PimDeWitte** [comment]
I figured it out. The GET parameters are not respected in android

e.g.

http://google.com?q=X will be sent properly on iOS, but will be sent as http://google.com on android @wkh237

**Comment by PimDeWitte** [comment]
@wkh237 any direction where I could look? Pretty urgent for me to get this fixed. This is so much better then the react-native-fs lib :-)

**Comment by wkh237** [comment]
@PimDeWitte , great thanks for your information! Looks like I added params twice on Android. So the server doesn't response as expect.

I've just solved this issue but it's based on `0.5.2` branch, the IOS HTTP implementation is quite different from previous version, if you're going to fix it base on `0.5.1` please check [here for the implementation](https://github.com/wkh237/react-native-fetch-blob/commit/cc52ad4ba05fe90105dd8ba7985002988eebff24) and [here for the test cases](https://github.com/wkh237/react-native-fetch-blob/commit/0f9c03b15713c99f656d312f01e3891977fb8e9e).

I will publish `0.5.2` once I finished updating the README.md.

**Comment by PimDeWitte** [comment]
@wkt
thanks so much!
