### ISSUE TITLE
Could not find class 'okio.Buffer'

### ISSUE THREAD

**Issue by agumack** [wkh237/react-native-fetch-blob#262]
Hi, Thank you for great lib.
It working fine on IOS, but i have get a error on android:

> Could not find class 'okio.Buffer', referenced from method okhttp3.internal.Util.toHumanReadableAscii

Thanks for support!

* React-native: 0.37
* "react-native-fetch-blob": "^0.10.3",

**Comment by wkh237** [comment]
@agumack , please try add Gradle dependency as describe in #217

**Comment by agumack** [comment]
Hi @wkh237 add at node-modules/react-native-fetch-blob/src/android/build.gradle ?
i tried but not working

**Comment by wkh237** [comment]
Have you used other packages where explicitly specifying OkHttp's version? If so, Gradle will use that one and cause this error [pre this](https://github.com/square/okhttp/issues/2297).
