### ISSUE TITLE
Parallel downloads in IOS are broken

### ISSUE THREAD

**Issue by francisco-sanchez-molina** [wkh237/react-native-fetch-blob#263]
When I launch multiple downloads, the promises are mixed. Especially when some downloads return 404. Example code:

```javascript
download(url) {
RNFetchBlob
  .config({
    timeout: 7000,
    path: destination
  })
  .fetch('GET', url, this._getHeaders())
  .then(resp => {
    if (url !== resp.info().redirects[0]) {
      console.warn('bug!')
    })
}

['url1', 'url2', 'notFoundUrl3'].forEach(url => download(url))
```

Thanks

RN 0.41.2
RNFB all versions

**Comment by wkh237** [comment]
@francisco-sanchez-molina , thanks for reporting this issue. I can replicate it on my end.

**Comment by wkh237** [comment]
@francisco-sanchez-molina, I've applied a fix t to this issue, please upgrade your package from our archive repo and help verify it, thanks 👍 

```
$ npm install --save wkh237/react-native-fetch-blob-package#0.10.3-fix-263
```

**Comment by francisco-sanchez-molina** [comment]
Thanks a lot! I check the fix, and now it works like a charm!!
