### ISSUE TITLE
.config({ path }) and .abort()

### ISSUE THREAD

**Issue by wcandillon** [wkh237/react-native-fetch-blob#270]
Hello,

I'm implementing an Image pipeline using RN `ListView`. When a row becomes invisible and it had a pending request for it, I would like to cancel that request.

`fetch` doesn't have `abort()`. `XMLHttpRequest` has an `abort()` method but it doesn't seem to be possible to use it with `RNFetchBlob.config({ path })` in order to avoid bridging the image to the JS space.

How would you recommend that I tackle this issue?

**Comment by wkh237** [comment]
@wcandillon , does [fetch.cancel](https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#fetchcanceleventlistenerpromisernfetchblobresponse) work for you?

**Comment by wcandillon** [comment]
@wkh237 It works great thank so much for your support, my apologies for missing it from the docs.

**Comment by wcandillon** [comment]
@wkh237 I described the approach taken [here](https://medium.com/@wcandillon/image-pipeline-with-react-native-listview-b92d4768b17c).

**Comment by wkh237** [comment]
All good, feel free to file an issue anytime 👍
