### ISSUE TITLE
File path change btw sessions causing retrieval failure 

### ISSUE THREAD

**Issue by natashache** [wkh237/react-native-fetch-blob#275]
Hi,
I'm using react-native-fetch-blob to download mp3 files to phone and then playing them later. The problem is that the actual path for `RNFetchBlob.fs.dirs.DocumentDir` changes when I close the app and restart again, which means I can't use the absolute file path I stored right after downloading the files retrieve the files in the next run of the app.

Here's my code for downloading and storing the file paths:
```
export function downloadAudio(urlArray) { //download every section in the urlArray
  return (dispatch) => {
    Promise.all(urlArray.map(section => {
      dispatch(startDownload(section.section_id))
      console.log('download start for id = ',section.section_id ) //start download
      return RNFetchBlob
      .config({
        path: RNFetchBlob.fs.dirs.DocumentDir + '/courseSections/' + section.section_id + '.mp3',
        appendExt: 'mp3'
      })
      .fetch('GET', section.section_url, {
        'Cache-Control': 'no-store'
      })
      .progress({ count: 10 }, (received, total) => {
        console.log(`progress for section ${section.section_id}: `, Math.floor(received/total*100), '%')
        dispatch(downloadProgress({id: section.section_id, progress: Math.floor(received/total*100)/100}))
      })
      .then(res => {
        console.log(`section ${section.section_id} is saved to: `, res.path())
        return { path: res.path(), id: section.section_id }
      })
      .then(pathInfo => dispatch(downloadSuccess(pathInfo))) //download finished
    }))
      .catch((error, statusCode) => {
        console.log(statusCode, ' error: ', error)
      })
  }
}
```
I stored `{ path: res.path(), id: section.section_id }` as part of persisted app state. But it's not useful cuz next time I open the app, the file path has been reassigned. For example, here's the path one file was downloaded to:
![screenshot 2017-03-03 11 06 18](https://cloud.githubusercontent.com/assets/19754530/23559242/52ed0186-0004-11e7-9fbf-8fff5475d973.png)

But after I close the app and restart, the path is changed to:
`/Users/NatashaChe/Library/Developer/CoreSimulator/Devices/830778DE-3CE3-4FC7-AA4B-DFBAE999751C/data/Containers/Data/Application/0C47E33F-ACF8-4539-9456-8FF3E8FBECB2/Documents/courseSections/14.mp3`

i.e. the files got assigned to a different sub-folder under the `Application` folder.

Obviously the audio player (I'm using react-native-sound) can't find the file using the original path that the app has stored. So my question is: Is there a way I can fix the path? Or is there some other way of retrieving files that I'm not aware of? 

And also, I haven't tried this on the phone yet. Does anyone know if the above code can be directly used on iphone or shall I set the file path in any other way?

I'm using the iOS simulator, with react native 0.41.

**Comment by wkh237** [comment]
From my understanding, this only happens in sandbox mode, the app's home folder (DocumentDir) should not change on a real device. 

However, we can still improve this for better development experience.
