### ISSUE TITLE
a bug on the 256GB iOS device 

### ISSUE THREAD

**Issue by Sky891028** [wkh237/react-native-fetch-blob#276]
function 
`df();`
`callback(@[[NSNull null], @{
                  @"free" : [NSString stringWithFormat:@"%d", totalFreeSpace],
                  @"total" : [NSString stringWithFormat:@"%d", totalSpace]
                }]);`
will callback the wrong value
`callback(@[[NSNull null], @{
                  @"free" : [NSString stringWithFormat:@"%ld", totalFreeSpace],
                  @"total" : [NSString stringWithFormat:@"%ld", totalSpace]
                }]);`
it work fine!

**Comment by wkh237** [comment]
@Sky891028 , the fix already added to branch `issue-276`, please try install the package from the branch and see if it works.
