### ISSUE TITLE
How to stop readStream when reading huge file and start reading a file at specific position?

### ISSUE THREAD

**Issue by newhalo** [wkh237/react-native-fetch-blob#279]
Hi! I'm trying to upload huge files in chunks to my server by using readStream and fetch data to server, my app will allow to pause uploading, I'm looking for a way to stop the opening readStream (readStream still reading for a long time, to the end of file), when user press resume, how can i start reading a file by readStream at specific position (from byte != 0)!

Sorry about my bad English!
Thanks very must!

**Comment by wkh237** [comment]
@newhalo , this is not supported yet but we're planning to add this in the future version. 

Refer to #124

**Comment by MarkMurphy** [comment]
I'm Looking this functionality as well
