### ISSUE TITLE
Converting a normal(from the project folder) image file to a blob from 

### ISSUE THREAD

**Issue by TheMarsGuy** [wkh237/react-native-fetch-blob#289]
I mean to ask, is it to possible to use a path like './anImage.png', where anImage.png is in the same folder as index.ios.js. Basically I am not trying to use an image from the device, but an image from the project folder.
`Blob.build(RNFetchBlob.wrap('RNFetchBlobfile://Users/Random/aUser/aProject/anImage.png'),type : 'image/png' })
    .then((blob) => console.log("Hello"))
     .catch((err) => console.log(err))
`

**Comment by wkh237** [comment]
@TheMarsGuy , yes it's possible please refer to [the document](https://github.com/wkh237/react-native-fetch-blob/wiki/Web-API-Polyfills-(experimental)#constructordata-options)
