### ISSUE TITLE
Self signed certificates

### ISSUE THREAD

**Issue by KyKyPy3** [wkh237/react-native-fetch-blob#29]
Hi. I tried to use your library and get a problem if the site uses self signed certificate. Do you have any solution for that?

**Comment by wkh237** [comment]
Hi @KyKyPy3 , thanks for your report, I will try to add an option for that.

**Comment by wkh237** [comment]
Hi @KyKyPy3 , I've published a new version (`v0.5.3`) with an option added to `config`, so that you can create connection to a self-signed server 

```js
RNFetchBlob
.config({
    trusty : true // <---add this
})
.fetch('GET', 'https://www.myserver.com/item/')
```
please try if this solve the problem.

**Comment by KyKyPy3** [comment]
Hello. I verify your fix and it works. Many thanks for the quick response.

**Comment by jdpenuliarkorefabrik** [comment]
Where do I put this code? please reply at jdpenuliar@korefabrik.com or jaydz.penuliar@gmail.com thank you very much guyysss. starter on react-native here

**Comment by anhichang** [comment]
Is it possible to read thumbprint/fingerprint of the certificate?
