### ISSUE TITLE
Setting any http headers results in immutable issue.

### ISSUE THREAD

**Issue by Kaishley** [wkh237/react-native-fetch-blob#290]
**RN Version**: 0.42.0
**RNFB Version**: 0.10.2 (latest)
**Issue on**: iOS only. (Android working)

**NOTE**: RNFB version **0.10.0** is working.

**Problem**:
![image](https://cloud.githubusercontent.com/assets/7120747/23995728/35bb1638-0a64-11e7-8290-34de6383a8e9.png)

**Code**:

```
this.http_headers = {
  'authorization': 'Bearer ' + this.props.user.token,
  ...Network.device_info_headers
};

RNFetchBlob.config({session: 'images', fileCache: true, appendExt: 'png'})
  .fetch('GET', this._signatureUrl(intervention.user_sign_logo_id), this.http_headers)
```

**Comment by wkh237** [comment]
@Kaishley , I've fixed this issue. You can now install the package from branch `issue-290` and verify if it works 👍

**Comment by Kaishley** [comment]
Getting new errors on both devices now.

**iOS**
![simulator screen shot 20 mar 2017 09 29 59](https://cloud.githubusercontent.com/assets/7120747/24089508/e15cc2fe-0d50-11e7-95ea-26cef819a692.png)

**Android**
![screenshot_20170320-093009](https://cloud.githubusercontent.com/assets/7120747/24089522/f4619712-0d50-11e7-8dc3-55e20d30b38f.png)

**Comment by wkh237** [comment]
Okay, I've just changed the way it process headers, please try again, thanks.

**Comment by Kaishley** [comment]
Working on both devices. Cheers.
