### ISSUE TITLE
On Android 7.0, ";BASE64" is not stripped from the Content-Type in the final request

### ISSUE THREAD

**Issue by damjoh** [wkh237/react-native-fetch-blob#293]
RNFetchBlob.fetch(
       'PUT',
        uploadUrl,
        { 'Content-Type': 'image/jpeg;BASE64' },
        imageData
    )

The point of the ;BASE64 suffix here is to set react-native-fetch-blob's decoding mode. It does not belong in the Content-Type of the final request. This causes issues with servers that whitelist Content-Type or treat ;BASE64 as a genuine Content-Type parameter.

Ideally there would be a way of setting the decoding mode that doesn't involve overloading the meaning of standard HTTP headers.

**Comment by wkh237** [comment]
@damjoh , from my understanding the server should not blacklist lower-cased `content-type` header field per [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2).

> **3.2.  Header Fields**
>
>   Each header field consists of a case-insensitive field name followed
>   by a colon (":"), optional leading whitespace, the field value, and
>   optional trailing whitespace.

[whatwg-fetch](https://github.com/github/fetch/blob/master/fetch.js#L109) also lowercasing all headers before sending them.

**Comment by damjoh** [comment]
@wkh237 To be clear: I am talking about servers that whitelist the *contents of* Content-Type. For example, an image upload endpoint might allow "Content-Type: image/jpeg" but not "Content-Type: image/jpeg;BASE64"

**Comment by wkh237** [comment]
@damjoh , thanks for the explanation. I think the library should have striped `;base64` suffix [here](https://github.com/wkh237/react-native-fetch-blob/blob/master/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java#L244), will look into it.

**Comment by wkh237** [comment]
I've tried to fix this issue on branch `issue-293` please upgrade the package from this branch see if that works, thanks !
