### ISSUE TITLE
Android App crashes with DownloadManager when Endpoint returns 403

### ISSUE THREAD

**Issue by manuelkch** [wkh237/react-native-fetch-blob#296]
Are there any option to catch 403's from fetch with Android Download Manager? 
The problem is that at the moment of the fetch call i'm not pretty sure if my endpoint responses with a valid 200. Do i have to check the endpoint manually before trying to download my binary with the DownloadManager?

**Comment by wkh237** [comment]
@manuelkch , I've added error handling to Android DownloadManager, could you please verify it?

To update the package from branch `issue-296`

```
$ npm install --save git://github.com/wkh237/react-native-fetch-blob.git#issue-296
```
