### ISSUE TITLE
iOS PATCH method removes body

### ISSUE THREAD

**Issue by atlanteh** [wkh237/react-native-fetch-blob#306]
I'm using fetch-blob "fetch" polyfill.
When executing the following code in iOS, my server receives empty req.body:  

`fetch('http://myServer.com/test', {method: 'PATCH', body: {test: 1234}});`

when I use POST, it's working fine.

versions
react-native: 0.42.3
react-native-fetch-blob: 0.10.4

**Comment by atlanteh** [comment]
false alarm. it was react-native-debugger.

**Comment by jhen0409** [comment]
https://github.com/jhen0409/react-native-debugger/issues/60 I confirmed it not related to debug mode, should reopen this?

**Comment by atlanteh** [comment]
I'm opening. Thx!

**Comment by wkh237** [comment]
The PR already merged 👍  you can now install the package from branch `issue-306`.
