### ISSUE TITLE
[iOS] Can't build without ARC errors

### ISSUE THREAD

**Issue by jonesdar** [wkh237/react-native-fetch-blob#31]
RNFetchBlobNetwork.m:32:13: ARC forbids synthesizing a property of an Objective-C object with unspecified ownership or storage attribute
RNFetchBlobNetwork.m:35:13: ARC forbids synthesizing a property of an Objective-C object with unspecified ownership or storage attribute
RNFetchBlobNetwork.m:36:13: ARC forbids synthesizing a property of an Objective-C object with unspecified ownership or storage attribute
RNFetchBlobFS.h:18:28: Existing instance variable 'callback' for property 'callback' with unsafe_unretained attribute must be __unsafe_unretained

I'm using 0.5.3.
Is it because I've added the project manually rather then with rnpm and have missed some build flags?

**Comment by jonesdar** [comment]
The properties it's complaining about are:

@property (nullable, nonatomic) RCTResponseSenderBlock callback;
@property (nullable, nonatomic) CompletionHander fileTaskCompletionHandler;
@property (nullable, nonatomic) DataTaskCompletionHander dataTaskCompletionHandler;

**Comment by wkh237** [comment]
Hi @jonesdar , I think this problem is similar to #30 , I'm still trying to reproduce this error, looks like these block properties can't be nullable, if you remove `nullable`  from those properties, do you still get the error ?

**Comment by jonesdar** [comment]
Hello. No that doesn't help. Adding `strong` fixes things though - is that the right thing to do?
It's interesting that you don't see these errors - is it related to the version of Xcode perhaps? I'm using 7.2.

**Comment by jonesdar** [comment]
I think it might be Xcode version related. Our build machine has just built things successfully and it's using Xcode 7.3.

**Comment by wkh237** [comment]
@jonesdar great thanks ! I'm using Xcode 7.3 and I can build it without error, I'll release a version after doing some test.

**Comment by jonesdar** [comment]
Thanks @wkh237. That fixes the 3 errors in RNFetchBlobNetwork.m. The one in RNFetchBlobFS.h is still there though. Adding `strong` to `@property (nonatomic) RCTResponseSenderBlock callback;` seems to fix it.

**Comment by wkh237** [comment]
@jonesdar thank you, Looks like I missed that one in `RNFetchBlobFS.h`, I'll fix that one ASAP.

**Comment by jonesdar** [comment]
Xcode 7.2 build is now working for me. Thanks @wkh237 for the quick turnaround.

**Comment by wkh237** [comment]
@jonesdar you're welcome 👍

**Comment by Pianist038801** [comment]
@wkh237 Hi!  Image-upload to firebase storage using React Native is what I wanna do right now.
   But the same error occurred during the development. I am using XCode 8.3.3.
   I am sure you can figure this out.

**Comment by wkh237** [comment]
@Pianist038801 let me clone the repository and see if there's anything I can help.

**Comment by Pianist038801** [comment]
@wkh237 Oh, I just found a mistake. I fixed it. Thanks for your kindness.
