### ISSUE TITLE
fs.exists() taking over 4000ms to complete

### ISSUE THREAD

**Issue by mmmurf** [wkh237/react-native-fetch-blob#310]
Just curious if this is a normal amount of time for checking the existence of a file on an iPhone 7.  Suggestions for speeding this up or anything I can do to provide a more useful report?

**Comment by wkh237** [comment]
@mmmurf , thanks for reporting the issue. Could you provide the URI of the file? On the other hand, how large is the file ? is it a folder containing lot of files and directories ?
