### ISSUE TITLE
Download to DICM can support in ios?When download to DocumentDir, we can't find that image in file system.

### ISSUE THREAD

**Issue by zhulichao** [wkh237/react-native-fetch-blob#317]

**Comment by wkh237** [comment]
@zhulichao , could you provide how you use it? From my understanding, DCIM folder is Android only, IOS does not have an external storage.

**Comment by mykelaballe** [comment]
same issue here. where should we put the files we want to store on the phone? for android im using the RNFetchBlob.dirs.PictureDir. For iOS, am i supposed to use RNFetchBlob.dirs.DocumentDir? im storing files locally for offline use and faster retrival, so the app doesnt have to download the images and files again and again

**Comment by mykelaballe** [comment]
what's the status on this one? DCIM is for Android only. But how about IOS? i tried using DocumentDir but i cant find the files

**Comment by durgarao150** [comment]
Any updates on what directory to use for IOS?

**Comment by kesiena115** [comment]
Same issue here. Any update on the directory to use for iOS?
