### ISSUE TITLE
[Question] How to access the content size of a file before downloading it?

### ISSUE THREAD

**Issue by Crash--** [wkh237/react-native-fetch-blob#324]
Currently I've something like: 

```js
this.task = RNFB.config({
        path: realLocalPath,
        indicator: true,
        overwrite: true
      })
      .fetch('GET', remoteURL);
 this.task.progress((loaded, total) => {
        this.setState({
          percent: Math.floor(100 * (loaded / total))
        })
      })
this.task.then((res) => {
...
});
```

But I want to prevent the download if the user doesn't have enough freeSpace on his phone. I can easily do it in the progress, but this solution doesn't sound optimal ?

**Comment by wkh237** [comment]
@Crash-- , thanks for the feedback. You can do this by checking the `Content-Type` field in response header upon receiving response headers from the server then [cancel](https://github.com/wkh237/react-native-fetch-blob/wiki/Classes#cancelpromise) the request if the free space is not enough. There's an API we haven't address in the document but we've already used that in XMLHttpRequest polyfill for a while. 

[https://github.com/wkh237/react-native-fetch-blob/blob/master/polyfill/XMLHttpRequest.js#L199](https://github.com/wkh237/react-native-fetch-blob/blob/master/polyfill/XMLHttpRequest.js#L199)

Will add this part to documentation later.

**Comment by Crash--** [comment]
Thanks ;)
