### ISSUE TITLE
Race condition with config() and cancel()

### ISSUE THREAD

**Issue by wcandillon** [wkh237/react-native-fetch-blob#331]
@wkh237 First things first, thank you for this amazing library!

I found a race condition between `config()` and `cancel()` which seems fairly easy to reproduce.
This race condition leads to broken images such as this one: https://www.dropbox.com/s/euwx03cglbuuu1h/Screenshot%202017-04-15%2010.16.26.png?dl=0 or https://github.com/facebook/react-native/issues/9893.

```js
cache.task = RNFetchBlob.config({ path }).fetch("GET", uri, {});
cache.task.catch(error => {
  console.log(error);
//This below should always return false but doesn't
// in a scenario where we do a lot of fetch() and cancel()
// for example when scrolling quickly through a feed of image
// see: https://hackernoon.com/image-pipeline-with-react-native-listview-b92d4768b17c
  RNFetchBlob.fs.exists(path).then(result => console.log(result));
});
```

**Comment by wkh237** [comment]
@wcandillon , thanks for the feedback. Wondering if there's a sample project for replicate this one?

**Comment by wcandillon** [comment]
@wkh237 Not at the moment but maybe in the near future. I think you can reproduce it by start many requests and canceling them. It looks the writing of the image to disk can be interrupted by `cancel()`, is that something you can potentially identify on the objectivec code?

The way I managed to work around this issue is by doing `fs.unlink` after canceling: https://github.com/wcandillon/react-native-img-cache/blob/master/src/index.tsx#L106

**Comment by wkh237** [comment]
By design,  if there's either `path` or `fileCache` property in `config`, the response data chunks will be written to the location directly. When canceling the task, the incomplete file will not be removed since some people may use it later (like resume the download by [Range Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests)).

**Comment by wcandillon** [comment]
@wkh237 Oh right that makes sense. Thank you for the feedback.
