### ISSUE TITLE
RNFetchBlob failed to encode response data to BASE64 string.

### ISSUE THREAD

**Issue by IceNeoMax** [wkh237/react-native-fetch-blob#334]
I'm downloading a pdf file and then i use cancel to stop downloading and that error appear.
Here's my code 
downloadPdf = (data) => {
    downloading  = RNFetchBlob.fetch('GET', basePdf+data.pdf , {
        //some headers ..
        //basePdf+data.pdf
      });
      RNFetchBlob.config({
        fileCache : true,
        path : RNFetchBlob.fs.dirs.DocumentDir + '/' +data.pdf
      });
      downloading.progress((received, total) => {
          let width= (received/total);
          this.setState({ width:width});
      })
      .then((res) => {
        this.setState({dataPdf: {year:data.year, pdf:data.pdf ,stored:res.path(),width:1}  });
        });
      });
downloading.cancel();

**Comment by wkh237** [comment]
@IceNeoMax , does it happen on both Android and IOS? Does it always happen when canceling the request?

**Comment by IceNeoMax** [comment]
@wkh237 i just test on android. it always happen when i cancel the request
