### ISSUE TITLE
Unable to use camera image file on Android

### ISSUE THREAD

**Issue by ajonno** [wkh237/react-native-fetch-blob#338]
We've hit a snag when trying to upload a blob to Firebase and it's only on Android.

We are using:
- React Native 0.41.1
- ```react-native-fetch-blob: ^0.10.4``` 

Just to be clear:

- iOS: taking a photo and/or using the camera roll -> uploading to Firebase is fine.

- Android: using an image from the camera roll -> uploading to Firebase is fine.

It's solely an issue with photo's taken on the camera and (it seems, maybe) the file name formatting done by ```react-native-fetch-blob``` for Android.  But, really not sure so wanted to post here to confirm.

Here is the code we are using on the image file (after a photo is taken):
```
...
   // file is grabbed here. the following is an example: 
   photoPath = 'content://com.xxxxx.provider/app_images/Android/data/com.xxxxx/files/Pictures/image-355b65c8-dfad-4c53-b278-a2f268ff588d.jpg'

   const uploadUri = Platform.OS === 'ios' ? photoPath.replace('file://', '') : photoPath
  
   //wrap it
   const rnfbURI = RNFetchBlob.wrap(uploadUri);

   //note ***: rnfbURI string looks like this (on Droid). 
   //RNFetchBlob-file://content://com.xxxxxxx.provider/app_images/Android/data/com.xxxxx/files/Pictures/image-355b65c8-dfad-4c53-b278-a2f268ff588d.jpg

  //create blob and send to Firebase
    Blob
    .build(rnfbURI, { type: 'image/jpg;' }) 
    .then((blob) => {
        const imageName = blob._ref.substr(blob._ref.lastIndexOf('/') + 1);
        const imageRef = `images/${ownerKey}`;

        firebase.storage()
          .ref(imageRef)
          .child(imageName)
          .put(blob, { contentType : 'image/jpg' })
          .then((snapshot) => {
                 //etc..
                  blob.close();       
              })
        })
    })
    .catch(error => {
          console.log('blob creation error', error);
    });
```

No error is thrown it just fails silently.

Appreciate your help really need to get this sorted soon as possible, many thanks.

**Comment by wkh237** [comment]
@ajonno , I suppose this is the same problem as #287 , please have a look 👍

**Comment by ajonno** [comment]
thanks for this - it looks like i should test the branch ```issue-287```? can you let me know proper way to install and use that specific branch ? ie. how to do so from CLI or package.json ?

**Comment by wkh237** [comment]
there is an instruction in our [wiki](https://github.com/wkh237/react-native-fetch-blob/wiki)

**Comment by ajonno** [comment]
i just tried to run the following (via the wiki instructions) and the npm install just seems to hang:
```npm install --save git://github.com/wkh237/react-native-fetch-blob.git#issue-296```

Any idea why that would occur ? (I don't have any issues install via npm or yarn with other packages)

**Comment by ajonno** [comment]
I tested the build for #287 and this did not fix the issue unf. I'll try to give you as much detail as I can here to help.

deleted the React Native app off Android on both sim and real device.
installed this: ```npm install --save git://github.com/wkh237/react-native-fetch-blob.git#issue-287```

- deleted the node_modules folder

- rebuilt the node_modules folder

- re-installed the mobile app to HTC 10 (device) and simulator

- took a photo using ```react-native-image-picker``` 

- passed this image through the same code block as is detailed above in this issue

**Result:**
nothing happens. neither a blob is returned, nor is any error message generated.

this is the exact value that is being passed in to parameter 1 of the failing ```Blob.build(..  ```
```RNFetchBlob-file://content://com.cleverbean.provider/app_images/Android/data/com.cleverbean/files/Pictures/image-cf654736-e1ed-4a09-99bf-c078ff6478d1.jpg```

Important Note: if I choose an image from the **camera roll** this image WILL get **correctly** processed by ```Blob.build(..``` .  Here is what the parameter 1 value look like for this **successful** scenario: ```RNFetchBlob-file://content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F1697/ORIGINAL/NONE/2051903203``` 

I'm not sure what to try next but we're in a bit of a pickle now as the app goes out to testers at schools next week (yikes!). Anything I can do to help / try again please let me know, thanks.

**Comment by ajonno** [comment]
after more testing this seems to be resolved. we we're using a <CachedImage> component and after uninstalling that and using vanilla <Image> the Android blob's *from the camera* started uploading to Firebase. What we didn't test, was playing with the param's on <CachedImage> to see if it's behavior could be tweaked so as not to interfere with the Firebase uploads from Droid. That's on our todo list but at least for now the primary issue is resolved.
