### ISSUE TITLE
license

### ISSUE THREAD

**Issue by ddaaggeett** [wkh237/react-native-fetch-blob#341]
hello,
what's the intended license of this software package?
is it permissible?

**Comment by wkh237** [comment]
@ddaaggeett , thanks for the heads up. The license file is missing after we separate the development and distribution files into two projects, I've added it to the project 👍 

[https://github.com/wkh237/react-native-fetch-blob/blob/master/LICENSE](https://github.com/wkh237/react-native-fetch-blob/blob/master/LICENSE)
