### ISSUE TITLE
Cant cache images on IOS

### ISSUE THREAD

**Issue by ronak301** [wkh237/react-native-fetch-blob#345]
Hi , i am not able to cache images on IOS which are downloaded with authentication headers.
For ex : 
RNFetchBlob
      .config({
        fileCache : true,
        appendExt : 'png'
      })
        .fetch('GET', 'some url -> which redirect to s3 url', {
        'X-Access-Token': ''
      } )

**Comment by wkh237** [comment]
@ronak301 , is there more information about this?  is there any error ?

**Comment by ronak301** [comment]
Ahh..adding key in config did the trick.

**Comment by alexprodev** [comment]
Same issue - I can't store it on my local side. It works for the first time but I close the app and re-run it then it will be erased automatically.
