### ISSUE TITLE
Possibly a typo in polyfill/FileReader.js

### ISSUE THREAD

**Issue by kbeckmann** [wkh237/react-native-fetch-blob#347]
There is a piece of code that looks like a typo in the file polyfill/FileReader.js:
https://github.com/wkh237/react-native-fetch-blob/blob/master/polyfill/FileReader.js#L82
```
  get readState() {
    return this._readyState
  }
```

I am not sure what the code does so I am not comfortable writing a PR here. It seems `this._readyState` is undefined, but `this._readState` exists.

Version: current master
Sample code: see above

**Comment by kbeckmann** [comment]
I should probably create a separate issue for this, but in the same file there are multiple references to a variables that don't exist, `label` and/or `b`, e.g.:

```
  abort() {
    log.verbose('abort', b, label)
  }

  readAsArrayBuffer(b:Blob) {
    log.verbose('readAsArrayBuffer', b, label)
  }
```

Seems this code would crash if it is called.

**Comment by wkh237** [comment]
@kbeckmann , thanks for your information. Basically we're not using the FileReader polyfill ATM, however, still appreciate your help. 👍

**Comment by wkh237** [comment]
Already fixed these typos, you can also find the commit in branch `0.10.6` and `issue-347`
