### ISSUE TITLE
response.headers()

### ISSUE THREAD

**Issue by braco** [wkh237/react-native-fetch-blob#351]
https://developer.mozilla.org/en-US/docs/Web/API/Response/headers

Is there any reason response.headers() isn't implemented, out of curiosity?

On that note, are there any plans to aim closer to the core fetch standard? There are enough differences in output that I've had to write a wrapper to this library so it can place nicely with the other fetch functions.

**Comment by wkh237** [comment]
@braco ,  thanks for the suggestion. I think this has already been addressed in #281 please move to that thread 😃 . Basically, I think this one should be corrected but I'm very busy and there're still tons of issues and requirements coming over. Will hand on this issue when I have time, and of course, a PR is definitely welcome 👍
