### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by ataomega** [wkh237/react-native-fetch-blob#352]
At first thanks for the great work.

I'm using this package as a replacement for JS Fetch. I have calls to different URLs. all works fine except one :

http://somewebsite.com/app/user?field_conditions[field_last_name]="%Sch%"&options[field_conditions_op][field_last_name]=LIKE

When I try fetching it via GET method, it throws an error : "unsupported url"

**Comment by wkh237** [comment]
Try escape special characters like `"` or `[`

**Comment by denghejun** [comment]
Yes, pelase use `encodeURI(uri)` to escape. it works to me.
