### ISSUE TITLE
Log statement in RNFetchBlobFileResp.java is killing android performance.

### ISSUE THREAD

**Issue by ramakula** [wkh237/react-native-fetch-blob#353]
Log.i at line 84 in RNFetchBlobFileResp.java is killing android performance. This needs to be removed: Log.i("bytes downloaded", String.valueOf(byteCount) + "/" + String.valueOf(read) + "=" + String.valueOf(bytesDownloaded));

Here is the logcat snippet:

05-10 16:32:20.675  3468  3686 I bytes downloaded: 8192/8192=4237980
05-10 16:32:20.675  3468  3685 I bytes downloaded: 8192/8192=4203164
05-10 16:32:20.675  3468  3686 I bytes downloaded: 8192/8168=4246148
05-10 16:32:20.675  3468  3685 I bytes downloaded: 8192/8168=4211332
05-10 16:32:20.678  3468  3685 I bytes downloaded: 8192/1048=4212380
05-10 16:32:20.680  3468  3686 I bytes downloaded: 8192/1048=4247196
05-10 16:32:20.681  3468  3686 I bytes downloaded: 8192/8192=4255388
05-10 16:32:20.681  3468  3686 I bytes downloaded: 8192/8168=4263556
05-10 16:32:20.682  3468  3686 I bytes downloaded: 8192/1048=4264604
05-10 16:32:20.683  3468  3686 I bytes downloaded: 8192/8192=4272796
05-10 16:32:20.683  3468  3686 I bytes downloaded: 8192/8168=4280964
05-10 16:32:20.684  3468  3686 I bytes downloaded: 8192/1048=4282012
05-10 16:32:20.686  3468  3684 I bytes downloaded: 8192/8192=4499100
05-10 16:32:20.686  3468  3684 I bytes downloaded: 8192/8168=4507268
05-10 16:32:20.687  3468  3684 I bytes downloaded: 8192/1048=4508316
05-10 16:32:20.687  3468  3684 I bytes downloaded: 8192/8192=4516508
05-10 16:32:20.687  3468  3684 I bytes downloaded: 8192/8168=4524676
05-10 16:32:20.687  3468  3684 I bytes downloaded: 8192/1048=4525724
05-10 16:32:20.688  3468  3684 I bytes downloaded: 8192/8192=4533916
05-10 16:32:20.688  3468  3684 I bytes downloaded: 8192/8168=4542084
05-10 16:32:20.688  3468  3684 I bytes downloaded: 8192/1048=4543132
05-10 16:32:20.689  3468  3684 I bytes downloaded: 8192/8192=4551324
05-10 16:32:20.689  3468  3684 I bytes downloaded: 8192/8168=4559492
05-10 16:32:20.690  3468  3684 I bytes downloaded: 8192/1048=4560540
05-10 16:32:20.690  3468  3684 I bytes downloaded: 8192/8192=4568732
05-10 16:32:20.690  3468  3684 I bytes downloaded: 8192/8168=4576900
05-10 16:32:20.691  3468  3684 I bytes downloaded: 8192/1048=4577948
05-10 16:32:20.691  3468  3684 I bytes downloaded: 8192/8192=4586140
05-10 16:32:20.692  3468  3684 I bytes downloaded: 8192/8168=4594308
05-10 16:32:20.692  3468  3684 I bytes downloaded: 8192/1048=4595356
05-10 16:32:20.692  3468  3684 I bytes downloaded: 8192/8192=4603548
05-10 16:32:20.693  3468  3684 I bytes downloaded: 8192/8168=4611716
05-10 16:32:20.693  3468  3684 I bytes downloaded: 8192/1048=4612764
05-10 16:32:20.693  3468  3684 I bytes downloaded: 8192/8192=4620956
05-10 16:32:20.694  3468  3684 I bytes downloaded: 8192/8168=4629124
05-10 16:32:20.694  3468  3684 I bytes downloaded: 8192/1048=4630172
05-10 16:32:20.694  3468  3684 I bytes downloaded: 8192/8192=4638364
05-10 16:32:20.694  3468  3684 I bytes downloaded: 8192/8168=4646532
05-10 16:32:20.695  3468  3684 I bytes downloaded: 8192/1048=4647580
05-10 16:32:20.695  3468  3684 I bytes downloaded: 8192/8192=4655772
05-10 16:32:20.697  3468  3685 I bytes downloaded: 8192/8192=4220572
05-10 16:32:20.698  3468  3688 I bytes downloaded: 8192/1048=4752028
05-10 16:32:20.699  3468  3688 I bytes downloaded: 8192/8192=4760220
05-10 16:32:20.699  3468  3688 I bytes downloaded: 8192/8168=4768388
05-10 16:32:20.700  3468  3688 I bytes downloaded: 8192/1048=4769436
05-10 16:32:20.700  3468  3688 I bytes downloaded: 8192/8192=4777628
05-10 16:32:20.701  3468  3688 I bytes downloaded: 8192/8168=4785796
05-10 16:32:20.701  3468  3688 I bytes downloaded: 8192/1048=4786844
05-10 16:32:20.702  3468  3688 I bytes downloaded: 8192/8192=4795036
05-10 16:32:20.702  3468  3688 I bytes downloaded: 8192/8168=4803204
05-10 16:32:20.703  3468  3688 I bytes downloaded: 8192/1048=4804252
05-10 16:32:20.704  3468  3688 I bytes downloaded: 8192/8192=4812444
05-10 16:32:20.704  3468  3688 I bytes downloaded: 8192/8168=4820612
05-10 16:32:20.704  3468  3688 I bytes downloaded: 8192/1048=4821660
05-10 16:32:20.704  3468  3688 I bytes downloaded: 8192/8192=4829852
05-10 16:32:20.705  3468  3688 I bytes downloaded: 8192/8168=4838020
05-10 16:32:20.705  3468  3688 I bytes downloaded: 8192/1048=4839068
05-10 16:32:20.706  3468  3685 I bytes downloaded: 8192/8168=4228740
05-10 16:32:20.707  3468  3685 I bytes downloaded: 8192/1048=4229788
05-10 16:32:20.709  3468  3686 I bytes downloaded: 8192/8192=4290204
05-10 16:32:20.709  3468  3686 I bytes downloaded: 8192/8168=4298372
05-10 16:32:20.710  3468  3686 I bytes downloaded: 8192/1048=4299420
05-10 16:32:20.712  3468  3686 I bytes downloaded: 8192/8192=4307612
05-10 16:32:20.713  3468  3686 I bytes downloaded: 8192/8168=4315780
05-10 16:32:20.713  3468  3686 I bytes downloaded: 8192/1048=4316828
05-10 16:32:20.714  3468  3686 I bytes downloaded: 8192/8192=4325020
05-10 16:32:20.715  3468  3685 I bytes downloaded: 8192/8192=4237980
05-10 16:32:20.716  3468  3685 I bytes downloaded: 8192/8168=4246148
05-10 16:32:20.717  3468  3685 I bytes downloaded: 8192/1048=4247196
05-10 16:32:20.718  3468  3685 I bytes downloaded: 8192/8192=4255388
05-10 16:32:20.718  3468  3688 I bytes downloaded: 8192/8192=4847260
05-10 16:32:20.719  3468  3685 I bytes downloaded: 8192/8168=4263556
05-10 16:32:20.719  3468  3688 I bytes downloaded: 8192/8168=4855428
05-10 16:32:20.719  3468  3685 I bytes downloaded: 8192/1048=4264604
05-10 16:32:20.720  3468  3688 I bytes downloaded: 8192/1048=4856476
05-10 16:32:20.721  3468  3688 I bytes downloaded: 8192/8192=4864668
05-10 16:32:20.722  3468  3688 I bytes downloaded: 8192/8168=4872836
05-10 16:32:20.722  3468  3688 I bytes downloaded: 8192/1048=4873884
05-10 16:32:20.722  3468  3684 I bytes downloaded: 8192/8168=4663940
05-10 16:32:20.723  3468  3684 I bytes downloaded: 8192/1048=4664988
05-10 16:32:20.723  3468  3688 I bytes downloaded: 8192/1769=4875653
05-10 16:32:20.724  3468  3688 I bytes downloaded: 8192/-1=4875653
05-10 16:32:20.724  3468  3684 I bytes downloaded: 8192/8192=4673180
05-10 16:32:20.725  3468  3684 I bytes downloaded: 8192/8168=4681348
05-10 16:32:20.726  3468  3684 I bytes downloaded: 8192/1048=4682396
05-10 16:32:20.727  3468  3684 I bytes downloaded: 8192/8192=4690588
05-10 16:32:20.727  3468  3684 I bytes downloaded: 8192/8168=4698756
05-10 16:32:20.728  3468  3684 I bytes downloaded: 8192/1048=4699804
05-10 16:32:20.728  3468  3684 I bytes downloaded: 8192/8192=4707996
05-10 16:32:20.729  3468  3684 I bytes downloaded: 8192/8168=4716164
05-10 16:32:20.729  3468  3684 I bytes downloaded: 8192/1048=4717212
05-10 16:32:20.730  3468  3684 I bytes downloaded: 8192/8192=4725404
05-10 16:32:20.730  3468  3684 I bytes downloaded: 8192/8168=4733572
05-10 16:32:20.730  3468  3684 I bytes downloaded: 8192/1048=4734620
05-10 16:32:20.731  3468  3684 I bytes downloaded: 8192/8192=4742812
05-10 16:32:20.731  3468  3684 I bytes downloaded: 8192/8168=4750980
05-10 16:32:20.732  3468  3684 I bytes downloaded: 8192/1048=4752028

**Comment by wkh237** [comment]
@ramakula , thanks for the information, have already remove the statement in 7752ff7. You can also find the fix on branch `0.10.6` and `issue-353` 👍
