### ISSUE TITLE
dirs.DownloadDir not work

### ISSUE THREAD

**Issue by AmusedMe** [wkh237/react-native-fetch-blob#355]
I am using react-native v0.40.0, fs v2.3.2, fetch-blob v0.10.5, android 7.0, when I use
`
const android = RNFetchBlob.android;
                RNFetchBlob.config({
                  addAndroidDownloads: {
                    useDownloadManager: true,
                    title: 'App Released',
                    description: 'Found new version',
                    mime: 'application/vnd.android.package-archive',
                    mediaScannable: true,
                    notification: true,
                    appendExt: 'apk',
                    path: dirs.DownloadDir + '.apk'
                  }
                })
                  .fetch('GET', URLCONSTS.URLRESOURCE + res.result.androidUrl)
                  .then((rest) => {
                    android.actionViewIntent(rest.path(), 'application/vnd.android.package-archive');
                  });
`

the problem is, the downloaded apk always in root Directory rather than the Download Directory.
I tried a lot but still not working. I will your help. thx.

**Comment by wkh237** [comment]
@AmusedMe , if I'm reading this correctly, you're going to make the file visible in Android's Downloads app? then you'll need to use [Download Manager](https://github.com/wkh237/react-native-fetch-blob/wiki/Classes#addandroiddownloadsobject-android-only)

**Comment by wkh237** [comment]
@AmusedMe , a new API `RNFetchBlob.android.addCompleteDownload` has been added in branch `issue-355` which can directly add a file to Downloads app. 

The usage is described in the following example

```js
RNFetchBlob.android.addCompleteDownload({
        title : 'test file of RNFB',
        description : 'desc',
        mime : 'image/png',
        path : myPath,
        showNotification : true
      })
```

You can install the package from this branch and verify if that works correctly 👍

**Comment by gferreyra91** [comment]
I have the same problem, when i try to open with `android.actionViewIntent(rest.path(), 'application/vnd.android.package-archive')`
it's fails because a problem with the permissions of the folder `/data/user/0/com.android.providers.downloads/cache/`
