### ISSUE TITLE
How to use `timeout`

### ISSUE THREAD

**Issue by RabbitDream** [wkh237/react-native-fetch-blob#361]
`config`:({
    timeout:1000
});
Is this okay?

**Comment by RabbitDream** [comment]
Set the `timeout` after '1000', no success, did not take the wrong method

**Comment by wkh237** [comment]
@RabbitDream , if the server responds in 1000ms the timeout will not be firing.

**Comment by RabbitDream** [comment]
How long is the shortest?

**Comment by wkh237** [comment]
@RabbitDream , I'm closing this issue as there's already some workaround in #368. Please keep track of this in that thread instead.
