### ISSUE TITLE
re rendering issue after .then

### ISSUE THREAD

**Issue by barron9** [wkh237/react-native-fetch-blob#364]
alert works ok but not rendering happens after .then

how can I do that

```
pulldata() {
RNFetchBlob.fetch('GET', 'http://bigcom', {
     })
  .then((res) => {
    alert(res.text());

return <Text>{res.text()}</Text>

  })
  .catch((errorMessage, statusCode) => {
alert(errorMessage);
  })

}

```

**Comment by wkh237** [comment]
@barron9 , I'm not sure where's exactly the problem, if the `alert` works, rendering issue might not relate to this lib.

**Comment by barron9** [comment]
@wkh237 but.. how can i get a result to my render function after .then ?
