### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by blackxored** [wkh237/react-native-fetch-blob#365]
Recommended approach for testing?
I'm using `react-native-cacheable-image` and it fails to render.

```
TypeError: Cannot read property 'DocumentDir' of undefined

      at Object.<anonymous> (node_modules/react-native-fetch-blob/fs.js:24:24)
      at Object.<anonymous> (node_modules/react-native-fetch-blob/index.js:21:9)
```

**Comment by Sam1301** [comment]
+1
I am facing the same issue.

**Comment by wkh237** [comment]
I'm going to close this one as it's duplicated,  there're already some discussions in #212, please move to the thread, thanks.
