### ISSUE TITLE
Resume downloading after lost connection

### ISSUE THREAD

**Issue by IceNeoMax** [wkh237/react-native-fetch-blob#378]
i did a normal download then i suddenly shut down my internet and it stopped.
after that i turn the internet on again but it doesnt resume the downloading.
what can i do?

"react-native": "^0.43.4",
"react": "^16.0.0-alpha.6",

**Comment by wkh237** [comment]
@IceNeoMax , I think you will need a server that supports mechanisms like [Range-Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests), and after the connection lost, request chunks you haven't downloaded yet.

see our [test case](https://github.com/wkh237/react-native-fetch-blob-dev/blob/master/test/test-0.9.6.js#L31) for reference
