### ISSUE TITLE
Multipart with array as field is treated as string

### ISSUE THREAD

**Issue by darrenchiu** [wkh237/react-native-fetch-blob#379]
Hi,

Not sure if there is a way to do this or this is a bug. If I try to put an array in multipart upload, seems it will be treated as string instead of array and the server will throw an error in identifying it as array:

`
     RNFetchBlob.fetch('POST', 'https://some-api', {
        Authorization: token,
      }, [
        {name: 'title', data: 'Testing Create Memo'},
        {name: 'availableDistricts', data: JSON.stringify([true, true, true])}
      ])
`

and server will receive the field as

`
'[true, true, true]'
`

and throw an validation error.

Anyway to get rid of the single quote that quoting the array?

Thanks a lot

**Comment by wkh237** [comment]
@darrenchiu , does this happen on Android or IOS ?
