### ISSUE TITLE
Can't upload non-local files with content:// URIs

### ISSUE THREAD

**Issue by ivankashtanov** [wkh237/react-native-fetch-blob#381]
Hi,
I've been trying to use this package for uploading files I pick on device using system's document picker.
It provides access to local files and Google Drive content as well. Most of GD data is not on device but picker returns `content://com.google.android.apps.docs.storage/document/...` URI, i.e. `content://`  URIs as well.
Unfortunately, using it for upload result in an error on [this](https://github.com/wkh237/react-native-fetch-blob/blob/master/android/src/main/java/com/RNFetchBlob/RNFetchBlobBody.java#L266) line that says something like `can't invoke method String.toCharArray() on null object reference`. 

AFAIU, reading content URIs should be done using `ContentResolver` object (details [here](https://stackoverflow.com/a/27143382)). Example there shows bitmap reading but it's also possible to create input stream from URI to read any type of data (details [here](https://developer.android.com/guide/topics/providers/document-provider.html), section "Get an InputStream").

It would be great to change content URI handling so that `ContentResolver` is used when needed.

**Comment by ivankashtanov** [comment]
I've managed to make it work for remote GD files, will make a PR if I have time.

**Comment by ivankashtanov** [comment]
[Here](https://github.com/ivankashtanov/react-native-fetch-blob/commit/19a36d2e9e3decbd3597bc7365bf64c54e05b242) is my solution. It copies the way `bundle-assets://` are handled, but uses `ContentResolver.inputStream` for stream creation.
Haven't tested all cases (only multipart body case), so didn't make a PR yet.

**Comment by akuma06** [comment]
Even `android.getContentIntent` gives us a content:// uri :/. Really need this

**Comment by wkh237** [comment]
There's a PR #374 merged for solving this issue. Please try to install the package from branch `issue-374` and see if it works.

**Comment by wkh237** [comment]
closing this issue as it's similar to #287
