### ISSUE TITLE
undefined is not an object (evaluating 'RNFetchBlob.DocumentDir')

### ISSUE THREAD

**Issue by Antoine-Mace** [wkh237/react-native-fetch-blob#386]
Possible duplicate issue with https://github.com/wkh237/react-native-fetch-blob/issues/371

although mine appear on IOS simulator (iphone 6 iOS 10.2),

here my dependencies :
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-fetch-blob": "0.10.5"

If anyone as any fix, solution it will be awesome

thanks

![screen shot 2017-06-05 at 14 30 03](https://cloud.githubusercontent.com/assets/22074517/26785684/9db1a08c-49fb-11e7-8aa2-8ee2c5b3740d.png)

**Comment by Antoine-Mace** [comment]
Solved by re-install react-native-fetch-blob

**Comment by justinmakaila** [comment]
This is still an issue and re-install didn't work

**Comment by zengyimou** [comment]
i have the same error

**Comment by justinmakaila** [comment]
@zengyimou  `react-native link`

**Comment by Adamnator92** [comment]
@justinmakaila it didn't work at all

**Comment by IrinaDorofeeva** [comment]
Adamnator92, did you find a fix? I have the same issue, nothing helps.

**Comment by Adamnator92** [comment]
@justinmakaila didnt, i try a lot of solution none of them work

**Comment by latusaki** [comment]
Just got this as well, trying to use as backend for redux-persist

**Comment by IrinaDorofeeva** [comment]
I found a fix. In my case deleting 'build' folder in 'ios' folder fixed the issue. Before that I did cache cleaning, reinstall, relink  - nothing fixed. I don't know if just deleting 'build' alone would fix the problem or all those previous steps I've done also helped.

**Comment by sunny635533** [comment]
i also have the error in ios.I tried a lot of solutions,but not work.

**Comment by latusaki** [comment]
I had this issue and it was installation problem. For some reason link did not work, had to do the steps manually.

**Comment by sunny635533** [comment]
@latusaki use manually to add it, your project can run?

**Comment by GROL** [comment]
+1 same error

**Comment by dangbh1002** [comment]
That's because of Expo.
If i use "react-native run-ios" or "react-native run-android", it's be fine..
But if i open project by Expo, it's the propblem!

**Comment by manjeets12** [comment]
@IrinaDorofeeva  +1

**Comment by templarstone** [comment]
I have the same problem with iOS. 

On Android run fine, cause I installed manually react-native-fetch-blob (MainApplication, settings.gradle, build.gradle, ... ). 

How can solve this issue on iOS?

**Comment by templarstone** [comment]
Ok, I installed rnpm, I did rnpm link and ready!

**Comment by vnd-ranga** [comment]
@ghost  +!

**Comment by safeimuslim** [comment]
+1 same error

**Comment by paulgrant** [comment]
+1 Same issue running in ios, referenced in libraries, linked, uninstalled and installed.  Nothing.
