### ISSUE TITLE
Upload photos taken from my camera

### ISSUE THREAD

**Issue by rena08** [wkh237/react-native-fetch-blob#390]
Hello ! I am working with the library in Android but i have an error. When i try upload an image taken from my camera doesn't work, but i try upload an image that not taken with my camera and it upload successfully.
The imageData.uri is for example: content://media/external/images/media/59732 for both cases.
mimeType for example is: jpeg or png.
Here is the code used:

`                RNFetchBlob.fetch('POST', 'URL POST', {
                    'Content-Type' : 'multipart/form-data'
                },
                    [
                        { name : 'media',filename: imageData.fileName,type: 'image/'+mimeType,data : RNFetchBlob.wrap(imageData.uri) }
                    ]
                )
                    .then((resp) => {
                       // success
                    })
                    .catch((err) => {
                        // error
                    })`

I am using RN 0.40. an RNFB  git://github.com/wkh237/react-native-fetch-blob.git#issue-287

Sorry for my english.

**Comment by rena08** [comment]
I solved it !! I read the file with RNFetchBlob.fs.readFile(path,'base64') and i put the response in data:

`{ name : 'media',filename: imageData.fileName,type: 'image/'+mimeType,data : base64Response }`

Sorry for my english

**Comment by roycclu** [comment]
@rena08 Tried your solution and got this error:
```
You attempted to set the key `_65` with the value `2` on an object that is meant to be immutable and has been frozen.
```
Any idea what caused it?
