### ISSUE TITLE
cacheDir specific or shared?

### ISSUE THREAD

**Issue by ramsestom** [wkh237/react-native-fetch-blob#395]
Is the cacheDir from RNFetchBlob.fs.dirs specific to each application or shared between all aplications runing on the device and using react-native-fetch-blob?
This is to know if there is a risk from one application to ovewrite a file written by another app into cacheDir with the same name...

**Comment by wkh237** [comment]
@ramsestom , the `cacheDir` resides in each app's home folder, so yes, they're separated.

**Comment by ramsestom** [comment]
Perfect. Thanks
