### ISSUE TITLE
undefined is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular')

### ISSUE THREAD

**Issue by cbjs** [wkh237/react-native-fetch-blob#398]
react-native: 0.44.3
react-native-fetch-blob: 0.10.5

<img width="377" alt="screen shot 2017-06-17 at 11 20 46 pm" src="https://user-images.githubusercontent.com/1215843/27254105-e5eeeeec-53b3-11e7-9111-318b38aef682.png">

**Comment by JonathanKirknes** [comment]
I have this issue, too. Anyone can help me?

**Comment by cbjs** [comment]
link react-native-fs, not react-native-fetch-blob

**Comment by qq912276337** [comment]
the same error.how to fix it?
link react-native-fs has no effect

**Comment by misterwell** [comment]
I'm seeing this issue as well... tried linking, unlinking... not sure how to proceed. Any suggestions? Any logs I can provide?
