### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): Array [   [Error: TypeError: expected dynamic type `string', but had type `object'], ]

### ISSUE THREAD

**Issue by krazyzohaib** [wkh237/react-native-fetch-blob#399]
```js
  RNFetchBlob.fetch('POST', 'url', {
          Authorization: 'Bearer access-token',
          otherHeader: 'foo',
          'Content-Type': 'multipart/form-data',
        }, [
          { name: 'firstName', data: this.state.firstName },
          { name: 'lastName', data: this.state.lastName },
      	  { name: 'email', data: this.state.email },
          { name: 'password', data: this.state.password },
      	  { name: 'city', data: this.state.city },
          { name: 'maritalStatus', data: this.state.maritalStatus },
      	  { name: 'children', data: this.state.children },
          { name: 'profession', data: this.state.profession },
          { name: 'image',
          filename: this.state.fileName,
          type: 'image/jpeg/jpg/png',
          data: RNFetchBlob.wrap(this.state.path) },
        ])
        .then((resp) => resp.json())
        .then((respJson) => {
            console.log(respJson);
            const { success, authToken, userId } = respJson;
            this.setState({ authToken, userId });
            if (success === true) {
                this.successRegister();
            } else if (success === false) {
                  this.failedRegister();
                }
        })
        .catch((error) => {
          console.log(error);
           this.failedRegister();
          return error;

       });

```
this is mycode i am having the above mentioned error

**Comment by wkh237** [comment]
@krazyzohaib , please keep in mind that all `data` in form data should be a `String`. I'm closing this one let move to #404 if you still having question on this.

**Comment by namnh240795** [comment]
i also have this error and don't know how to fix it even data is String :|

Here is my code

const { fs, fetch, wrap } = RNFetchBlob;

export const uploadAvatar = async avatarInfo => {
  console.log(avatarInfo.fileName);
  console.log(avatarInfo.type);
  console.log(wrap(avatarInfo.path));
  console.log(avatarInfo.fileName.split(".")[0]);

  const base64 = await readImageBase64(avatarInfo.path);
  console.log(String(base64))
  
  return RNFetchBlob.fetch("POST", url,
  {'Content-Type': 'Application/json'},
  {
    name: avatarInfo.fileName.split('.')[0], 
    filename: avatarInfo.fileName, 
    type: avatarInfo.type,
    data: base64
  }).then(resp => {
      console.log("res", resp);
  })
  .catch(err => {
     console.log("err", err);
  });
};

const readImageBase64 = imageUrl =>
  fs.readFile(imageUrl, "base64").then(res => {
    console.log('base64 ', res)
    return res
  });
