### ISSUE TITLE
Undefined error

### ISSUE THREAD

**Issue by kobePer** [wkh237/react-native-fetch-blob#4]
Hi,

I wan't to use your package for fetching network images.
The images are protected by Basic Auth.

I would like to use them in an <Image /> component, but keep getting following error on RNFetchBlob.fetch():

`TypeError: Cannot read property 'fetchBlob' of undefined`

I'm on RN ^0.22.2
i've installed rnpm and ran the `rnpm link` command

Any clue on what i'm missing here?

**Comment by kobePer** [comment]
For those interested, following actions solved my issue:
- Cleaning my Xcode-project
- restarting RN package manager
- resetting the iOS simulator

**Comment by wkh237** [comment]
Hi @kobePer I think it might because this module uses native libraries, therefore it's necessary to recompile the whole project after `rnpm link`, and also restart RN packager.

Though the problem seems to have been solved, if there's any problem please feel free to create issues :D
