### ISSUE TITLE
undefined is not an object(evaluating 'RNFetchBlob.Document.Dir')

### ISSUE THREAD

**Issue by rhenmark** [wkh237/react-native-fetch-blob#402]
Hi. I'm using expo and I don't want to eject my file from expo. I wanted to use react-native-fetch-blob but I encountered this issue "undefined is not an object(evaluating 'RNFetchBlob.Document.Dir')". Can anyone that could help me to fix this ? Thanks

"expo": "^17.0.0",
"react": "16.0.0-alpha.6",
"react-native": "^0.44.0",

**Comment by wkh237** [comment]
@rhenmark , please refer to #299.
