### ISSUE TITLE
How to store files in iOS?

### ISSUE THREAD

**Issue by mykelaballe** [wkh237/react-native-fetch-blob#403]
i want to store files and images in iOS. where should i put the files? the folder structure should be:
1. MainFolder
2. under MainFolder there are 2 more folders: Announcements and Moments

Announcements folder - images and documents like word, excel, pdf, text files
Moments folder - images only

how should i achieve this using the library?

currently in Android i'm using the mkdir, isDir and writeFile methods for creating a folder, checking if the file already exists and saving the files. im using the PictureDir property for Android.

**Comment by lll000111** [comment]
Have you tried asking on https://stackoverflow.com/

**Comment by lll000111** [comment]
Since this is not a bug, and since there have been no news, I'll close this issue. Feel free to reopen if you still have questions.

**Comment by mykelaballe** [comment]
i still dont know how to store files in iOS

**Comment by jaycee425** [comment]
any news? @mykelaballe  do you know now how to do it?
