### ISSUE TITLE
TypeError: expected dynamic type `string', but had type `int64'null

### ISSUE THREAD

**Issue by gopchi** [wkh237/react-native-fetch-blob#404]
Hi guys, having some issue uploading image. I use "react-native-image-crop-picker": "^0.13.1" which returns me an image object with base64 data object, path, type and size. I use the base64 data and pass it as showed in the example for "multipart/form-data" upload.

```
"react-native": "0.42.3",
"react-native-cli": "^2.0.1",
"react-native-fetch-blob": "^0.10.5",
```

Here is my code:

```
RNFetchBlob.fetch('POST', url, headers, [
    { name : 'file', filename : "my_file.jpg", data: String(image.data)},
  ]).then((resp) => {
        console.log(resp)
  }).catch((err) => {
        console.log(err)
  });
```
image.data is a base64 representation of the picked image from the library using react-native-crop-picker. The error is the following:

`Error: RNFetchBlob request error: TypeError: expected dynamic type `string', but had type `int64'null`

P.S. Also have tried without using String(), but with no success. Either way, there's an error.

Would appreciate the help! 
Thanks!

**Comment by wkh237** [comment]
@gopchi , I've just finished running several test cases on multipart request and it turns out working seemly. 

See the [test case](https://github.com/wkh237/react-native-fetch-blob-dev/blob/master/test/test-0.5.1.js#L123) 

Furthur to your error message, I think that's caused by a `non-string` field you've passed in `data`. Though the code snippet looks very well, perhaps you can check if the field is a `String` not `null` or some other types.

**Comment by gopchi** [comment]
@wkh237 Hi and thanks for the response! I wanted to let you know that I resolved the issue by replacing 'file://' with 'RNFetchBlob-file://'. 

```
const uploadUri = Platform.OS === 'android' ? uri.replace('file://', '') : uri;

RNFetchBlob.fetch('POST', url, headers, [
      { name: 'mission-img', filename: filename, data: 'RNFetchBlob-file://' + uploadUri }
]).then(response => {
      dispatch({ type: 'imageUploadSuccess', imageAdded: JSON.parse(response.data) });
}).catch(error => {
      dispatch({ type: 'imageUploadFailed', error: error });
});
```

**Comment by wkh237** [comment]
@gopchi , thanks for reporting, I have to say this is a little confusing and we should somehow consider making the URI system more simple and clear as mentioned in #387. Anyway, just great to know the problem got resolved 👍

**Comment by fabriziomoscon** [comment]
I just wanted to add that also the `headers` keys must all be of type `string`. Hopefully this will save time to people in the future.

**Comment by krailler** [comment]
@fabriziomoscon  +10000
