### ISSUE TITLE
Where do downloaded file stored path?

### ISSUE THREAD

**Issue by aristaanggi** [wkh237/react-native-fetch-blob#405]
I just want my app download a file from the server by using react-native-fetch-blob. The problem is, where do the file stored? I just alert the `res.path() `and got an empty string and console.log the callback from react-native-fetch-blob and got this object 

`data: "/data/data/com.arista/files/RNFetchBlobTmp_c89d2b49-43cc-4146-b975-e2998591d678", taskId: "c89d2b49-43cc-4146-b975-e2998591d678", type: "path" : .....`

this is my code

```
alert("downloading");
RNFetchBlob
    .config({
        useDownloadManager : true, 
        fileCache : true
    })    
    .fetch('GET', 'http://fontawesome.io/assets/font-awesome-4.7.0.zip', {})
    .then((res) => {

        console.log(res);
        alert("Download");
        alert('The file saved to ', res.path());
    })
```

**Comment by wkh237** [comment]
@aristaanggi , according to the code snippet you provided, the file will be stored in `/data/data/com.arista/files/RNFetchBlobTmp_c89d2b49-43cc-4146-b975-e2998591d678` which is exactly the value that `res.path()` returned.
