### ISSUE TITLE
can i choice a file from my devices?

### ISSUE THREAD

**Issue by Nealyang** [wkh237/react-native-fetch-blob#410]
i want to upload my file ,but how can i get this file uri?

**Comment by wkh237** [comment]
@Nealyang , you can use libraries like [react-native-image-picker](https://github.com/react-community/react-native-image-picker) or if you're on Android, use platform-specific APIs [per wiki](https://github.com/wkh237/react-native-fetch-blob/wiki/Android-API#user-content-androidgetcontentintentmimestringpromise)
