### ISSUE TITLE
Sending a FormData() as the body of a request with RNFetchBlob.

### ISSUE THREAD

**Issue by nomikeeper** [wkh237/react-native-fetch-blob#412]
react-native-cli: 2.0.1
react-native: 0.44.0,

I'm having an issue to send a FormData() with RNFetchBlob.fetch(). I tried out uploading an array 
```
[{
   "name": video.name,
    "filename": video.name,
    "data":RNFetchBlob.wrap(video.uri),
    'message': this.state.message,
    'event_id': id,
    'private': "false"
}]
```
containing a video and It was just fine but when I tried to upload a FormData() containing a video, it didn't work. I know RNFetchBlob is expecting a dynamic string or array for the request body and the FormData is a object containing a video file. 
I'm just appending values like this: 
```
var videoFormData = new FormData();
            videoFormData.append("name",video.name)
            videoFormData.append("filename",video.name)
            videoFormData.append("data",RNFetchBlob.wrap(video.uri))
            videoFormData.append("message",this.state.message)
            videoFormData.append("event_id",id)
            videoFormData.append("private","false")
```
The form's structure is presents as down below:
```
{_parts: Array[6]}
parts:Array[6]
length:6
__proto__:Array[0] []
      0:Array[2] 
      1:Array[2] 
      2:Array[2]   // ["data","RNFetchBlob-file://content://media/external/video/media/1066"]
      3:Array[2] 
      4:Array[2] 
      5:Array[2] 
```
Can RNFetchBlob send a formData() as the body of a request or am I just doing it wrong?
API side expecting a FormData() as the body, is it achievable by using RNFetchBlob.

**Comment by wkh237** [comment]
@nomikeeper , though there's no direct support for this but you actually can do this by using [XMLHttpRequest Polyfill](https://github.com/wkh237/react-native-fetch-blob/wiki/Web-API-Polyfills-(experimental)#user-content-xmlhttprequest) or [Fetch Replacement](https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#user-content-fetch-replacement). 

Besides, I think it's a good point to support directly use FormData in future release, will look into it 👍

**Comment by nomikeeper** [comment]
@wkh237 Thanks, I will try out the other two. I'm gonna close this one~ 

> RNfetchBlob currently not directly supporting the FormData() object but there is a way send a FormData as the body of a request.

**Comment by Clcll** [comment]
@nomikeeper DId you solve this problem, if yes, can you provide an example ? Thx

**Comment by ashusdn** [comment]
Hi Team,

Can we send formdata using this, or how to feasible send extra parameter through this.

**Comment by Clcll** [comment]
@ashusdn 
 let obj = {
            uploadUrl: uploadUrl,
            method: 'POST',
            headers: {
                'Accept': 'application/json',
            },
            **fields: {"exampleKey": "exampleValue"}**,  try this way
            files: [
                {
                    name: name,
                    filename: filename
                    filepath: uri
                },
            ]
        };

        FileUpload.upload(obj, (err, result) => {................

**Comment by ashusdn** [comment]
@Clcll  Thanks for your quick response can you please provide example/code using RNFetchBlob

**Comment by Clcll** [comment]
@ashusdn 
please look this package https://github.com/wkh237/react-native-fetch-blob
