### ISSUE TITLE
Download file by POST method

### ISSUE THREAD

**Issue by wayne1203** [wkh237/react-native-fetch-blob#413]
HI, I'm using the latest version (0.10.6) of the library.
But I got a question about using POST method to download file.
How can I add params to the fetch function for POST method?

My code is like this. I don't know where I need to put "params" so I just estimate the position~ Haha...
```
var params = {
	"f_oc": "avatar-d",
	"f_aaid": SessionVariable.USER_AAID,
	"f_mhs": r_ava
};

RNFetchBlob
	 .config({
		 // add this option that makes response data to be stored as a file,
		 // this is much more performant.
		fileCache : true
	 })
	.fetch('POST', url, {
		 //some headers ..
	 }, JSON.stringify(params))
		 .then((res) => {
		    // the temp file path
		    console.log(res.path())
		    callback(res.path());
	})
	 .catch((errorMessage, statusCode) => {
		console.log("Error: "+ errorMessage + " - " + statusCode);
	})

```

**Comment by nomikeeper** [comment]
@wayne1203 I don't quite understand this, you already put your params inside of the fetch and you are asking where do I need to put the params?

the structure is like this ```fetch(Method, URL, headers, body)```
and you did put your params there and you did stringify it.

> .fetch("POST",
               "www.example.com/endpoint",
               { auth-token: token},
               JSON.stringify(params)  <============= You did put your params in here.
              )

and you also did declared your params at the beginning like this:

> var params = {
	                   "f_oc": "avatar-d",
	                   "f_aaid": SessionVariable.USER_AAID,
	                   "f_mhs": r_ava
};

**Comment by wayne1203** [comment]
Thanks for reply.
I just thinking is the params in a correct position because I got 0KB file.

**Comment by wkh237** [comment]
@wayne1203 , about the `params`, do you mean [querystring](https://en.wikipedia.org/wiki/Query_string) ?

**Comment by wayne1203** [comment]
Uh.... I'm not sure is it the same thing. I'm using "RequestParams" in Android.

**Comment by nomikeeper** [comment]
@wayne1203 By params you mean the body of the POST request right? 
@wkh237 I don't think he's referring the [querystring](https://en.wikipedia.org/wiki/Query_string) but the body of the request since it's a POST request. Or am I wrong? /I don't know well about this one./

**Comment by wayne1203** [comment]
@nomikeeper Yes, that's right. Btw, Is it able to print out what I'm sending in the request for debugging? I just thinking is my code correct or not.

**Comment by nomikeeper** [comment]
@wayne1203 I'm not sure if its going to be helpful or not. This is case of uploading a file but it works just fine. Check out this one.

```
RNFetchBlob.fetch(
                        "POST",
                        "localhost:8080/endpoint",
                        {
                            'auth-token': token,
                            'Content-Type': 'multipart/form-data'
                        },
                        formData
                )
                .uploadProgress((written,total) =>{
                    console.log("Uploaded", Math.floor(written/total * 100))}
                )
                .catch((e, statusCode) => {console.error("Got an error: ", e)})
                .done(()=>{console.log("Done!")})})
```
that form data looks like this:

```
[{
name : 'avatar-foo', 
filename : 'avatar-foo.png', 
type:'image/foo', 
data: RNFetchBlob.wrap(path_to_a_file)
}]
```
About the debugging, Yes you can.

**Comment by wayne1203** [comment]
@nomikeeper Added 'Content-Type': 'multipart/form-data' to header and I tried to change "params" to [{ data.... }], it will crash the app (Force close).
If "params" not convert to string(JSON.stringify) it'll get "NSDictonary cannot be converted to NSString" 


But, Thanks for your help~

**Comment by nomikeeper** [comment]
@wayne1203 what kind of data are you sending as the body? 
Does it contain a file? or should it be plain text?
In my code I was uploading a video and that's why sent a array as the body, but you don't have to do the same. Can you show me the structure of the body file. So, I might be able to help you.
Or what kind of request the server side expecting to get from your app?

**Comment by wayne1203** [comment]
@nomikeeper Sure. The request body just like the one I posted at #1 
```
var params = {
	"f_oc": "avatar-d",
	"f_aaid": SessionVariable.USER_AAID,
	"f_mhs": r_ava
};
```

No file including inside.

**Comment by nomikeeper** [comment]
@wayne1203 In that case, just JSON.stringify would do the work. But wait, isn't this the server side problem? You did mention everything works just fine but you are not getting the file from the server right?
Which leads to a conclusion server is not returning the correct data or it's not handling the request good enough.
If there was a error on the app side it won't send a request, right? But you said it did, but server is not returning the file. Maybe the data inside of the body didn't match what the server was expecting and I guess server is lack of handling those cases? /Maybe server got the data and it's not parsing the string into an object.../

**Comment by wayne1203** [comment]
The funny thing is I can get the file in Android (The app I wrote before in Android Studio, Not React Native).
I'll ask the sever support to check what the problem is.
Thanks

**Comment by wayne1203** [comment]
Finally is the server problem.  Server only provide "GET" for downloading file.
But I got the same problem in using "POST" for upload file.... I'll open an new issue.
Thank you for answering
