### ISSUE TITLE
[iOS] how to wrap the path and pass it through multipart/formdata?

### ISSUE THREAD

**Issue by ElvisWong** [wkh237/react-native-fetch-blob#414]
Package Version: 
react-native@0.43.4
react-native-fetch-blob@0.10.5
react-native-camera@0.8.0

Hi guys, I am new to react native and right now I am working on a small project that required me to do image/video upload. So, I tried to used[ react-native-camera](https://github.com/lwansbrough/react-native-camera) module to take picture or record video directly. I am able to take photo and display the image directly in my app and I got a file path from calling `this.camera.capture({}).then((data) => {console.log("image path: ", data.path);}).catch(err => console.error(err));`. The console result become like this: `image path: /var/mobile/Containers/Data/Application/2DE31AD4-1…/Documents/[filename].jpg`. 

Then, I tried to put this image path into RNFetchblob.wrap function and sending a request to my api by setting 'Content-Type' to be 'multipart/formData'. However, I can't receive any file sent to my server. Here is the way I used:

	RNFetchBlob.fetch('POST', [url], {
        Authorization: jwtToken, 
        'Content-Type' : 'multipart/form-data'
    }, [
        { name: 'file', filename: [fileName], type: 'image/jpeg', data: RNFetchBlob.wrap('/var/mobile/Containers/Data/Application/2DE31AD4-1…/Documents/[filename].jpg') }
    ]).then((response) => {
        console.log("res: ", response.text());
    })
    .catch((error) =>  {
        console.log(error);
    });

 Did I do something wrong when I was trying to follow the example? Or can you guys suggest any solution for that? Thank you very much.

**Comment by EnriqueDev** [comment]
I'm kinda of having the same problem but just on the android platform, iOS seems to upload just fine.

**Comment by wkh237** [comment]
on Android, try to add `file://` before the path.
