### ISSUE TITLE
Question: uploading multiple binary files in a single request without using forms data

### ISSUE THREAD

**Issue by mannol** [wkh237/react-native-fetch-blob#418]
I've seen examples of using form data to upload multiple files but, is it possible to upload data from multiple files without using forms?

Reason:
I have a server that accepts binary data only and delimits files by arguments provided as url queries.

**Comment by wkh237** [comment]
@mannol , I'm not quite clear about your question. Could you provide an example ?

**Comment by mannol** [comment]
Yeah, I modified the server to accept multipart/form-data. Closing this.
