### ISSUE TITLE
Error: `_reactNativeFetchBlob2.default.readStream is not a function`

### ISSUE THREAD

**Issue by smartt** [wkh237/react-native-fetch-blob#42]
I'm trying to use readStream, but react native is giving me the red-screen-of-death with the message, "_reactNativeFetchBlob2.default.readStream is not a function".

The package was installed using `npm` and linked using `rnpm`.  And ideas?

Versions:
 - "react-native": "0.28.0"
 - "react-native-fetch-blob": "^0.6.1"
 - iPhone 6 simulator running iOS 9.3
 - XCode 7.3.1

**Comment by wkh237** [comment]
Hi @smartt , I've just run [the tests](https://github.com/wkh237/react-native-fetch-blob/blob/master/test/test-0.5.1.js#L49) on iPhone 9.3 and simulator, but it doesn't give me this error. According to your error message, I suppose you're using the package this way

```js
RNFetchBlob.readStream(...)
```

However `readStream` is a function  in `fs` namespace, therefore it should be called this way

```js
RNFetchBlob.fs.readStream(...)
```

**Comment by smartt** [comment]
Got it.  I opened a PR https://github.com/wkh237/react-native-fetch-blob/pull/46 to update the example in the README to use `fs` to hopefully avoid this confusion in the future.
