### ISSUE TITLE
file doesn't exist after rebuild

### ISSUE THREAD

**Issue by IceNeoMax** [wkh237/react-native-fetch-blob#422]
/Users/nguyen/Library/Developer/CoreSimulator/Devices/A37CC7D1-6E51-49FF-B1CE-C3250DF708A9/data/Containers/Data/Application/75ED25DF-A291-4F60-94F1-24AAB193D8A3/Documents/AR_ENG_2016.pdf
Users/nguyen/Library/Developer/CoreSimulator/Devices/A37CC7D1-6E51-49FF-B1CE-C3250DF708A9/data/Containers/Data/Application/77F19A17-07E6-414C-AD12-B085FF39B07C/Documents/AR_ENG_2014.pdf
here's the two files after i rebuild my project (i stored path in my async storage). Then i used RNFetchBlob.fs.exists to check 
and the 1st path doesn't exist ( that path from my 1st build)
is that the second build remove the 1st file that was downloaded from the previous build?

**Comment by wkh237** [comment]
From my understanding this should only happen on the simulator, have you tried on a real device?

**Comment by IceNeoMax** [comment]
@wkh237 i did test on both release and debug on real device. 
Still happen man!

**Comment by wkh237** [comment]
The library uses `NSDocumentDirectory` and there's a [related SO thread](https://stackoverflow.com/questions/26807535/objective-c-documents-directory-keeps-changing-on-device) has been answered, I assume you're encountering the same problem?

**Comment by IceNeoMax** [comment]
@wkh237 i'm afraid it's not. mine just change went i rebuild the app not each time i launch it.

**Comment by eigithub** [comment]
@IceNeoMax , I think you should store the relative path and append the path after `dirs.DocumentDir` in runtime, this works for me.

**Comment by IceNeoMax** [comment]
@eigithub  yeah i did it thank you 💃
