### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by Chi-Duc** [wkh237/react-native-fetch-blob#436]
Hi,

I've built with React Native 0.45.1 and react-native-fetch-blob 0.10.6 and failed with the following error message:

In file included from <...>/node_modules/react-native-fetch-blob/ios/RNFetchBlob/RNFetchBlob.h:22:
../../react-native/React/Base/RCTBridgeModule.h:12:9: fatal error: 'React/RCTDefines.h' file not found

Please help. 
Thanks,
CD

**Comment by tehong** [comment]
I'm having the same problem.  I'm on React Native 0.46.1 with ExpoKit SDK 19.0.0 and eact-native-fetch-blob 0.10.7.  It is not clear to me how to fix this.

**Comment by ionflow** [comment]
Same issue here with @tehong setup.

**Comment by ionflow** [comment]
Also tried following these steps: https://github.com/facebook/react-native/issues/11721#issuecomment-270672904

Tried this:

![screenshot1](https://user-images.githubusercontent.com/4053903/28912028-4ef8eb66-77e7-11e7-874a-3f6c07fb003c.jpg)

**Comment by wkh237** [comment]
If you're using Expo please have a look on #371 #299

**Comment by ionflow** [comment]
@wkh237 I couldn't get this to work a fresh `expo detach`. Which comments in these two issues were you thinking would be helpful?

**Comment by ionflow** [comment]
@wkh237 after starting over from scratch I was able to get this working with an ejected expo app. Thanks!
