### ISSUE TITLE
Implement Blob and other polyfills

### ISSUE THREAD

**Issue by wkh237** [wkh237/react-native-fetch-blob#44]
According to #37 advice from @vaibhawc , perhaps we should consider implement `Blob` class on RN since we already have network and fs APIs. This may let some JS libraries that depends on web API becomes available in RN. At least we can try to make [firebase.storage](https://firebase.google.com/docs/reference/js/firebase.storage.Storage) work.

[Work in progress document](https://github.com/wkh237/react-native-fetch-blob/wiki/Web-API-Polyfills-(WIP))

[Spec Reference](https://developer.mozilla.org/docs/Web/API/Blob)

These are polyfills that planned to be implemented so far

- [x] Blob
- [x] File
- [x] XMLHttpRequest
- [x] FileReader (postponed)
- [x] Test cases
- [x] [Documentation](https://github.com/wkh237/react-native-fetch-blob/wiki/Web-API-Polyfills-(work-in-progress))

This feature will develop on branch **0.8.0**

**Comment by wkh237** [comment]
Related to [facebook/react-native#8684](https://github.com/facebook/react-native/issues/8684).

**Comment by wkh237** [comment]
merged into `0.8.0`

**Comment by wkh237** [comment]
A workable example base on `0.8.0-alpha.5`

[https://github.com/wkh237/rn-firebase-storage-upload-sample](https://github.com/wkh237/rn-firebase-storage-upload-sample)

**Comment by wkh237** [comment]
test case reference 

[https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/)

**Comment by dcworldwide** [comment]
Awesome work. I've quickly tested out uploading a file to firebase on 0.8.0-alpha.5 but I did have an issue. 

```
07-26 13:41:29.604  3333  3370 I ReactNativeJS: 'Blob', 'verbose:', 'Blob constructor called', 'mime', 'image/png;BASE64', 'type', 'string', 'length', 68
07-26 13:41:29.604  3333  3370 I ReactNativeJS: 'Blob', 'verbose:', 'create Blob cache file from file path', 'RNFetchBlob-file://file:/data/user/0/com.mva/cache/1469504489517.PNG'
07-26 13:41:29.604  3333  3370 I ReactNativeJS: 'Blob', 'verbose:', 'register blob onCreated', 0
07-26 13:41:29.606  3333  3370 I ReactNativeJS: 'Blob', 'error:', 'RNFetchBlob could not create Blob : file:/data/user/0/com.mva/cache/1469504489517.PNG', 'stat error: failed to list path `file:/data/user/0/com.mva/cache/1469504489517.PNG` for it is not exist or it is not a folder'
```

I realise this is alpha so there is no point testing it just yet. Just wanted to say I"m really happy your tackling an important problem and am looking forward to using your lib :)

**Comment by wkh237** [comment]
@dcworldwide , thank you for your information !  I think you might try removing the prefix `file:` from the path, and see if it works then 👍

**Comment by dcworldwide** [comment]
Ok I'll try that, thanks :+1:

**Comment by shirleycharlin** [comment]
@dcworldwide  hey I have also encounter the same issue right now. Can I know if you have resolved it? :)

**Comment by shirleycharlin** [comment]
right now I am encountering with these error message: 

Blob verbose: Blob constructor called mime image/jpeg;BASE64 type string length 34
log.js:24 Blob verbose: create Blob cache file from file path RNFetchBlob-file://[object Object]
log.js:24 Blob verbose: register blob onCreated 0
log.js:36 Blob error: RNFetchBlob could not create Blob : [object Object] failed to list path `[object Object]` for it is not exist or it is not exist

and I am using 0.8.0-alpha.6

**Comment by wkh237** [comment]
@shirleycharlin , I think that's because you're using an object as first argument of Blob constructor.

please refer to [the document](https://github.com/wkh237/react-native-fetch-blob/wiki/Web-API-Polyfills-(work-in-progress)#constructordata-options)

**Comment by shirleycharlin** [comment]
Hi I understand. I have change it to the string variable. 

however, i am not able to create the file. is it because of file:/// ???

Blob verbose: Blob constructor called mime image/jpeg;BASE64 type string length 248
log.js:24 Blob verbose: create Blob cache file from file path RNFetchBlob-file://file:///Users/shirleylee/Library/Developer/CoreSimulator…C6E-B989F2DA34E1/Documents/images/92F4CD3C-288D-43D4-9967-A083147D0C78.jpg
log.js:24 Blob verbose: register blob onCreated 0
log.js:36 Blob error: RNFetchBlob could not create Blob : file:///Users/charlin/Library/Developer/CoreSimulator/Devices/2FF84675-D…C6E-B989F2DA34E1/Documents/images/92F4CD3C-288D-43D4-9967-A083147D0C78.jpg failed to list path `file:///Users/charlin/Library/Developer/CoreSimulator/Devices/2FF84675-D…C6E-B989F2DA34E1/Documents/images/92F4CD3C-288D-43D4-9967-A083147D0C78.jpg` for it is not exist or it is not exist

**Comment by shirleycharlin** [comment]
I have resolve it. I actually uses the syntax from Mr @dcworldwide  . if you don't mind I would like to copy and paste these code of mine later.

**Comment by wkh237** [comment]
@shirleycharlin , great to hear that 👍 Please feel free to leave any comment or message.
