### ISSUE TITLE
Notification doesn't download file

### ISSUE THREAD

**Issue by SergioReis97** [wkh237/react-native-fetch-blob#442]
Tying to use the option addAndroidDownloads and create a notification but the notification never opens the file. 
I can use 
```
let sendIntent = RNFetchBlob.android.actionViewIntent;
sendIntent(path, mimeType);

``` 
To open the downloaded file for android and it works accordingly, added it to the notification click (implemented by third party) and everything goes smoothly except that even disabling addAndroidDownloads notification it always stays there... and whenever clicked, it says "can't open file" in a toast and nothing happens.

Here's the complete function i'm currently using to download

```
  _downloadFile(fileName,url) {
    const PictureDir = RNFetchBlob.fs.dirs.PictureDir;
    var tipoFIcheiro = mimetype.lookup(fileName);
    if (!tipoFIcheiro)
      tipoFIcheiro = "image/png"

    RNFetchBlob
    .config({
        fileCache : true,
        addAndroidDownloads : {
          title : fileName,
          mime : tipoFIcheiro,
          useDownloadManager : true,
          description : fileName,
          mediaScannable : false,
          notification : false,
        }
      })  
      .fetch('GET', url, {
        //some headers ..
      })
      .then((res) => {
        // the temp file path
        let base64Str = res.data;
        let imageLocation = PictureDir + '/' + fileName;
        

        //Save image
        
        fs.writeFile(imageLocation, base64Str, 'base64');
        if (Platform.OS === 'ios') {
          notify("Download Completo",fileName)
        } else {
          notifyFicheiro("Download Completo",fileName,tipoFIcheiro,res.path())
        }
      })
    

  }
```
Thanks in advance

**Comment by SergioReis97** [comment]
SInce i can open the notification i create and opened the file i found out that the file is being saved under /data/user/0/com.android.providers.downloads/cache/downloadfile.bin . Is it possible to save it to the RNFetchBlob.dirs.DocumentDir instead and with the correct extension? that way notification can probably open the file

**Comment by wkh237** [comment]
@SergioReis97 , you can add `path` to `addAndroidDownloads`.

**Comment by SergioReis97** [comment]
Using this still gives the same error when trying to open the file

```
    .config({
        fileCache : true,
        addAndroidDownloads : {
          title : fileName,
          mime: tipoFIcheiro,
          path:dirs.DCIMDir,
          ext:"png",
          useDownloadManager : true,
          description : fileName,
          mediaScannable : true,
          notification : true,
        }
      })  
```

**Comment by wkh237** [comment]
I think you should also give a filename (also extension) to the path, not folder only 👍

**Comment by SergioReis97** [comment]
same result actually, it does appear on download but can't open file. When using my costum notification i can open the file (even tho it's the one in the cache and .bin) but in the notification of download manager always says "can't open file" and same when i go to download folder using a .png as test and forcing png in name and everything

```
    .config({
        let dirs = RNFetchBlob.fs.dirs
        fileCache : true,
        addAndroidDownloads : {
          title : "test.png",
          mime: tipoFIcheiro,
          path:dirs.DCIMDir+"test.png" ,
          ext:"png",
          useDownloadManager : true,
          description : fileName,
          mediaScannable : true,
          notification : true,
        }
      }) 
```

**Comment by SergioReis97** [comment]
Same result actually, it does download and goes to download app but always says "Can't open this file". Same when i click in downloadmanager notification and i can still open it using the custom notification even though it points to "/data/user/0/com.android.providers.downloads/cache/downloadfile.bin"

https://gyazo.com/5801c1764f1831f73aca6f56b6c33688

**Comment by wkh237** [comment]
It looks similar to #391

**Comment by SergioReis97** [comment]
Gonna try to re-install package since i've noticed you did a change to this already 1 sec

**Comment by SergioReis97** [comment]
Re-installing into 0.10.6 didn't work but I copied the changes you've did in and it does indeed solve. Thank you for this amazing project/help :)
https://github.com/wkh237/react-native-fetch-blob/commit/ed2732a47ef5b4e7748b4c7632771d6f30a12c88

**Comment by wkh237** [comment]
Great 👍  Nice to know you solve the problem.
