### ISSUE TITLE
when i download a file which type is zip  how can  Extract it to current dir?

### ISSUE THREAD

**Issue by littlekite** [wkh237/react-native-fetch-blob#443]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. 
You may want to take a look on that page or find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
* issues lack of detailed information will be closed without any feedback

**Comment by wkh237** [comment]
This is somehow out of the scope, perhaps you can try [react-native-zip](https://github.com/remobile/react-native-zip)
