### ISSUE TITLE
Xcode runs the error 

### ISSUE THREAD

**Issue by zhuanglong** [wkh237/react-native-fetch-blob#446]
react-native 0.46.4
xcode 8.3.3 

Too many arguments to block...

![jietu20170728-203932](https://user-images.githubusercontent.com/19422011/28717594-07d5b860-73d5-11e7-8072-1a55965e9fdc.jpg)

**Comment by wkh237** [comment]
Looks like it's a problem with your React Native version, which version your app running on?

**Comment by ericcastro92** [comment]
I have the same issue, running RN 0.46.4

**Comment by lll000111** [comment]
Can't really speak about iOS since I don't have it, but according to this:;

https://facebook.github.io/react-native/docs/native-modules-ios.html#promises

the error message is really strange, because on iOS `reject(...)` takes three arguments (on Android too, and only the first two are usually used, ending up as `code` and `message` properties on the Javascript `Error` object, respectively).

**Comment by YY030913** [comment]
same on rn 0.47.2

**Comment by SuhairZain** [comment]
Has anyone been able to fix this issue?

**Comment by lll000111** [comment]
@SuhairZain 

https://github.com/facebook/react-native/blob/master/React/Base/RCTBridgeModule.h#L40

```
typedef void (^RCTPromiseRejectBlock)(NSString *code, NSString *message, NSError *error);
```

**Comment by SuhairZain** [comment]
@lll000111 I guess this is something to do with CocoaPods pulling in some old version of RN (0.17 or so it seems), but I can't figure out how that thing happens in the first place. Not your problem though. Sorry.

**Comment by SuhairZain** [comment]
@lll000111 When I install RNFB using react-native link, I get the following error while building: `ld: library not found for -l-lRNFetchBlob` and when I try to do it using CocoaPods, I get the issue being caused by CocoaPods pulling in an ancient version of RN. Do you have any suggestion on how to fix this?

**Comment by lll000111** [comment]
@SuhairZain I'm also just a user, and all I can say, unfortunately, is "works for me".... :-(

**Comment by SuhairZain** [comment]
@lll000111 Which method did you follow? Do you remember?

**Comment by lll000111** [comment]
@winpuc Winfried, can you answer the above question? How do you build one.pictures with RNFB?

**Comment by Tonacatecuhtli** [comment]
@SuhairZain I would follow the manual linking instructions [here](https://github.com/wkh237/react-native-fetch-blob/wiki/Manually-Link-Package). That's what I/we did to link RNFB for Android anyway.

**Comment by afilp** [comment]
I also lost time trying to solve this isse.

This library adds `React/Core` as a dependency:
https://github.com/wkh237/react-native-fetch-blob/blob/master/react-native-fetch-blob.podspec

And it appears that the added version is "0.11.0"?

This is what I get at the `podfile.lock`:

  - react-native-fetch-blob (0.10.6):
    - React/Core
  - react-native-intercom (9.0.0):
    - Intercom (~> 4.1.0)
  - React/Core (0.11.0)

This adds an old version of React.

**Comment by afilp** [comment]
@SuhairZain Also, when I try to use the manual linking instructions I cannot because the `xcodeproj` file is "greyed out". I cannot select it. Do you know why?

**Comment by brownieboy** [comment]
I got this too on iOS.  When updating my Pods, I saw:

> Using React (0.11.0)

in the terminal, followed later by:

> [!] React has been deprecated

The file node_modules/react-native-fetch-blob/react-native-fetch-blob.podspec contains the following entry:

> s.dependency 'React/Core'

What's going on here?

**Comment by brownieboy** [comment]
Putting these two lines in my Pod file fixed it for me:

>   pod 'React', path: '../node_modules/react-native'
>   pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

When I ran `pod update` afterwards, I could see that React 0.51.0 was pulled in to replace version 0.11.0.

**Comment by TyLy83** [comment]
brownieeboy your solution is work. cheers mate
