### ISSUE TITLE
Image automatically resized when sent over to back end

### ISSUE THREAD

**Issue by reidash** [wkh237/react-native-fetch-blob#451]
Hi ,

Whenever I upload an image to my backend, I realise the image had been resized to a smaller size.
Is there anyway to upload to the backend at the original size? 

`RNFetchBlob.fetch(
   'POST', 
   'http://192.168.0.108:80/scanning/detect/', 
   {
   'Content-Type' : 'multipart/form-data',
   'Content-Length' : '219153'
   }, 
   [
    { 
	name : 'image',
	filename : 'image.jpg', 	
	data: RNFetchBlob.wrap(uploadUri)
	}
    ])`

**Comment by wkh237** [comment]
From my understanding, this library does not compress the data, you may need to check the backend implementation.

**Comment by lll000111** [comment]
I'll close this, feel free to reopen if still necessary.

**Comment by hanishsharma** [comment]
I am also facing the same issue. When I upload 5mb image to server, then it gets compressed. Can you please tell me how can upload the actual size of image.
Thanks in advance :-)
