### ISSUE TITLE
undefined is not an object (evaluating 'RNFetchBlob.DocumentDir

### ISSUE THREAD

**Issue by sunny635533** [wkh237/react-native-fetch-blob#454]
### ## my project is swift with pod, i already add #import <react-native-fetch-blob/RNFetchBlob.h> in my headers, it always that "undefined is not an object (evaluating 'RNFetchBlob.DocumentDir". I found the RNFetchBlob is undfined. I don't know why.

react-native:0.42.3
xcode:8.3.3

**Comment by sunny635533** [comment]
i solved this by manually link it.

**Comment by EduardoPajarito** [comment]
I have the same problem, any solutions?


![captura de pantalla 2017-08-02 a la s 15 59 27](https://user-images.githubusercontent.com/9276220/28895802-7cfddece-779f-11e7-86a1-60280b784f82.png)

**Comment by sunny635533** [comment]
@Birdmaaant I think its because RNFetchBlob‘s class in a file directory not a Group on ios,so that RNFetchBlob module is unfined.

**Comment by wayne1203** [comment]
Hi, I got the same problem in iOS too.
I just tried to link "RNFetchBlob.h" to the library but not working at all.
How can you solve the problem?

**Comment by wayne1203** [comment]
Oh... I solved the problem by reinstall whole application.

**Comment by wabsolute-julianpierer** [comment]
I had the same problem on Android :/

**Comment by wayne1203** [comment]
Did you use
`react-native link`
and
`RNFB_ANDROID_PERMISSIONS=true react-native link`

That's all I know....

**Comment by RonnieRen** [comment]
you need to clean all cache and relaunch the app again .
for ios: 
 rm -rf ./ios/build
watchman watch-del-al
 rm -rf $TMPDIR/react-*
lsof -ti :8081 | xargs kill -9
react-native run-ios 

I believe so is android

**Comment by sunny635533** [comment]
maybe you forget to add RNFetchBlobPackage in android, please check it.

**Comment by GROL** [comment]
Helped for me this doc https://github.com/wkh237/react-native-fetch-blob/wiki/Manually-Link-Package

**Comment by Birdmaaant** [comment]
I already worked, I had to reinstall the package. :)

**Comment by gopikamurali** [comment]
i solved this problem by reinstall the application.

**Comment by jmasaki24** [comment]
Does anyone know why RNFB doesn't automatically add android permissions after 0.9.4?

**Comment by AlexM2807** [comment]
@GROL  it's work, thank's !

**Comment by Jarzka** [comment]
Works after I used `rn-fetch-blob` instead of `react-native-fetch-blob`
