### ISSUE TITLE
unterminated string constant in ./polyfill/Blog.js line 289

### ISSUE THREAD

**Issue by sebringj** [wkh237/react-native-fetch-blob#455]
```
      return Promise.reject('Blob has been released.)
```
needs to be changed to
```
      return Promise.reject('Blob has been released.')
```

**Comment by rightaboveit** [comment]
Unterminated*

**Comment by larryranches** [comment]
Yes we are seeing this on our end as well. Pretty critical to get fixed.

**Comment by mike-aungsan** [comment]
Same issue. 
npm: 5.3.0
node 8.2.1
OS: Win 8.1

**Comment by wkh237** [comment]
Thanks ! Just publish a new version 0.10.8 to `npm`  👍

**Comment by mikemonji** [comment]
WOW, prompt response. Love you guys for this...
