### ISSUE TITLE
I need help to read a stream type Uint8Arrays (or at least save it into file)

### ISSUE THREAD

**Issue by rubelux** [wkh237/react-native-fetch-blob#459]
I am trying to play an audio file with Uint8Arrays format that [AWS Polly](https://aws.amazon.com/polly/) returns. For that, I read it as a stream, but just keep getting errors from the bridge saying 'Invalid data message - all must be length: 8'. It happens when I try to open the stream: `ifstream.open()`

```javascript
//polly config
const params = {
    LexiconNames: [], 
    OutputFormat: "mp3", 
    SampleRate: "8000", 
    Text: "All Gaul is divided into three parts", 
    TextType: "text", 
    VoiceId: "Joanna"
};

Polly.synthesizeSpeech(params, function(err, data) {
    let _data = "";
    RNFetchBlob.fs.readStream(
        // file path
        data.AudioStream,
        // encoding, should be one of `base64`, `utf8`, `ascii`
        'ascii'
    )
    .then((ifstream) => {
        ifstream.open()
        ifstream.onData((chunk) => {
            _data += chunk
        })
        ifstream.onError((err) => {
            console.log('oops', err.toString())
        })
        ifstream.onEnd(() => {  
            //pasing _data to streaming player or normal audio player
            ReactNativeAudioStreaming.play(_data, {showIniOSMediaCenter: true, showInAndroidNotifications: true});
        })  
    })
}); 

```

Another solution I have also tried is to save the stream into a file to load it later on, but I need to merge all the array pieces into one array 

```RNFetchBlob.fs.createFile("myfile.mp3", dataG.AudioStream, 'ascii');```

Much appreciate any help, I have been quite blocked with this for a while

Ruben

**Comment by wkh237** [comment]
@rubelux , I'd like to know if this happens on both Android and IOS? Also, what's the RN's version? 

I have just done a test using `readStream` with a 22MB file and it's working correctly. Could you provide the file or is there any way I can replicate the error?

**Comment by rubelux** [comment]
@wkh237 Thanks for helping me out, 
so the RN version is: 0.43.3 and I'm targeting IOS only (for the time being)

The only way to reproduce this would be by using the AWS Polly and because I believe the problem is in the type of Uint8Arrays that it returns.

**Comment by rubelux** [comment]
I could copy here the Uint8Arrays log if that would help

**Comment by lll000111** [comment]
A reproducible self-contained example would help. I myself can only look at Android issues though, and the project owner is pretty busy. How comfortable do you yourself feel trying to debug the issue? I found the code - even the iOS one that was completely new to me and for which I don't even have an IDE, only gray plain text - pretty accessible. There also is the https://github.com/wkh237/react-native-fetch-blob-dev repository with a test environment for this package.

**Comment by fredbt** [comment]
@rubelux have you found a solution for this? I have a similar use case here.

**Comment by lll000111** [comment]
One question:  You accumulate over `let _data = "";`. If the type is `ascii`, shouldn't you have an array? It should look something like this, an array of 0.255 numbers: `[102, 111, 111, 12, 0, 242, ...]`

**Comment by ohtangza** [comment]
So, was this resolved?

**Comment by shrinandhini2801** [comment]
I am facing same issue . Please let me know if anybody finds a solution for this.
