### ISSUE TITLE
[Android] Did not get file absolute path 

### ISSUE THREAD

**Issue by HKbool** [wkh237/react-native-fetch-blob#462]
I use `react-native-document-picker` to get uri of pdf-file.
like this,

> DocumentPicker.show({
>       filetype: [DocumentPickerUtil.allFiles()],
>     },(error,res) => {
>        this.setState({pdf_uri:res.uri})
>       this.setState({fileName:res.fileName})
>         console.log(res);
> }

.
I get this 
![2508b833-da25-44ed-be2a-2ab88c65ce33](https://user-images.githubusercontent.com/16604879/29015332-3323a8da-7b80-11e7-99a6-c5fb5370f17f.png)
and then , I used `RNFetchBlob.fs.writeFile`

> RNFetchBlob.fs.writeFile(dirs.CacheDir+'/'+this.state.fileName,this.state.pdf_uri,'uri')
>         .then((success) => {
>           // this.setState({suc_uri:RNFS.CachesDirectoryPath+'/'+this.state.fileName})
>           console.log(success)// **_there just return fileSize , why???_**
>           console.log('FILE WRITTEN!');
>         })
>         .catch((err) => {
>           console.log(err);
>         });

and  I changed code ,

> RNFetchBlob.fs.readFile(this.state.pdf_uri,'base64')
>         // files will an array contains filenames
>         .then((files) => {
>           this.setState({base64Str:files})
>             // console.log(files)
>         })

> RNFetchBlob.fs.writeFile(dirs.CacheDir+'/'+this.state.fileName,this.state.base64Str,'base64')
>         .then((success) => {
>           console.log(success) // **_there is also return fileSize_**
>           console.log('FILE WRITTEN!');
>         })
>         .catch((err) => {
>           console.log(err);
>         });

i want to use `react-native-pdf-view` to open pdf-file,how can i change code or have anywhere wrong in here.

help,thanks

"react-native": "0.47.1",
"react-native-document-picker": "^2.0.0",
"react-native-fetch-blob": "^0.10.8",
"react-native-fs": "^2.5.1",
"react-native-pdf-view": "^0.3.2"

> 

>

**Comment by mohamedtijani** [comment]
@HKbool  you have to find a solution please
