### ISSUE TITLE
Chunk 

### ISSUE THREAD

**Issue by sm2017** [wkh237/react-native-fetch-blob#464]
How to read Chunk of a file ?

**Comment by lll000111** [comment]
You have to read the file and select the chunk that you want in your own code. There is no mechanism in the code to start at an offset and read only a number of bytes.

**Comment by sm2017** [comment]
>Feature request?

Yes


Can you implement it? because for large files it is needed

**Comment by wkh237** [comment]
We're working on this feature, the implementation is finished just no time test it. I'm closing this issue as this is what #124 does.
