### ISSUE TITLE
Example code for writeStream ignores that stream.write() returns a promise?

### ISSUE THREAD

**Issue by lll000111** [wkh237/react-native-fetch-blob#467]
The example code at https://github.com/wkh237/react-native-fetch-blob#file-stream completely ignores the promise returned by the `write` function.

Now I wonder, if it does not matter, why return a promise? But if it matters, don't I have to wait for the promise? One, to be sure of success, two, for sequencing the writes correctly?

**Comment by wkh237** [comment]
Well, basically it does not matter because the fs I/O operations are queued and executed in the same thread.

**Comment by lll000111** [comment]
That leaves open the problem of a rejected writer promise though....

**Comment by lll000111** [comment]
Suggestion (very short PR on the way): If `write()` resolves with the `RNFetchBlobWriteStream` instance instead of with `undefined` the `write` calls can be chained:

```javascript
[return] RNFetchBlob.fs.writeStream(PATH_TO_FILE, 'utf8', true)
.then((ofstream) => ofstream.write('foo'))
.then((ofstream) => ofstream.write('bar'))
.then((ofstream) => ofstream.write('foobar'))
.then((ofstream) => ofstream.close())
```

No more issues with unhandled rejections, AND the returned promise now resolves when the last write actually happened, the original example code resolves when the stream object is created.

This is optional, since writes are in the order they are issued (Are they? Does the low-level iOS and Android code guarantee that?) an alternative is to issue all writes at once:

```javascript
[return] RNFetchBlob.fs.writeStream(PATH_TO_FILE, 'utf8', true)
.then((ofstream) => Promise.all([
    ofstream.write('foo'),
    ofstream.write('bar'),
    ofstream.write('foobar')
]))
// Use array destructuring to get the stream object from the first item
.then(([ofstream]) => ofstream.close())
```

**Comment by lll000111** [comment]
@wkh237 I don't understand how Github and git work. When I try to create a pull request all the previous changes from the already merged pull request from yesterday are in it again! Even though I update my local repo!

Could you please insert [this tiny patch](https://github.com/lll000111/react-native-fetch-blob/commit/c17106d4370eb2081e63e7055df93949c3a2a699) manually? I HATE git, it is WAY too complex (the correct word: not complicated but complex - complexity arises from interactions of by themselves very simple things).

**Comment by lll000111** [comment]
TODO for myself: PR to update the documentation for 0.10.9 too

**Comment by lll000111** [comment]
I'm closing it here and create a link to this issue in my own copy of this repo.
