### ISSUE TITLE
Bug - Android cannot import the module

### ISSUE THREAD

**Issue by niros001** [wkh237/react-native-fetch-blob#470]
Hi, i'am using:
react-native 0.44
react-native-fetch-blob 0.10.8
And when i only use this:
`import RNFetchBlob from "react-native-fetch-blob"`
I got that error:
`Attemp to invoke virtual method "java.io.Filejava.io.File.getParentFile()" on a null object reference`
* In ios everything work perfect.

**Comment by lll000111** [comment]
I think it would help a lot if you could include the particular piece of code that caused it. `fs.writeFile` is just one of four locations (and functions) in the code where that method is called, just to give an example.

**Comment by lll000111** [comment]
I'll close this for now. Feel free to reopen with new information.
