### ISSUE TITLE
[Android] Android 7.0 permission issue

### ISSUE THREAD

**Issue by CptMaumau** [wkh237/react-native-fetch-blob#471]
Hi, using 0.10.8 and using an android emulator with API 24 and android 7.0 I get `Permission Denial: requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()`

According to the [Android patch note](https://developer.android.com/about/versions/nougat/android-7.0-changes.html#perm) 

> To share files between applications, you should send a content:// URI and grant a temporary access permission on the URI. The easiest way to grant this permission is by using the FileProvider class. 

Has anyone run into this issue?

**Comment by lll000111** [comment]
I don't really know, but since nobody responded, is this an RNFB issue or an RN issue? Link: https://facebook.github.io/react-native/docs/permissionsandroid.html

**Comment by rochapablo** [comment]
https://github.com/joltup/react-native-fetch-blob/issues/59

**Comment by paruckerr** [comment]
Nothing??? Same problem...

**Comment by lll000111** [comment]
@paruckerr Please read the README.
