### ISSUE TITLE
writeFile: inconsistent behavior Android vs. iOS?

### ISSUE THREAD

**Issue by lll000111** [wkh237/react-native-fetch-blob#483]
`writeFile` insists that the file already exists as far as my own Android experiences show. I looked up the Java source code and the Java documentation, and basically all they say is

> [Whether or not a file is available or may be created depends upon the underlying platform.](https://docs.oracle.com/javase/7/docs/api/java/io/FileOutputStream.html)

Do you *want* this behavior, or is this completely accidental?

Looking at the iOS sources too: I think Android and iOS `writeFile` behavior differ? iOS: https://github.com/wkh237/react-native-fetch-blob/blob/master/ios/RNFetchBlobFS.m#L342 It seems to me that the iOS version creates the file if it does not exist. The Android version doesn't do anything explicitly, it uses the _unspecified_ behavior of `new FileOutputStream`: https://github.com/wkh237/react-native-fetch-blob/blob/master/android/src/main/java/com/RNFetchBlob/RNFetchBlobFS.java#L75

**Comment by wkh237** [comment]
I think the IOS one is correct, it should create a file if it doesn't exist, just like Node.js does.

**Comment by lll000111** [comment]
I'm taking care of it in my upcoming PR. It's inline 66: https://github.com/lll000111/react-native-fetch-blob/blob/0.10.9/android/src/main/java/com/RNFetchBlob/RNFetchBlobFS.java#L53
