### ISSUE TITLE
RNFetchBlob.fs.readFile default settings doesnt function

### ISSUE THREAD

**Issue by hasancanozkan** [wkh237/react-native-fetch-blob#484]
RN: 0.47.1  
fetch-blob: 0.10.8
I just realized that RNFetchBlob.fs.readFile default setting doesnt work, i have to specify 'utf8' in the Promise. This could also be related the issue #450 , because I was getting the same error if i dont specify utf8. I hope you fix this

**Comment by lll000111** [comment]
I'll add it to my upcoming pull request for 0.10.9.
