### ISSUE TITLE
writeStream() does not create file if it doesn't exist?

### ISSUE THREAD

**Issue by lll000111** [wkh237/react-native-fetch-blob#491]
Android: https://github.com/wkh237/react-native-fetch-blob/blob/master/android/src/main/java/com/RNFetchBlob/RNFetchBlobFS.java#L324

iOS: https://github.com/wkh237/react-native-fetch-blob/blob/master/ios/RNFetchBlob/RNFetchBlob.m#L219

Right now `writeStream()` starts by checking if a file exists and/or is a directory.

I'm not sure about the behavior on "file does not exist". Shouldn't the default for a write stream be to create the file if it doesn't exist?

**Comment by wkh237** [comment]
Well .. basically I'll reference [node.js's fs API](https://nodejs.org/api/fs.html).

**Comment by lll000111** [comment]
This creates the file if it does not exist:

```
$ node
> const fs = require('fs')
undefined
> let s = fs.createWriteStream('FOO')
undefined
> s.write("#!/usr/bin/node\n");
true
> s.end()
```

**Comment by wkh237** [comment]
Okay, I think as long as it's acting consistently across different platform that would be fine 😄

**Comment by lll000111** [comment]
Commited to my own repo's 0.10.9 branch.
