### ISSUE TITLE
For anyone maintaining old projects with React-native version 0.34

### ISSUE THREAD

**Issue by bjacog** [wkh237/react-native-fetch-blob#493]
Mod is welcome to tag this as not an issue, I just thought I'd share as I could not find any version matching in the readme between RN and fetch-blob and google came up empty.

We recently tried to build an app using 0.10.8 and ran into an issue:
```
...node_modules/react-native-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java:26: error: cannot find symbol
```
The line in question was in RNFetchBlobReq.java:
```
import com.facebook.react.modules.network.TLSSocketFactory;
```

This was caused by TLSSocketFactory not being in our react-native yet which was at 0.34. Since the project could not be upgraded due to navigation issues we started looking into when this was added to react-native-fetch-blob.

We changed rn-fetch-blob to use 0.10.6 and the project built for Android without problems.
Obviously, any issues fixed since 0.10.6 would be there.

**Comment by hgonzalez94** [comment]
god bless
