### ISSUE TITLE
How to send image with external bodyData ? 

### ISSUE THREAD

**Issue by Clcll** [wkh237/react-native-fetch-blob#503]
RNFetchBlob.fetch('POST', uploadUrl, {
                'Accept': 'application/json',
                'Content-Type': 'multipart/form-data',
            },
            [
                {
                    name: name,
                    filename: filename,
                    type: fileType,
                   **fields ----- this**,  nothing happens 
                    data: RNFetchBlob.wrap(url.replace('file://', ''))
                },
                **fields ----- this** crash application
            ])

How to send with **data** external fields ?

**Comment by lll000111** [comment]
I think you might find something in the Wiki: https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#available-request-body-types ("usage : Multipart form data").
