### ISSUE TITLE
TODO: fs.hash(..) function only works for files for which we have a path but not for URIs

### ISSUE THREAD

**Issue by lll000111** [wkh237/react-native-fetch-blob#509]
`fs.hash` can only deal with files for which we have a path. Since all it needs is an input stream and that has already been implemented I can look at 

https://github.com/lll000111/react-native-fetch-blob/blob/0.10.9/android/src/main/java/com/RNFetchBlob/RNFetchBlobFS.java#L153

Not sure if this also needs to be done for iOS, the `readFile` method there looks pretty simple so maybe not.

_Ticket assigned to myself._

**Comment by winpuc** [comment]
I'd expect this to be useful at least for URLs that resolve locally like content://media/external/images/media/1133.

The current behaviour is confusing because the error message says "File doesn't exist" but fs.exists returns true.

At least the error message should be fixed.

**Comment by lll000111** [comment]
Tested by @winpuc - code update checked in, PR to be created next
