### ISSUE TITLE
[Android] undefined is not an object (evaluating 'RNFetchBlob.DocumentDir')

### ISSUE THREAD

**Issue by dphov** [wkh237/react-native-fetch-blob#51]
Hello!

This error appears at start launch in the simulator/device.

In my example I'm trying implement this part of code, how we can avoid this issue?

Thank you in advance.

`  componentDidMount() {
    RNFetchBlob
  .config({
    // add this option that makes response data to be stored as a file,
    // this is much more performant.
    fileCache : true,
  })
  .fetch('GET', 'https://homepages.cae.wisc.edu/~ece533/images/mountain.png')
  .then((res) => {
    // the temp file path
    console.log('The file saved to ', res.path('/'))
  })
      requestPermission("android.permission.ACCESS_FINE_LOCATION").then((result) => {
        console.log("Granted!", result);// now you can set the listenner to watch the user geo location
        }, (result) => {
        console.log("Not Granted!");
        console.log(result);
        });`

react-native@0.29.0
react-native-cli@1.0.0
react@15.2.0
react-native-fetch-blob@0.6.3-dev.1

![img1](https://cloud.githubusercontent.com/assets/8191815/16757248/24da68bc-4824-11e6-9c5a-df789ebbc8a4.jpg)
![img2](https://cloud.githubusercontent.com/assets/8191815/16757250/2743307a-4824-11e6-848c-44fe4bd82188.jpg)

**Comment by wkh237** [comment]
Hi @dphov , It looks like your package is not linked properly, did you restart your packager after install the package ? the module has many native code so you have to rebuild the project after install it.

**Comment by dphov** [comment]
Hi @wkh237 , 
1. I'm restarted packager
2. ran `npm install`
3. ran `rnpm link`

And I got the same error

**Comment by wkh237** [comment]
Did you save the package dependency to `package.json` ? rnpm does not work if the package could not be found in `package.json`.

could you try the following commands ?

```
$ npm install --save react-native-fetch-blog@0.6.3-dev.1
$ rnpm link react-native-fetch-blob
$ react-native run-android
```

**Comment by dphov** [comment]
package.json after running commands
`  "dependencies": {
    "react": "15.2.0",
    "react-native": "0.29.0",
    "react-native-android-permissions": "^0.0.6",
    "react-native-cli": "^1.0.0",
    "react-native-fetch-blob": "^0.6.3-dev.1",
    "undefined": "^0.1.0"
  }`

got same error  again

**Comment by wkh237** [comment]
Hi @dphov , I've noticed that the error message is saying `RNFetchblob.DocumentDir` instead of `RNFetchBlob.fs.dirs.DocumentDir`, could you try changing it from your code and see if this works ?

**Comment by dphov** [comment]
fs.js
```
...
const dirs = {
    DocumentDir :  RNFetchBlob.fs.dirs.DocumentDir,
    CacheDir : RNFetchBlob.CacheDir,
    PictureDir : RNFetchBlob.PictureDir,
    MusicDir : RNFetchBlob.MusicDir,
    MovieDir : RNFetchBlob.MovieDir,
    DownloadDir : RNFetchBlob.DownloadDir,
    DCIMDir : RNFetchBlob.DCIMDir
}
...
```

Error:
![225512622_13309556757415055642](https://cloud.githubusercontent.com/assets/8191815/16758447/f9828b48-482a-11e6-8265-bf557c3ea934.jpg)
![225524099_2649258526146943969](https://cloud.githubusercontent.com/assets/8191815/16758481/331824da-482b-11e6-9668-06879c186dd1.jpg)

**Comment by wkh237** [comment]
This may also related to changes in `0.29` , could you check `MainApplication.java` in `/android/app/src/main/java/com/<project name>t/MainApplication.java`, see if the RNFetchBlobPackage is added into package list ?

```diff
 @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          // Add this line if it does not exists
+         new RNFetchBlobPackage()                                                                                                                
      );
    }
```

Add the missing package and compile to see if it work 👍

**Comment by wkh237** [comment]
- [ ] Add 0.29 instruction to README.md
- [ ] Change rnpm link script

**Comment by dphov** [comment]
MainApplication.java
```
package com.awesomeproject;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import com.RNFetchBlob.RNFetchBlobPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNFetchBlobPackage(),
          new RNPermissionsPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```
added import com.RNFetchBlob.RNFetchBlobPackage;
added new RNPermissionsPackage()

Error:

![222829449_16365169123451930029](https://cloud.githubusercontent.com/assets/8191815/16758974/2129dfd6-482e-11e6-930d-52e1d2ec66c8.jpg)

![225514929_9654000154810424985](https://cloud.githubusercontent.com/assets/8191815/16758984/29117b46-482e-11e6-850c-f966ee788d58.jpg)

**Comment by wkh237** [comment]
I think you can undo the change about `RNFetchBlob.DocumentDir` I mentioned above.

```diff
...
const dirs = {
+    DocumentDir :  RNFetchBlob.DocumentDir,                                                                                  
-    DocumentDir :  RNFetchBlob.fs.dirs.DocumentDir,                                                                                  
    CacheDir : RNFetchBlob.CacheDir,
    PictureDir : RNFetchBlob.PictureDir,
    MusicDir : RNFetchBlob.MusicDir,
    MovieDir : RNFetchBlob.MovieDir,
    DownloadDir : RNFetchBlob.DownloadDir,
    DCIMDir : RNFetchBlob.DCIMDir
}
...
```

I think  it should then work properly !

**Comment by dphov** [comment]
Hurray! It works! Thank you!

**Comment by wkh237** [comment]
That's great 👍  Please feel free file an issue if something's going wrong 😄

**Comment by dphov** [comment]
Sure! 😄  👍

**Comment by shirleycharlin** [comment]
Commenting just in case anyone encounter **the same issue when compiling IOS**. 

I have also encountered this when I transfer my project to a new macbook.

Solution:
Run the app on the simulator.
Delete away the build file inside IOS folder. 
At the simulator, go to Simulator > Reset content and setting
Rebuild the app again - react-native run-ios


Credits to this link: http://stackoverflow.com/questions/35611765/react-native-run-ios-command-fails-pch-issues-but-build-succeeds-in-xcode

**Comment by wkh237** [comment]
@shirleycharlin , great thanks for your additional information 👍

**Comment by RichardBoyewa** [comment]
I am still having this same issue @dphov reported, I have done the linking but the error persists on Android. Is there any other reason 
```js
 RNFetchBlob 
``` 
will be undefined? Cos I get error  `undefined is not an object (evaluating 'RNFetchBlob.DocumentDir')`

1. "react-native-fetch-blob": "^0.8.2",
2.  "react-native": "0.30.0",

**Comment by wkh237** [comment]
@RichardBoyewa , I've write some instructions in other thread, let's discuss this issue [here](https://github.com/wkh237/react-native-fetch-blob/issues/84), Thank you: )

**Comment by snjjain11** [comment]
I'm getting the error not able to find the symbol RNFetchBlobPackage after adding the package in main application

**Comment by snjjain11** [comment]
before that i was getting the error undefined is not an object (evaluating 'RNFetchBlob.DocumentDir')

**Comment by slender9168** [comment]
Two things solved the problem for me:
1- use the react-native link command
2- deploy the app again to the device from android studio ( i think using the package manager (npm start) only packages the new javascript code, not the library native code )

**Comment by valerybodak** [comment]
@dphov 
How did you resolve this issue? I have the same error on Android emulator. 
My dependencies from package.json:

"dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-drawer": "^2.3.0",
    "react-native-fetch-blob": "^0.10.5",
    "react-native-localization": "^0.1.30",
    "react-native-router-flux": "3.39.1",
    "react-native-video": "^1.0.0"
  },

**Comment by Antoine-Mace** [comment]
@valerybodak [https://github.com/wkh237/react-native-fetch-blob/issues/371](url)

**Comment by martianmartian** [comment]
newbies? read this post. https://blog.nativebase.io/adding-third-party-native-modules-using-react-native-cbcb9e3786ba

**Comment by huangtubiao** [comment]
@wkh237 @shirleycharlin I got the same issue when compiling IOS, but it work when compiling Android.I follow your steps to solve, but still not work.

dependencies：
1、"react-native": "0.44.0",
2、"react-native-fetch-blob": "^0.10.8"


Compile Error：
** BUILD FAILED **



The following build commands failed:
	CompileC /Users/leo/code/RNDemo/ios/build/Build/Intermediates/TcpSockets.build/Debug-iphonesimulator/TcpSockets.build/Objects-normal/x86_64/TcpSockets.o TcpSockets.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/RNDemo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by percyhanna** [comment]
For future posterity: I also ran into this problem because I was accidentally still running a React packager for a different project. I assume they got their wires crossed somehow. Not sure if it's expected to be able to run 2 packagers side-by-side or not?

**Comment by harish-aka-shivi** [comment]
If you are making a Activity and implementing DefaultHardwareBackBtnHandler,  then in your `onCreate(Bundle savedInstanceState)`,  use addPackage() method like this:


`mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new RNFetchBlobPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
`

**Comment by krishan-kumar-mourya** [comment]
After linking you need to run
`pod update`

**Comment by frostover** [comment]
*This is solution for Android build. I didn't have any issues with iOS, some of these steps might help for iOS as well.*

First make sure the package is installed 
`npm install react-native-fetch-blog`

Next make sure it's included your package.json file (your version number might be different, just make sure it's there)
```
"dependencies": {
  "react-native-fetch-blob": "^0.10.8",
}
```

Next link the react-native-fetch-blob package directly using
`react-native link react-native-fetch-blob`

Next verify that the package is included in `app/src/main/java/com/[APP-NAME]/MainApplication.java`. Find the `getPackages()` function, inside there you should see `new MainReactPackage()`, among other packages. Look for `new RNFetchBlogPackage()`, if it's not in this list, add it.

Try to build the project. If you get an error `error: cannot find symbol new RNFetchBlobPackage()` then go back to the file `app/src/main/java/com/[APP-NAME]/MainApplication.java` and add `import com.RNFetchBlob.RNFetchBlobPackage;` to the top with the other imports. Try to build and it should work.

All these steps ended up working for me and the project was built.
