### ISSUE TITLE
Can't create file with base64 code in it

### ISSUE THREAD

**Issue by SkunSHD** [wkh237/react-native-fetch-blob#514]
Can't create base64 file with [createFile method](https://github.com/wkh237/react-native-fetch-blob/wiki/File-System-Access-API#createfilepath-data-encodingpromise)

Base64 code that I'm trying to save is [cropped image](https://github.com/stoffern/react-native-image-cropper)

The same base64 code, that I can't save, [this app](https://codebeautify.org/base64-to-image-converter) understands without problems

So in the end`RNFB.fs.createFile()` creates just empty file.
What restrictions on base64 code could possibly be that could impede for saving info in it?

Base64 code that I'm trying to save:
https://hastebin.com/odugonivut.go

P.S. I'm using react-native-fetch-blob@0.10.8

**Comment by niros001** [comment]
I have problem with creating image file too with `RNFB.fs.createFile()`.
The file success to create and have the base64 data but when i try to render the file i can't see the image:
`<Image style={{width: 250, height: 250}} source={{uri:FILE_PATH}}/>`

**Comment by SkunSHD** [comment]
The problem solved! [ReadSrteam method](https://github.com/wkh237/react-native-fetch-blob/wiki/File-System-Access-API#readfilepath-encodingpromise) helped with that.

Because:
> Read the file from the given path, if the file is large, you should consider use readStream instead.

Final version of code:
`RNFB.fs.createFile(path, '', 'utf8').then((res) => {
                    RNFB.fs.writeStream(path, 'base64').then((stream) => {
						stream.write(base64Data.substr(index + 1));
						return stream.close();
                    })`

**Comment by niros001** [comment]
index???

**Comment by lll000111** [comment]
Cat.

_(I too know words.)_

**Comment by lll000111** [comment]
Look, @niros001, downvoting me won't help you. If you are unable to provide a USEFUL comment that lets us know what on earth you actually want than please stay away and don't waste our time!

I had written:

Cat.

_I too know words. Most humans prefer whole sentences though, enhances the potential benefits of conversations tremendously. Efficiency through brevity is nice - but useless if efficacy goes towards zero._
