### ISSUE TITLE
Android download succeeding but not showing in file manager (redux-saga)

### ISSUE THREAD

**Issue by Noitidart** [wkh237/react-native-fetch-blob#515]
Super basic question I have here. 

I have not added any extra permissions because I am only writing to internal storage of `RNFetchBlob.fs.dirs.DocumentDir`.

I  am trying to download an image from dropbox, I do so like this, I am using redux-saga:

```js
const path = `${RNFetchBlob.fs.dirs.DocumentDir}/blah.png`;
const req = RNFetchBlob.config({
    path
});
const res = yield call([req, req.fetch], 'POST', 'https://content.dropboxapi.com/2/files/download', {
    Authorization: 'Bearer ' + TOKEN,
    'Dropbox-API-Arg': JSON.stringify({
        path: asset.dropbox
    })
});
```

This returns `res.respInfo.status` of `200` and doing `res.path()` gives me the expected path which I hold in `const path`, but going to this directory with file manager on Android, does not show the file there.

I must be doing something wrong. I really appreciate your help with my question.

**Comment by Noitidart** [comment]
The path is `/data/user/0/com.myapp/files/Sep 10th 2.53 pm.png` and when I go to File Manager > `/Android/data/com.myapp/files/` it's empty. :(

**Comment by emilebres** [comment]
Actually `/data/user/0/com.myapp/files/` and File Manager > `/Android/data/com.myapp/files/` are not the same folder. 
The path for the second one is `/storage/self/primary/Android/data/com.myapp/files/`. So it makes sense that you don't see anything. If you want to see if your files are there, rather use `adb` (see https://developer.android.com/studio/command-line/adb.html). 
For example:
- `adb shell`
- `run-as myapp`
- `ls files`
and you should see your files.

**Comment by Noitidart** [comment]
Ah thank you very much sir. That is very interesting. Thank you for leaving this open for me to close.
