### ISSUE TITLE
Android, even with `file://` prefix, it is not loading into `<Image>`

### ISSUE THREAD

**Issue by Noitidart** [wkh237/react-native-fetch-blob#517]
On Android I am using the following snippet, this is right from the readme - https://github.com/wkh237/react-native-fetch-blob/#download-to-storage-directly

```js
RNFetchBlob
  .config({
    fileCache : true,
    appendExt : ext // i use proper ext here
  })
  .fetch('GET', url)
  .then((res) => {
    imageView = <Image source={{ uri : Platform.OS === 'android' ? 'file://' + res.path() : res.path() }}/>
  })
```

However it is not loading. There is not even a trigger of `onError` nor `onLoadStart` nor `onLoadEnd` nor `onLoad` .

I did not add any extra permissions, as I use this same method to load videos to with `react-native-video` and it works fine. It's just `<Image>`s, does anyone know why?

**Comment by Noitidart** [comment]
I have also tried specifying the `type` key in `source` like this:

```
<Image source={{ uri : 'file://' + res.path(), type:ext }}/>
```

However this did not fix it either.

**Comment by lll000111** [comment]
When I look at page

https://facebook.github.io/react-native/docs/image.html

the source for images from teh filesystem is used like this.

    source={require('./img/favicon.png')}

Could you try that?

**Comment by Noitidart** [comment]
Thanks very much @lll000111 for your help and trying to google. I really appreicate your help, very much!  I also searched hard but nothing helped. Doing `require('absolute path here')` caused a red box error of "_require@http://localhost:8081/index.android.bundle?platform=androind&dev=true&hot=false&minify=false:46:22`, with more stuff that doesnt make sense. I tried doing `require('file://absolute path here')` and the same happened there. I thought this made sense because `require` is usually transpiled into something at build time, so I didnt think it would work with a variable string at runtime. Any other ideas sir? :(

**Comment by lll000111** [comment]
> and trying to google. I really appreicate your help, very much! I also searched hard but nothing helped

Well... it would be nice to see _all_ relevant information right away.

**Comment by lll000111** [comment]
Feel free to reopen if you have new information.

**Comment by Noitidart** [comment]
Thank you sir.

> Reading the description here (link) you could try reading the image as base64 encoded string and using a data: URI.

If i load as base64, the resources are so big it eventually causes a crash.

> Did you specify a size?

Yes I specified with and height

> Feel free to reopen if you have new information.

Thanks for bearing with me. I will keep trying. I will try to write a test for you all.

**Comment by lll000111** [comment]
You could try asking on StackOverflow, with as detailed information as possible (or they'll get mad and you get downvotes).

**Comment by Noitidart** [comment]
Thank you sir for re-opening due to my comment. I really respect that. I will close as you originally intended and will try to add the material you recommended here.
