### ISSUE TITLE
'RNFB_ANDROID_PERMISSIONS' is not recognized

### ISSUE THREAD

**Issue by rami-diwip** [wkh237/react-native-fetch-blob#519]
Hi, 
Sorry for this newbie question but i couldn't find any solution.
After installation i got:

> react-native-fetch-blob will not automatically add Android permissions after 0.9.4 please run the following command if you want to add default permissions :
> 
>         RNFB_ANDROID_PERMISSIONS=true react-native link

when trying to run  RNFB_ANDROID_PERMISSIONS=true react-native link in the command line i got:

> 'RNFB_ANDROID_PERMISSIONS' is not recognized as an internal or external command,
> operable program or batch file.

Do i have missing path in the environment variables?

**Comment by lll000111** [comment]
You are trying this in a Windows console, but that syntax is for a shell, `bash` for example. If you have Git for Windows (you already have Windows, and everybody should have git so there is a high chance you installed that package?) it provides a bash shell (bash.exe).

For Windows: https://superuser.com/questions/212150/how-to-set-env-variable-in-windows-cmd-line

**Comment by rami-diwip** [comment]
thanks for the quick and helpful respond

**Comment by aditodkar** [comment]
@lll000111 @rami-diwip  I am getting same problem how to fix it ? I am using windows 10

**Comment by lll000111** [comment]
@aditodkar https://github.com/wkh237/react-native-fetch-blob/blob/master/README.md

**Comment by aditodkar** [comment]
@lll000111  Yes I have seen the readme file but in CMD in windows 10 when I do -> `RNFB_ANDROID_PERMISSIONS=true react-native link` it says unrecognized

**Comment by lll000111** [comment]
If you saw the README you should know that this repository is unmaintained and that asking here therefore is futile. There is a new maintainer.

So again:

https://github.com/wkh237/react-native-fetch-blob/blob/master/README.md

**Comment by aditodkar** [comment]
@lll000111 After adding `RNFB_ANDROID_PERMISSIONS=true` in system variables still I get error. see screenshot: ![screenshot_9](https://user-images.githubusercontent.com/16613832/52053259-e59eb000-257e-11e9-9584-40331f314226.png)

**Comment by lll000111** [comment]
@aditodkar **PLEASE READ https://github.com/wkh237/react-native-fetch-blob/blob/master/README.md**

**Comment by aditodkar** [comment]
@lll000111 I am using new repo rn-fetch blob but still getting same error. ![screenshot_10](https://user-images.githubusercontent.com/16613832/52053833-80e45500-2580-11e9-8a5e-9cb0fa02dc15.png)
