### ISSUE TITLE
InputStream leak

### ISSUE THREAD

**Issue by dantman** [wkh237/react-native-fetch-blob#524]
PathResolver.java has a InputStream leakage.

https://github.com/wkh237/react-native-fetch-blob/blob/821eeb0/android/src/main/java/com/RNFetchBlob/Utils/PathResolver.java#L78-L92

Line 78 opens an InputStream which is only closed inside the body of a `filename != null` condition. If a filename cannot be determined by `getContentName` or something throws an exception the method will exit without closing the InputStream leaving the JVM to clean it up on its own, which may not happen until the App is terminated.

A try..finally that closes the stream at the end if its not null should be used to prevent leakage of the stream.

**Comment by lll000111** [comment]
Patch commited, is part of PR https://github.com/wkh237/react-native-fetch-blob/pull/510
