### ISSUE TITLE
Cannot Share using RNFetchBlob

### ISSUE THREAD

**Issue by michaelspeed** [wkh237/react-native-fetch-blob#526]
I am trying to share an image after downloading from an URL.
the code to reproduce - 

```js
const dirs = RNFetchBlob.fs.dirs
    RNFetchBlob
      .config({
        fileCache: true,
        appendExt: 'jpg'
      })
      .fetch('GET', this.props.file)
      .then((res) => {
        Share.share({
          url: res.path()
        })
      })
```

But this approach works with iOS, but it sends a blank url in Android.
i tried - 
```js
Share.share({
          url: 'file://'+res.path()
        })
```

But it still sends null in Android

maybe related to #517

**Comment by lll000111** [comment]
According to https://facebook.github.io/react-native/docs/share.html sharing a URL is an iOS thing.

**Comment by michaelspeed** [comment]
i will not open i guess its only iOS thing? but any ideas how to share with android?

**Comment by lll000111** [comment]
Sorry, no. You could ask on StackOverflow.

**Comment by lll000111** [comment]
Actually... have you tried sending the URL in the text message? After all, when you enter stuff on a social media site they automatically parse URLs form the text. Maybe that already is enough.

**Comment by michaelspeed** [comment]
ya that is working good, let me try passing with a native module
