### ISSUE TITLE
typo in class name RNFetchBlobFetchRepsonse

### ISSUE THREAD

**Issue by timLoewel** [wkh237/react-native-fetch-blob#527]
RNFetchBlobFetchRe**ps**onse should probably be RNFetchBlobFetchRe**sp**onse

https://github.com/wkh237/react-native-fetch-blob/blob/45b86cfde232c88f857b470f52b1cddc1ef9f9f5/polyfill/Fetch.js

**Comment by lll000111** [comment]
Thanks, patch commited into an already open PR.
