### ISSUE TITLE
Error invalidPatterns[i].test is not a function

### ISSUE THREAD

**Issue by rhenmark** [wkh237/react-native-fetch-blob#530]
when using window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest I got  this error 'ExceptionsManager.js:65 invalidPatterns[i].test is not a function'. Can someone help me?

**Comment by lll000111** [comment]
Duplicate: https://github.com/wkh237/react-native-fetch-blob/issues/298#issuecomment-331348569
