### ISSUE TITLE
Question about Android Progress 

### ISSUE THREAD

**Issue by AlmogRnD** [wkh237/react-native-fetch-blob#538]
The docs have the following "After 0.7.0 IOS and Android upload progress are also supported."

What exactly does this mean? Can someone a explain this a bit further?

**Comment by lll000111** [comment]
I guess this?

https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#fetchuploadprogressconfig-eventlistenerpromisernfetchblobresponse

**Comment by AlmogRnD** [comment]
Thanks perfect
