### ISSUE TITLE
Support for writing TypedArray's (e.g. UInt8Array)

### ISSUE THREAD

**Issue by jd20** [wkh237/react-native-fetch-blob#547]
With recent support in RN for TypedArray's, is there a way (or planned support) for writing them directly, instead of base64 strings or normal arrays? For example, I tried something simple like:

```
const fs = RNFetchBlob.fs
const dirs = RNFetchBlob.fs.dirs
let path = dirs.DocumentDir + '/test.txt'

let arr = new Uint8Array(10)
fs.writeFile(path, arr, 'ascii')
 .then(() => console.log("Wrote data to: " + path))
```

And this results in an `Error: Expected "data" is an Array when encoding is "ascii", however got object`. For now, I'm working around the issue by converting to a normal array like this:

```
let arr2 = Array.prototype.slice.call(arr)
arr2.length === arr.length
arr2.constructor === Array
fs.writeFile(path, arr2, 'ascii')
  .then( ... )
```

However, I'm thinking there's some performance overhead to this, as it's creating a shallow copy of the entire array (not as bad as Base64 encoding I guess). Would it make sense to add support for RFNB to accept TypedArray's directly?

**Comment by lll000111** [comment]
> With recent support in RN for TypedArray's

Do you have a link?

**Comment by jd20** [comment]
Not sure if I'm misunderstanding what TypedArray support in RN means, but I was going off this [WebKit bug report](https://bugs.webkit.org/show_bug.cgi?id=120112) and facebook/react-native#1424. With a fresh RN 0.48.4 project, I'm able to declare and populate UInt8Array's OK. I thought in older RN versions the TypedArray variants weren't present?

**Comment by lll000111** [comment]
The reason that issue is closed [is this](https://github.com/facebook/react-native/issues/1424#issuecomment-278802057):

> We are trying to keep issues focused on bugs and this is more of a feature request,

So, no, there is no support yet. Please reopen when there is, I'll be the first one to implement the Android side, albeit for the fs functions only (I don't touch the fetch code) since we need it ourselves.
