### ISSUE TITLE
Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'

### ISSUE THREAD

**Issue by whysetiawan** [wkh237/react-native-fetch-blob#566]
I have problem when i upload image but i don't really understand about troubleshooting in wiki page.
I am using 0.10.8. I have tried to downgrade library, but i got another error,  the error was **"listener is not defined"**. What should i do right now? 

~~~~ const uploadImage = (uri, imageName, mime = 'image/jpg') => {

return new Promise((resolve, reject) => {

const uploadUri = Platform.OS === 'ios' ? uri.replace('file://', '') : uri

let uploadBlob = null

const imageRef = firebaseApp.storage().ref('posts').child(imageName)

fs.readFile(uploadUri, 'base64')

.then((data) => {

return Blob.build(data, { type: `${mime};BASE64` })

})

.then((blob) => {

uploadBlob = blob

return imageRef.put(blob, { contentType: mime })

})

.then(() => {

uploadBlob.close()

return imageRef.getDownloadURL()

})

.then((url) => {

resolve(url)

})

.catch((error) => {

reject(error)

})

})

}

**Comment by JazLow** [comment]
I solved it by resetting the window.XMLHttpRequest to it's original state after finished using the fetch blob for uploading my image to cloud.

const Blob = FetchBlob.polyfill.Blob;
// Keep an original copy of window.XMLHttpRequest before set it to FetchBlob.polyfill.XMLHttpRequest
const oriWindowXMLHttpRequest = window.XMLHttpRequest;
window.XMLHttpRequest = FetchBlob.polyfill.XMLHttpRequest;
window.Blob = Blob;



return new Promise((resolve, reject) => {
		Blob.build(imageFile, { type: mime })
			.then(blob => {
				uploadBlob = blob;
				return imageRef.put(blob, { contentType: mime });
			})
			.then(() => {
				uploadBlob.close();
				return imageRef.getDownloadURL();
			})
			.then(url => {
// Reset it to the original WindowXMLHttpRequest after the task has been done completely
				window.XMLHttpRequest = oriWindowXMLHttpRequest;
				resolve(getSuccessResponse(url));
			})
			.catch(error => {
// Reset it to the original WindowXMLHttpRequest after the task has been done completely
				window.XMLHttpRequest = oriWindowXMLHttpRequest;
				showToast(getErrorMessage(error));
				reject(getFailResponse(error));
			});
	});


Hope it helps :)
