### ISSUE TITLE
“RNFetchBlob.fetch is not a function”

### ISSUE THREAD

**Issue by Larney11** [wkh237/react-native-fetch-blob#58]
I keep receiving the error “RNFetchBlob.fetch is not a function”.

I put a more [detailed description of the error on StackOverflow](http://stackoverflow.com/questions/38457345/npm-react-native-fetch-blob-rnfetchblob-fetch-is-not-a-function) if anyone cares to take a look. Thanks.

**Comment by Larney11** [comment]
The problem was I was importing the package wrong.

I was importing it with:  
var RNFetchBlob = require('react-native-fetch-blob');

When it should have been:
var RNFetchBlob = require('react-native-fetch-blob').default;

I forgot the ".default".

**Comment by wkh237** [comment]
@Larney11 , Thank you for point out this problem, though the problem has been solved, others who does not using ES6 may still run into the same situation. 

I'll put related informations to [Trouble Shooting](https://github.com/wkh237/react-native-fetch-blob/wiki/Trouble-Shooting) page for reference. It is also considerable to change the way module is exported if possible, I'' open an issue for this.

Again, thank you for your information, please feel free to get back to here for further assistance 👍
