### ISSUE TITLE
go into error except in chrome debugging

### ISSUE THREAD

**Issue by MervynFang** [wkh237/react-native-fetch-blob#6]
I use fetch to post a base64 image data and always go into error in debug or release. when i open debug js, it success. what's wrong. is it anything i have to setting?

**Comment by wkh237** [comment]
Hi @MervynFang , I'll try to figure it out, thanks for informing !

**Comment by MervynFang** [comment]
I just try in android. 
and it can probably be the problem of atob.
The Error Message is:
ReferenceError: Can't find variable: atob

**Comment by wkh237** [comment]
@MervynFang , It seems `atob` is not supported in js context, and also Blob type, perhaps I have to change the API and documents ..

If you're going to post a BASE64 encoded image, you can just put the string into `body`, like 

```js

      RNFetchBlob.fetch('POST', 'https://content.dropboxapi.com/2/files/upload', {
        Authorization : "Bearer ...",
        more headers ...
        'Content-Type' : 'application/octet-stream',
      }, resp.base64())
      .then((resp2) => {
        console.log(resp2.text())
      })
```
and it will be transformed into something like Blob in native, I think manually doing `atob` is unnecessary.

**Comment by MervynFang** [comment]
@wkh237 got it, thanks a lot
