### ISSUE TITLE
Cannot access base64 data from response

### ISSUE THREAD

**Issue by Larney11** [wkh237/react-native-fetch-blob#60]
I cannot access the base64 data from response data.
For detailed explanation [check out this write up](http://stackoverflow.com/questions/38461979/npm-react-native-fetch-blob-how-to-access-base64-data-inside-object).

**Comment by wkh237** [comment]
Hi @Larney11 , the resonse object looks fine in the screen shot, can you explain more about how you access `resp.data` ? What's the error message ? Because that function looks fine in our test case.

**Comment by Larney11** [comment]
@wkh237 There is no error, the emulator won't open. 
I now access it with resp.data and return it.
The response is then used for the source of the image.
`<Image source={{uri: resp.data}} style={{width: 100, height: 50}} />`.

The problem is now that the image will not display when 'resp.data' is returned.
Am I supposed to decode the response or something?

Thanks for the help.

**Comment by wkh237** [comment]
If that the resp.data doest contains a BASE64 encoded image, you can try the following usage

```js
<Image source={{uri : 'data:image/png;base64, ' + resp.data }} style={imageStyle} />
```

I think you may missed the MIME prefix, try it and see if the image displayed 👍

**Comment by Larney11** [comment]
@wkh237 That works perfect! Thanks very much!

**Comment by wkh237** [comment]
You're welcome :smiley:

**Comment by Larney11** [comment]
Hey @wkh237 . 
I figured your the man to ask this question. If I was to decode a base64 pdf would it look like this:
`var imageBase64 = "data:application/pdf;base64,"+base64Str;`

**Comment by wkh237** [comment]
@Larney11 , If you're going to decode a base64 data you don't need the dataURI prefix (data), just use the BASE64 string as input.

**Comment by Larney11** [comment]
@wkh237 
Thanks for the response.
I might have used the wrong terminology in my question.

This is my RNFetchBlob method containing the above sample code from the previous question.

`fetchAttachment: function(attachment_uri, attachment_mimetype) {

      return new Promise((RESOLVE, REJECT) => {

         RNFetchBlob.fetch('GET', config.apiRoot+'/app/'+pdf_uri)
           .then((res) => {
             let base64Str = res.data;

             var pdf_Base64 = 'data:application/pdf;base64,'+base64Str;

             RESOLVE(pdf_Base64)
           })

           .catch((errorMessage, statusCode) => {

             console.log("Error:",errorMessage)
          });
      })
}`

Does that look alright to you.

**Comment by wkh237** [comment]
@Larney11 , Yeah, that looks fine.

**Comment by Larney11** [comment]
@wkh237 Thanks for your help! [This I was wondering ](http://stackoverflow.com/questions/38662309/how-to-save-pdf-to-android-file-system-react-native). In case you know anything on react-native-fs.

**Comment by wkh237** [comment]
@Larney11 , can I have a look on the BASE64 data you got ? Perhaps the data not encoded correctly.

**Comment by Larney11** [comment]
@wkh237 Not sure what you mean by that. Will I console.log() the 'pdf_Base64' and send it to you?

**Comment by wkh237** [comment]
Okay 👍

**Comment by Larney11** [comment]
**console.log(pdf_Base64) =**
![screen shot 2016-08-02 at 09 23 58](https://cloud.githubusercontent.com/assets/20336495/17321936/eb014a64-5892-11e6-8d52-f6ac2ea2ceb5.png)


It printed almost another 12 pages of similar code.

**Comment by wkh237** [comment]
@Larney11 , I've done some test by download a PDF to storage and display it on Webview and that looks fine. I'm not sure if `Image` component supports PDF format, could you try using [react-native-pdf-view](https://github.com/cnjon/react-native-pdf-view) or Webview ?

**Comment by Larney11** [comment]
@wkh237 
I have been trying to display the PDF on wevview for a while and can't get it working. From what I read React-native-android's webview can only take a uri, and not a storage location or base64

I am currently trying to use react-native-pdf-view but unfortunately it only takes a file path([reference])(https://github.com/cnjon/react-native-pdf-view/blob/master/RNPDFView/RNPDFView.m#L56). And I can't get that file path because of [this](http://stackoverflow.com/questions/38662309/how-to-save-pdf-to-android-file-system-react-native).

Thanks for you time.

**Comment by wkh237** [comment]
@Larney11 , I think you can try to save the BASE64 string to file system without `data:application/pdf,BASE64` prefix. 

It's pretty simple to do this with our fs API

```fs
// destination path of the PDF file
let pdfLocation = RNFetchBlob.fs.dirs.DocumentDir + '/tmp.pdf'
// The base64 encoded string
let pdfBASE64 = 'JEBERi0xLj ....='
RNFetchBlob.writeFile(pdfLocation, pdfBASE64, 'base64')
    .then(() => {
        // use the path `pdfLocation`
    })
```

Hope it's gonna work 😏

**Comment by Larney11** [comment]
Thanks a million for all your help. I'll let you know how it goes.

**Comment by Larney11** [comment]
@wkh237 It works! Thanks for all your help.
**Solution**
[Check out this Stackoverflow solution](http://stackoverflow.com/questions/38662309/how-to-save-pdf-to-android-file-system-react-native).

**Comment by wkh237** [comment]
@Larney11 ,That's great ! I'm glad to be of help 😄
