### ISSUE TITLE
 Exception java.lang.RuntimeException

### ISSUE THREAD

**Issue by jjdp** [wkh237/react-native-fetch-blob#612]
Exception java.lang.RuntimeException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.

```
com.facebook.react.bridge.ReactContext.getJSModule (ReactContext.java:102)
com.RNFetchBlob.RNFetchBlobReq.emitStateEvent (RNFetchBlobReq.java:627)
com.RNFetchBlob.RNFetchBlobReq.done (RNFetchBlobReq.java:455)
com.RNFetchBlob.RNFetchBlobReq.access$100 (RNFetchBlobReq.java:60)
com.RNFetchBlob.RNFetchBlobReq$3.onResponse (RNFetchBlobReq.java:423)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:135)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
```
![err](https://user-images.githubusercontent.com/5244520/33327626-f0bd4994-d492-11e7-85b4-2946aaa813da.png)

happens on RN 0.49.5

Anyone encountered this so far?

It seems it happens when you initialize it too early as I do on mine on index.js

```
const Fetch = RNFetchBlob.polyfill.Fetch;
window.fetch = new Fetch({}).build();
```

or it could be the usage of https://github.com/kfiroo/react-native-cached-image

**Comment by PantTushar** [comment]
Have you found the fix for this? Even I am facing the same problem

**Comment by jjdp** [comment]
i moved the initialization to a later time

**Comment by temitope** [comment]
@PantTushar  @jjdp  running into the same issue.
Can you detail your solution a bit more.
Where/When did you move initialization to? Taking some stabs, hard to reproduce this.

**Comment by jjdp** [comment]
i do `new RNFetchBlob.polyfill.Fetch({}).build()` everytime i want to use it scoped to my function

**Comment by temitope** [comment]
@jjdp thanks for the timely response. Probably not a bad idea for clearer coding.
