### ISSUE TITLE
Another Cannot read property 'DocumentDir' of undefined

### ISSUE THREAD

**Issue by GavinThomas1192** [wkh237/react-native-fetch-blob#627]
I have exhausted all threads on the internet and can't find a solution. 
I'm trying to photo upload to firebase from my react-native app using react-native-fetch-blob. RN ios simulator running iphone 6. I have NOT tried running on android emulator yet, due to android env setup on different computer. 

This line causes the error.
 
    import RNFetchBlob from 'react-native-fetch-blob'

I have read many of the tutorials about using react-native-fetch-blob. 

I can't seem to link it correctly, or please tell me what my issue is. 

    "react": "16.0.0-beta.5",
    "react-native": "0.49.3",
    "react-native-fetch-blob": "^0.10.8",

What I've tried already...

    npm install --save react-native-fetch-blob
    react-native link 
...

    npm install --save react-native-fetch-blob
    react-native link react-native-fetch-blob
...

    rm -rf node_modules, then reinstall, then clean and build
...
I've followed the WIKI to manually link packages. Verified packages are linked via SS's
...

Clean and build after all of these scenario's.

I won't list EVERYTHING I've done because I've literally tried everything on stack and RNFB Issues/github. 

Here are some screenshots from Xcode, RNFB is getting linked correctly, or at least I think.

![screen shot 2017-12-22 at 11 02 50 am](https://user-images.githubusercontent.com/28162527/34310942-31d36006-e70f-11e7-8792-4c722a6effec.jpg)
![screen shot 2017-12-22 at 11 04 34 am](https://user-images.githubusercontent.com/28162527/34310943-31e9c74c-e70f-11e7-880c-464a7f11c93d.jpg)
![screen shot 2017-12-22 at 11 11 01 am](https://user-images.githubusercontent.com/28162527/34310945-31ff6e80-e70f-11e7-8aa1-19fc3bf6cc0a.jpg)
![screen shot 2017-12-22 at 11 21 13 am](https://user-images.githubusercontent.com/28162527/34310946-3215d86e-e70f-11e7-9fea-43255d6ef0d7.jpg)
![screen shot 2017-12-22 at 11 33 40 am](https://user-images.githubusercontent.com/28162527/34310947-322b460e-e70f-11e7-9469-9100c4a7dc63.jpg)
![screen shot 2017-12-22 at 11 44 09 am](https://user-images.githubusercontent.com/28162527/34310948-32438dcc-e70f-11e7-9285-ba554831562d.jpg)

**Comment by GavinThomas1192** [comment]
I've tried almost all google searches already.. 
https://github.com/wkh237/react-native-fetch-blob/issues/251 <==especially this one

**Comment by GavinThomas1192** [comment]
I deleted FBSDK login from my project entirely and it worked. "My code works and I don't know why"

**Comment by ajurav1** [comment]
Hello i have solved this issue---- when you install the `react-native-fetch-blob` and link with iOS, it only provide limited lib on native side.

you can to open project from iOS in Xcode then remove the **library of RNFetchBlob.xcodeproj** from library folder and then again add by right click on library folder from node modules-->**react-native-fetch-blob**--->**iOS folder** --->**add project RNFetchBlob.xcodeproj** then all required file will be there and make sure add lib on build phases also **libRNFetchBlob.a**

it works for me.

Thanks

**Comment by jorgeibarra01** [comment]
i've already tried linking it and have had no luck. 
Tried rebuilding the folder for Android and nothing. 
Is there any extra steps I have to do to install rn-fetch-blob? _

**Comment by sstano** [comment]
Hello, this is a rather painful one. I finally managed to get rid of the error - details [here (issue 251)](https://github.com/wkh237/react-native-fetch-blob/issues/251#issuecomment-433681183). Hope it works for you, too...
