### ISSUE TITLE
[android] Unsupported source URL: RNFetchBlob-file://content://media/external/video/media/669"

### ISSUE THREAD

**Issue by abdulsemiu-atanda** [wkh237/react-native-fetch-blob#648]
Awesome job with this project, I've got an issue where trying to upload a `video` to cloudinary returns `Unsupported source URL: RNFetchBlob-file://content://media/external/video/media/669"` on android. it works as expected in `iOS` any ideas what to do would be deeply appreciated. Thanks

### What I've tried
- Trimmed off `file://` while keeping `content://` and vice versa

### Version
- react-native-fetch-blob v0.10.8
- react-native v0.46.0

PS: I'm using `react-native-image-picker` to select a video file

**Comment by vaibhavpadalia** [comment]
I'm facing the same problem while downloading pdfs in Android. Works fine in iOS.

**Comment by abdulsemiu-atanda** [comment]
@vaibhavpadalia you'll need to use `path` instead of `uri` in android i.e you'll have something like
```js
Platform.OS === 'android' ? RNFetchBlob.wrap(data.path) : RNFetchBlob.wrap(data.uri))
```

**Comment by abdulsemiu-atanda** [comment]
I'm closing out this issue since the solution above seems to fix my problem
