### ISSUE TITLE
Enquires for can this works for IOS? 

### ISSUE THREAD

**Issue by shirleycharlin** [wkh237/react-native-fetch-blob#65]
Hi can I just clarify if this works for IOS too? and I am using E7 :)

Otherwise kindly advise me with alternatives. 

Thanks in advance! :)

**Comment by wkh237** [comment]
Yes, it should work on both Android and IOS.

**Comment by shirleycharlin** [comment]
@wkh237  hi! I just tried to understand your codes and found out that you have written for ios. i am going to try it now ! thanks for being RN firebase's saviour! :)

**Comment by wkh237** [comment]
You're welcome.
