### ISSUE TITLE
 Can not read .xls or .xlsx file

### ISSUE THREAD

**Issue by sumitnitsurat** [wkh237/react-native-fetch-blob#671]
RNFetchBlob - 0.10.8
I am trying to read the .xls file like this 

` RNFetchBlob.fs.readStream(filePath, 'utf8')
                .then((stream) => {
                    let data = '';
                    stream.open()
                    stream.onData((chunk) => {
                        data += chunk
                    })
                    stream.onError((err) => {})
                    stream.onEnd(() => {})`

where file path is path of the file on mobile system. When I am uploading a csv file with delimeter-8 encoded format its working fine. But apart from that other format of .Csv and .Xls, .Xlsx returning reading the data as garbage value. 

It would be great if you can help me with this as I have spent lot of time resolving this but couldn`t. 

Thanks.

**Comment by reviewher** [comment]
XLSX cannot be properly represented in a UTF8 string.  You have to use `binary` type and then convert the binary array to a string:

```js
RNFetchBlob.fs.readFile(filePath, 'binary').then((res) => {
  const data = res.map(x => String.fromCharCode(x)).join("");
  /* data is now a binary string */
  const wb = XLSX.read(input(res), {type:'binary'});
});
```

This is included in [a comment in the SheetJS React Native demo](https://github.com/SheetJS/js-xlsx/blob/master/demos/react/react-native.js#L16).

@lll000111 you can close this
