### ISSUE TITLE
Can't download from https source on Adnroid

### ISSUE THREAD

**Issue by polkolins** [wkh237/react-native-fetch-blob#683]
Do I do something wrong? When I use the same code for ```https://www.rhodeshouse.ox.ac.uk/media/1002/sample-pdf-file.pdf``` or whatever else pdf on https I have 0,00b/0,00b on my notifications panel and download is stopped and connection is in progress all the time. 

```javascript
var url  = "http://www.africau.edu/images/default/sample.pdf";
    const { config, fs } = RNFetchBlob
    let PictureDir = fs.dirs.PictureDir
    let options = {
      fileCache: true,
      addAndroidDownloads : {
        useDownloadManager : true,
        notification : true,
        path:  PictureDir + "/example.pdf",
      }
    }
    config(options).fetch('GET', url).then((res) => {
      Alert.alert("Done");
    });
```
"react": "16.2.0",
"react-native": "0.54.2",
"react-native-fetch-blob": "^0.10.8"

**Comment by smithaitufe** [comment]
Hello, did you succeed in downloading from http?

**Comment by polkolins** [comment]
@smithaitufe I had to leave the project, but no success at that moment

**Comment by yoginair** [comment]
options = {
fileCache : true,
trusty: true,// add this and remove credentials: 'include'
path: fs.dirs.DCIMDir + '/TransactionReceipt.pdf',
addAndroidDownloads: {
title:"TransactionReceipt",
useDownloadManager: false, // set this false
notification: true,
description: 'TransactionReceipt'
}
