### ISSUE TITLE
RNFetchBlob.fs.stat is not providing mime type of the file

### ISSUE THREAD

**Issue by Louies89** [wkh237/react-native-fetch-blob#687]
Currently. the below method is not giving any information about mime type of the file provided.

```
RNFetchBlob.fs.stat(PATH_OF_THE_TARGET)
    .then((stats) => {})
    .catch((err) => {})
```

If something like [this example](https://stackoverflow.com/questions/8589645/how-to-determine-mime-type-of-file-in-android/39923767#39923767) shall be implemented, it will be useful.

**Comment by lll000111** [comment]
Why do you still file issues for this project? See README!
