### ISSUE TITLE
upload doesn't work

### ISSUE THREAD

**Issue by anchetaWern** [wkh237/react-native-fetch-blob#7]
I'm getting the error:

```
sorry, the request failed. Please try again. {line: 381, column: 882, sourceURL: file: //index.android.bundle.
```

Not really sure what the error is all about but it seems I do not get this error when I enable chrome debugging. I tried creating a deploy version of the app in hopes that it would work but it didn't. 

I'll come back later to update and provide more info.

**Comment by anchetaWern** [comment]
seems to be related to this: https://github.com/wkh237/react-native-fetch-blob/issues/6
I'll close this off when it solves the issue for me.

**Comment by wkh237** [comment]
Hi @anchetaWern , I already got the situation, thanks for the report. 
You may try upgrade to v0.4.0, or would you provide the usage code about how the error happens?

**Comment by anchetaWern** [comment]
@wkh237 thanks it's working now. It looks like it's the same problem as the issue I linked to. 
I was supplying the base64 of the image picked with this module: https://github.com/marcshilling/react-native-image-picker to your library and it didn't work before when chrome debugging is disabled.
