### ISSUE TITLE
undefined is not an object(evaluating 'RNFetchBlob.DocumentDir')

### ISSUE THREAD

**Issue by asadadams** [wkh237/react-native-fetch-blob#706]
Installed react-native-fetch-blob version 0.10.8. And my react native version is 0.55.4. Receive the error 
"undefined is not an object(evaluating 'RNFetchBlob.DocumentDir')" when i require RNFetchBlob in my component . Have followed the instructions . Using manual linking and also using react-native link but still receive the error. I'm trying this on my android phone using react-native run-android in development . Need help urgently

**Comment by Spursh** [comment]
I have the same issue. Please look into it

**Comment by asadadams** [comment]
@Spursh  I fix it , just follow the linking instructions , either manual or using react-native link. You have to make sure the app is actually recompiling
