### ISSUE TITLE
Unable to resolve base 64  from directory

### ISSUE THREAD

**Issue by shirleycharlin** [wkh237/react-native-fetch-blob#71]
Hi!

I relocated my project to another folder. and I was prompt 
"unable to resolve module base-64 from <directory>/node_modules/react-native-fetch-blob/index.js
Unable to find this module in its module map or any of the node_module/base-64 and its parent directories.

**Comment by wkh237** [comment]
@shirleycharlin , does it help if you install `base-64` again ?

```
$ npm install --save base-64
```

**Comment by shirleycharlin** [comment]
Yes it does! thanks! :)

**Comment by wkh237** [comment]
Great to hear that :+1:
