### ISSUE TITLE
Network request doesn't show up in network tab - Android

### ISSUE THREAD

**Issue by stanshivam** [wkh237/react-native-fetch-blob#714]
Hi, I am trying to upload an image to the server, But request does't sow up in network tab, However, the response gets logged in catch or then.  What do I have to do to see the request in network tab.

* please provide the version of installed library and RN project.

> "rn-fetch-blob": "^0.10.11",
> "react-native": "0.53.3",
> "react": "16.2.0"

* a sample code snippet/repository is very helpful to spotting the problem.
```
 return await RNFetchBlob.fetch(
                'POST',
                `${apiConfig.url}customer/add_or_edit_user_vehicle_information`,
                {
                  Accept: 'application/json',
                  'Content-Type': 'multipart/form-data',
                },
                [
                  {
                    name: 'vehicle_image',
                    filename: 'myPhoto.jpg',
                    type: 'image/jpeg',
                    data: RNFetchBlob.wrap(authData.vehicleImage.uri),
                  },
                ],
              ).then((resp) => {
                console.warn(resp);
              }).catch((err) => {
                console.warn(err);
              });
```
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
Needs Feedback

**Comment by Evangelione** [comment]
same

**Comment by JofBigHealth** [comment]
@stanshivam @Evangelione 

Use a proxy like Charles to inspect. Note: rn-fetch-blob is a native package. Unlike `fetch` it doesn't go through JavaScript so you can't inspect it with dev tools.

@wkh237 You should close this I think.

**Comment by stanshivam** [comment]
Ok thanks.
