### ISSUE TITLE
Save file to internal storage

### ISSUE THREAD

**Issue by punksta** [wkh237/react-native-fetch-blob#731]
Is it possible to download file to [internal storage](https://developer.android.com/guide/topics/data/data-storage#filesInternal)? 
I want to download file for permanently internal usage without sharing with other apps.

**Comment by punksta** [comment]
figure out. DocumentDir is internal storage absolute dir for android.

**Comment by prasad456** [comment]
Can you guide me, in detail plz
how to download in internal storage for get

**Comment by punksta** [comment]
```
let dirs = RNFetchBlob.fs.dirs
RNFetchBlob
.config({
  path : dirs.DocumentDir + '/path-to-file.anything'
})
```

**Comment by punksta** [comment]
@prasad456
