### ISSUE TITLE
Can addAndroidDownloads specify download path?

### ISSUE THREAD

**Issue by siyuan** [wkh237/react-native-fetch-blob#74]
I want to specify path using addAndroidDownloads. In the wiki page, there is no path in addAndroidDownloads. So how can I specify addAndroidDownloads' download path.

**Comment by wkh237** [comment]
@siyuan , I'm afraid this does not yet supported in current releases, but it sounds reasonable to support this function, I'll add this to `0.9.0` milestone this release will hopefully launch in coming weeks.

**Comment by wkh237** [comment]
close on 0.9.0 release
