### ISSUE TITLE
Typo in Readme manual linking

### ISSUE THREAD

**Issue by mlumbroso** [wkh237/react-native-fetch-blob#76]
Hi,

a small issue on Readme Android install :

```
+ project(':react-native-fetch-blob').projectDir = new File(rootProject.projectDir,
' ../node_modules/react-native-fetch-blob/android')       
```

There is a space in the beginning of the path that prevents building the app, just remove it :

`+ project(':react-native-fetch-blob').projectDir = new File(rootProject.projectDir, 
'../node_modules/react-native-fetch-blob/android')                        
`

**Comment by wkh237** [comment]
@mlumbroso , thank you for your report ! I'll fix it right now 👍

**Comment by mlumbroso** [comment]
Thanks to you for this great library :-)
