### ISSUE TITLE
Authentication not working.

### ISSUE THREAD

**Issue by gauravbhusare** [wkh237/react-native-fetch-blob#82]
I am trying to get a pdf file which needs authentication.
I am doing it in following way.

        RNFetchBlob.fetch('GET', pdfDownloadURL, {
            'Authorization' : DEMO_TOKEN,
           
          })
          .then((res) => {
            let base64Str = res.base64()
            let text = res.text()
            let json = res.json()
          })
          .catch((errorMessage, statusCode) => {
            alert(error)
           
          })

This code is giving error 403(forbidden). Token is write cause I accessed another api's using fetch method.
Please help me solving this issue.

**Comment by wkh237** [comment]
@gauravbhusare , I think I need more information to figure this out. Can you send the request to a local server and see what's the headers looks like at server side ?

**Comment by wkh237** [comment]
@gauravbhusare , besides, does happens on both platform ? Or it only happens on Android or IOS ?

**Comment by gauravbhusare** [comment]
@wkh237 I am trying it on android only.
and the link I am using is not on my local server. Actually the response is null but it is showing PDF in web browser.

**Comment by gauravbhusare** [comment]
![image](https://cloud.githubusercontent.com/assets/20472198/17618478/b5dee09a-609d-11e6-933b-3cdcc593865e.png)


HTTP/1.1 200 OK
Date: Fri, 12 Aug 2016 09:30:53 GMT
X-Powered-By: Express
X-XSS-Protection: 1; mode=block
X-FRAME-OPTIONS: SAMEORIGIN
Strict-Transport-Security: max-age=360000
cache-control: no-cache, no-store, must-revalidate
pragma: no-cache
expires: 0
Accept-Ranges: bytes
Last-Modified: Wed, 10 Aug 2016 09:28:22 GMT
ETag: W/"cb34-15673c7fef0"
Content-Type: application/pdf
Vary: Accept-Encoding
Content-Encoding: gzip
Keep-Alive: timeout=15, max=94
Connection: Keep-Alive
Transfer-Encoding: chunked

**Comment by wkh237** [comment]
Hi @gauravbhusare , I think there should be another request with header `Range` that has non-null response body and status 206. It works in web browser since web browser automatically send `Range` requests, but we're not implement this mechanism at this moment, I think you might need to send range requests manually.

**Comment by gauravbhusare** [comment]
Will you help me by giving a small example how to send another request while using fetch blob
?

**Comment by wkh237** [comment]
Hi @gauravbhusare , here's an `Range Request` example base on DropBox V1 API. 

```js
let tmp = null
// assume the file size is 23975 bytes
// request first part of the file
RNFetchBlob
    .config({
      path : RNFetchBlob.fs.dirs.DocumentDir + '/part1.png'
    })
    .fetch('GET', 'https://content.dropboxapi.com/1/files/auto/'+FILENAME, {
      Authorization : `Bearer ${DROPBOX_TOKEN}`,
      // this is important since the request URL always the same, is we don't disable cache control
      // mechanism, the request will always have same response data
      'Cache-Control' : 'no-store',
      'Range' : 'bytes=0-22975'
    })
  })
  .then((res) => {
    // get second part and save to another file
    return RNFetchBlob
    .config({
      path : RNFetchBlob.fs.dirs.DocumentDir + '/part2.png'
    })
    .fetch('GET', 'https://content.dropboxapi.com/1/files/auto/'+FILENAME, {
      Authorization : `Bearer ${DROPBOX_TOKEN}`,
      'Cache-Control' : 'no-store',
      // request a range from 22976 to the end of content
      'Range' : 'bytes=22976-'
    })
  })
  .then((res) => {
    tmp = res
    // append second part to first part
    return RNFetchBlob.fs.appendFile(RNFetchBlob.fs.dirs.DocumentDir + '/part1.png', RNFetchBlob.fs.dirs.DocumentDir + '/part2.png', 'uri')
  })
  .then(() => {
     // remove the file contains second part since its content already append to first part
     tmp.flush()
   })
```

For more detailed explanation of `Range Request` see this [StackOverflow thread](http://stackoverflow.com/questions/8293687/sample-http-range-request-session)

**Comment by gauravbhusare** [comment]
Thanks a lot @wkh237 . I was celebrating independence day. I will let you if it works.

**Comment by maximtmartin** [comment]
Does this solution work?
Does the Range request header work?

I have a problem on Android. 

'Range' : 'bytes=0-' gives me all the data and is correct.
'Range' : 'bytes=0-22976' is fine.
'Range' : 'bytes=22977-' gives me the the wrong data.  It just starts with byte 0 until the Content-Length is met instead of starting with byte 22977. The response headers are correct, the response data isn't.

When I test this in a browser I get the correct response data.
