### ISSUE TITLE
firebase storage file upload..

### ISSUE THREAD

**Issue by gilra2000** [wkh237/react-native-fetch-blob#83]
In React-Native app how can i upload an image from user' device to Firebase storage?

image path -> /storage/emulated/0/Pictures/image-760dac79.jpg

**Comment by wkh237** [comment]
Hi @gilra2000 , I think you can check the [sample app repository](https://github.com/wkh237/rn-firebase-storage-upload-sample).

Basically you have to replace `window.XMLHttpRequest` and `window.Blob` this way

```js
import RNFetchBlob from 'react-native-fetch-blob'

const polyfill = RNFetchBlob.polyfill

window.XMLHttpRequest = polyfill.XMLHttpRequest
window.Blob = polyfill.Blob
```

Then create a Blob from the path

```js
let path = '/storage/emulated/0/Pictures/image-760dac79.jpg'
Blob.build(RNFetchBlob.wrap(path), { type : 'image/jpeg' })
        .then((blob) => firebase.storage()
                .ref('rn-firebase-upload')
                .child(testImageName)
                .put(blob, { contentType : 'image/png' })
        )
        .then((snapshot) => { /* there we go ! */ })
```

However, if you replace `window.XMLHttpRequest` the `fetch` may not work properly, but you can use our `fetch` API as an alternative.

**Comment by gilra2000** [comment]
T.T

failed...

Can you help?

ImagePicker.showImagePicker(options, (response) => {
        console.log('Response = ', response);

        if (response.didCancel) {
          console.log('User cancelled image picker');
        }
        else if (response.error) {
          console.log('ImagePicker Error: ', response.error);
        }
        else if (response.customButton) {
          console.log('User tapped custom button: ', response.customButton);
        }
        else {

          const testImageName = `image-from-react-native-${Platform.OS}-${new Date()}.jpg`;

          let path = response.path;  
          // path ->  /storage/emulated/0/Pictures/image-8de3ead3-4411cc.jpg

          Blob.build(RNFetchBlob.wrap(path), { type : 'image/jpeg' })
            .then((blob) => firebase.storage()
                    .ref('rn-firebase-upload')
                    .child(testImageName)
                    .put(blob, { contentType : 'image/png' })
            )
            .then((snapshot) => { /* there we go ! */ })

        }
      });

**Comment by wkh237** [comment]
@gilra2000 , is there any error message ? I think I need more information to figure out where's the problem.

**Comment by gilra2000** [comment]
<img width="947" alt="2016-08-13 10 36 37" src="https://cloud.githubusercontent.com/assets/3529738/17643485/83c628e8-61a6-11e6-90d1-4208aba065b8.png">

**Comment by wkh237** [comment]
@gilra2000 , does this happens on Android ? I've found an Android XMLHttpRequest bug in `0.9.0`, that might cause some problem. 

If you're still getting problem, please try install the package to latest package `0.9.1` via the following commands

```
$ rnpm uninstall react-native-fetch-blob
$ npm install --save react-native-fetch-blob
$ rnpm link
```

**Comment by archanasantoshwhatkar** [comment]
Not working just showing page no any action. pls guide me how to save image and videos clicked by camera in database
