### ISSUE TITLE
undefined is not an object (evaluating 'RNFetchBlob.DocumentDir') 

### ISSUE THREAD

**Issue by rameramwe** [wkh237/react-native-fetch-blob#84]
hey guy i'm getting this error undefined is not an object (evaluating 'RNFetchBlob.DocumentDir') ..
i know this was mentioned before but all the solutions didn't help fix the problem for me 
i'm going crazy .. i've been trying 9 hours to fix it with no luck 
i tried rnpm and didn't work then tried linking manually and still didn't work 
i'm using linux and android
and this is my package file 
```json
  "name": "funshare",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "firebase": "^3.1.0",
    "react": "15.2.1",
    "react-native": "0.29.1",
    "react-native-cli": "^1.0.0",
    "react-native-fbsdk": "^0.2.2",
    "react-native-fbsdkcore": "0.0.8",
    "react-native-fbsdklogin": "0.0.8",
    "react-native-fbsdkshare": "0.0.8",
    "react-native-fetch-blob": "^0.6.4",
    "react-native-gifted-spinner": "0.0.5",
    "react-native-icon-badge": "^1.1.1",
    "react-native-image-picker": "^0.21.1",
    "react-native-swipe-cards": "0.0.7",
    "react-native-swiper": "^1.4.8",
    "reflux": "^0.4.1"
  }
}
```

**Comment by wkh237** [comment]
Hi @rameramwe , apparently you're getting this error because the library is not linked properly. I've noticed that you might using an very old version of this library (0.6.4). Perhaps you can try the following steps :

First, close the app and packager.

Then upgrade `rnpm`

```
$ npm install -g rnpm
```

Remove the installed package

```
$ rnpm uninstall react-native-fetch-blob
```

Re-install the library

```
$ npm install --save react-native-fetch-blob && rnpm link
```

And there should be some logs in the terminal

<img width="626" alt="2016-08-14 12 25 45" src="https://cloud.githubusercontent.com/assets/5063785/17647221/4fafa326-621a-11e6-9680-64d8cc85380f.png">

To verify if the library is linked properly, check if these lines exists in `settings.gradle`

```gradle
include ':react-native-fetch-blob'
project(':react-native-fetch-blob').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fetch-blob/android')
```

Also check MainApplication.java

```java
import com.RNFetchBlob.RNFetchBlobPackage;
```

```diff
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
+          new RNFetchBlobPackage(),                                                                                                                             
         new MainReactPackage()
      );
    }
```

Now, run the app see if it work properly

```
$ react-native run-android
```

> React Native has changed its Android application template in 0.29 which result in `rnpm link` not working with RN 0.29.0, and 0.29.1. However we've fixed this problem by adding custom rnpm.

**Comment by RichardBoyewa** [comment]
@wkh237 Thanks. Let me try that now.

**Comment by RichardBoyewa** [comment]
@wkh237 I am still getting the same. Could it be because I am using it from a worker? It is used alongside with `react-native-workers` could that be the problem; I doubt it.

Thanks

**Comment by RichardBoyewa** [comment]
![image](https://cloud.githubusercontent.com/assets/3919611/17647435/1df5e66a-61e8-11e6-985a-4fe91d0d47dc.png)

Thats what I got after running `rnpm link`

**Comment by rameramwe** [comment]
hey @wkh237  thanks a lot for the fast and awesome response 
i did exactly like you said and i even got the same results in my terminal but still the same error :( 
![screenshot from 2016-08-14 07 23 36](https://cloud.githubusercontent.com/assets/17526866/17647432/2288c9c4-61f0-11e6-8836-40b2afaf50e3.png)

then i tried deleting the build folder in my android folder and uninstalling the package and then reinstalling it and compiling but still no luck ..

**Comment by rameramwe** [comment]
@RichardBoyewa  hey man about the skipped thing i got it too you gotta delete this line   new RNFetchBlobPackage(), in mainapplication.java and it'll work actually it'll just add it again :P  .

**Comment by rameramwe** [comment]
@wkh237 i noticed this while compiling ..does it matter ? 
![screenshot from 2016-08-14 07 34 46](https://cloud.githubusercontent.com/assets/17526866/17647469/d8a30c64-61f1-11e6-8285-854f7289accd.png)

**Comment by RichardBoyewa** [comment]
@rameramwe I did just that and the error is still there. Are you using it from a worker service? I am using this for a background service. 
Worker : `react-native-workers`

**Comment by rameramwe** [comment]
@RichardBoyewa  actually no i'm not using Workers but i'm using other stuff like image picker and Fbsdk  do you think this might  be causing the problem ?

**Comment by wkh237** [comment]
@RichardBoyewa , if you're using `react-native-workers` did you add 

```java
new WorkerPackage(new MyAwesomePackage(), new MyAmazingPackage())
```

to `WorkerPackage` constructor (which should located in [node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/WorkerPackage.java line 34](https://github.com/devfd/react-native-workers/blob/master/android/src/main/java/co/apptailor/Worker/WorkerPackage.java#L34)) ?

**Comment by RichardBoyewa** [comment]
I am not sure. I have been on this for a while... But this is an interesting package, I will fight my way through it :-)

**Comment by RichardBoyewa** [comment]
@wkh237 Let me do that.... I missed that line :-(

**Comment by rameramwe** [comment]
this package is essential for me cause i'm using firebase and i need firebase storage .

**Comment by wkh237** [comment]
@rameramwe , does the [firebase upload sample](https://github.com/wkh237/rn-firebase-storage-upload-sample) work on you environment ?

**Comment by rameramwe** [comment]
i'll check that and see

**Comment by RichardBoyewa** [comment]
Heyyyyyyyyyyyyy! 👍 It works.......... uuuuhhnnnnnnn!!! Dancing..... @rameramwe How far with yours? @wkh237 Thanks a billion. Can we drop this line as a comment in the ReadMe, incase someone else try to use it this way.

Thanks guys. You rock!

**Comment by rameramwe** [comment]
@RichardBoyewa  congrats man :D hope  i  can fix it too :P

**Comment by RichardBoyewa** [comment]
@rameramwe How can I message you directly... there is something you need to take out of your repo ASAP.... Don't commit that to gitHub

**Comment by RichardBoyewa** [comment]
@rameramwe check your dependencies to see that they don't need a special installation like mine.

**Comment by rameramwe** [comment]
@RichardBoyewa  i don't know how if you want that's my email rameramwe@gmail.com but i know what you mean :P the firebase thing

**Comment by RichardBoyewa** [comment]
:-) Sent you a mail. Have u solved urs ?

**Comment by rameramwe** [comment]
no not yet i'm trying to get the firebase upload repo running locally and see what'S going on

**Comment by RichardBoyewa** [comment]
ok. Best of luck.

**Comment by rameramwe** [comment]
@wkh237  i got the repo running and it works and it gave me 80% result why the hell ain't working with original app ? that'S the package file for the upload repo 
{
  "name": "RNFirebaseUploadSample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "firebase": "^3.2.0",
    "react": "15.2.1",
    "react-native": "^0.28.0",
    "react-native-fetch-blob": "0.9.1",
    "react-native-testkit": "^0.1.1",
    "react-timer-mixin": "^0.13.3"
  }
}
you can see here i'm using react native v0.28.0

**Comment by wkh237** [comment]
@rameramwe , I've tested the library with 0.29.1 Ubuntu 15 environment and it works fine. Could you provide a simplified sample of your project ?

**Comment by rameramwe** [comment]
@wkh237  would you like to see the repo ? it's not that big 
thank you very much for the help

**Comment by wkh237** [comment]
Yeah, I'd like to help if it's possible.

**Comment by rameramwe** [comment]
@wkh237 Awesome :D that'S the repo https://github.com/rameramwe/funshare

**Comment by wkh237** [comment]
@rameramwe , when I try to run the application but it gives me a totally different error message saying that something is incorrect in `SwipeCard.js`.

**Comment by wkh237** [comment]
I temporarily removed anything in `index.android.js` it works now. 
<img width="415" alt="2016-08-14 3 48 41" src="https://cloud.githubusercontent.com/assets/5063785/17647905/9eda03e4-6236-11e6-8390-c7403448922a.png">

**Comment by rameramwe** [comment]
great .. it'S not important anyways but you should require the library fetch blob and see if it works

**Comment by wkh237** [comment]
@rameramwe , I've noticed that FacebookSDK uses different Android Build Tool (23.0.2) and React Native uses 23.0.1. When the first time I try to build the project, it shows the following error message.

![issue1](https://cloud.githubusercontent.com/assets/5063785/17647919/29c30f6e-6237-11e6-84af-03f4ed59272d.png)

I'm wondering if your environment missed this build tool too. I fix this error by simply open the Android project with Android Studio and install the build tool. Have you tried build the project using Android Studio ?

There's also a [StackOverflow thread](http://stackoverflow.com/questions/17963508/how-to-install-android-sdk-build-tools-on-the-command-line) about install build tools using command line.

**Comment by rameramwe** [comment]
@wkh237  no i didn't use android studio

**Comment by rameramwe** [comment]
i never got this error

**Comment by wkh237** [comment]
After upgrade `react-native-swipe-cards` to `0.8.0` and fix the missing comma in `SwipeCards.js` the app work properly now. Perhaps try clone the repo and reinstall the npm packages ?

![runnung](https://cloud.githubusercontent.com/assets/5063785/17648017/43541b8c-623a-11e6-9aac-2826da4eb8a3.png)

**Comment by rameramwe** [comment]
@wkh237  thank you very much i go it to work .. i was testing not on genymotion but on my phone .. the solution was  to uninstall the app from my phone and reinstalling it using run-android .. that'S very weird but now it's working perfectly thank you very much again .

**Comment by wkh237** [comment]
@rameramwe , great to hear that ! Please feel free ask any question when needed 😄

**Comment by RichardBoyewa** [comment]
Nice job done here @wkh237 . @rameramwe Glad you finally got it to work.

**Comment by yunxuanyan** [comment]
I'll get this exception if I turn on the "Don't keep activities" setting in android. If I turn it off, I can use this library normally. My version is 
    "react-native-fetch-blob": "^0.9.6".

Thanks.

**Comment by zxx714** [comment]
I'll get this exception if I turn on the "Don't keep activities" setting in android. If I turn it off, I can use this library normally. My version is 
"react-native-fetch-blob": "^0.9.6".

Thanks.

**Comment by dwilt** [comment]
I am trying to install your plugin and having this problem. I've tried starting from scratch twice in the past week and I keep getting this screen. I got it installed after a while the first time but I had to reinstall again can't remember how I got around it.

First off, a couple comments about your installation instructions:
1. You first mention to install the package with npm via `npm install --save react-native-fetch-blob`.  That's fine. However, right after that you say:
> Or if using CocoaPods, add the pod to your Podfile, for example:

If I'm correct, it's not an "or" but a required 2nd step. By using CocoPods, you get the required iOS files right? Also, there should be a `pod install` instruction after adding the line to the `Podfile` right? However, when I run `pod install`, it hangs on trying to install `React (0.11.0)`:

![image](https://cloud.githubusercontent.com/assets/1065539/20913732/23325870-bb2f-11e6-8e40-ec177171a3cb.png)

**Comment by dwilt** [comment]
`pod install` finally finished but it says `React has been deprecated`:
![image](https://cloud.githubusercontent.com/assets/1065539/20913932/8516e01e-bb30-11e6-9357-57ff50ab1a85.png)
And I'm seeing this when trying to run `react-native run-ios` now:
```


** BUILD FAILED **


The following build commands failed:
        CompileC /Users/dwilt/Projects/GJS/gjs-app/ios/build/Build/Intermediates/Pods.build/Release-iphonesimulator/react-native-fetch-blob.build/Objects-normal/i386/RNFetchBlob.o /Users/dwilt/Projects/GJS/gjs-app/node_modules/react-native-fetch-blob/ios/RNFetchBlob/RNFetchBlob.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/dwilt/Projects/GJS/gjs-app/ios/build/Build/Intermediates/Pods.build/Release-iphonesimulator/react-native-fetch-blob.build/Objects-normal/i386/RNFetchBlobFS.o /Users/dwilt/Projects/GJS/gjs-app/node_modules/react-native-fetch-blob/ios/RNFetchBlobFS.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

**Comment by naviocean** [comment]
I got a same issue of @dwilt

**Comment by slender9168** [comment]
Two things solved the problem for me:
1- use the react-native link command
2- deploy the app again to the device from android studio ( i think using the package manager (npm start) only packages the new javascript code, not the library native code )

**Comment by YummyHa** [comment]
I'm getting the same issue but i'm using expo. How can i fix it without detach the project, please help!!

**Comment by harish-aka-shivi** [comment]
If you are making a Activity and implementing DefaultHardwareBackBtnHandler,  then in your `onCreate(Bundle savedInstanceState)`,  use addPackage() method like this:


`mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new RNFetchBlobPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
`

**Comment by krishan-kumar-mourya** [comment]
After linking you need to run
`pod update`
