### ISSUE TITLE
[FirebaseStorage] Same codes work in iOS but no response in android

### ISSUE THREAD

**Issue by smilechun** [wkh237/react-native-fetch-blob#91]
_createItem() {
        let images = this.state.images;
        let uri = images[0].uploadPath;
        let type = images[0].type;
        let rnfbURI = RNFetchBlob.wrap(uri);
        let filename = new Date().getTime().toString();
        console.log(rnfbURI, uri, type, filename);
        // create Blob from file path
        Blob
            .build(rnfbURI, { type : type + ';'})
            .then((blob) => {
                console.log(blob);
                // upload image using Firebase SDK
                firebase.storage()
                    .ref('users')
                    .child(filename)
                    .put(blob, { contentType : type + ';'})
                    .then((snapshot) => {
                        console.log('Done.');
                        console.log(snapshot);
                        blob.close();
                    }, (err) => {
                            console.log(err);
                            blob.close();
                        }
                    )
            });
    }

    _addImage() {
        console.log("add image start.")
        var imagesList = this.state.images;

        ImagePicker.showImagePicker(options, (response) => {
            console.log('Response = ', response);

            if (response.didCancel) {
                console.log('User cancelled image picker');
            }
            else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            } else {
                var source = {uri: response.uri, isStatic: true};
                var type = response.type || "";
                var uploadPath = response.path || "";

                if (Platform.OS === 'ios') {
                    source = {uri: response.uri.replace('file://', ''), isStatic: true};
                    type = 'image/' + response.uri.substr(response.uri.lastIndexOf('.') + 1)
                    uploadPath = source.uri;
                }

                imagesList.push({
                    path: source,
                    cover: imagesList.length ? false : true,
                    type: type,
                    uploadPath: uploadPath
                });

                this.setState({
                    images: imagesList
                })

            }
        });
    }

Debug Console Screenshot:
![screen shot 2016-08-15 at 11 50 09 pm](https://cloud.githubusercontent.com/assets/5795291/17670117/0bfbaaf6-6343-11e6-8b29-53d6afa27ef8.png)

Seems the firebase put() was not called, but it works in iOS. 

Any helps?

**Comment by wkh237** [comment]
@smilechun , thanks for reporting the issue. What's the version of react-native-fetch-blob you're using?

**Comment by smilechun** [comment]
I am using0 .9.2-beta.1.
Actually, I am not sure this is repository issue or my coding issue since I could upload the file successfully by just clone and run [rn-firebase-storage-upload-sample](https://github.com/wkh237/rn-firebase-storage-upload-sample)

**Comment by wkh237** [comment]
I will try to figure this out, be the way, you can also enable logs for `Blob` and `XMLHttpRequest` by change 

`node_modules/react-native-fetch-blob/polyfills/Blob.js` 
`node_modules/react-native-fetch-blob/polyfills/XMLHttpRequest.js` 
that will give us more clue.

```diff
- log.disable()                                                                                                                                                
+ log.level(3)                                                                                                                                                
```

there would be a lot of logs.

**Comment by smilechun** [comment]
After enabled the logs, I found that in iOS, there are many XMLHttpRequest logs printed. 
However, In Android, nothing about XMLHttpRequest is printed. Is that fine or an issue?

It seems that the auth() request did not send to firebase, maybe this is a reason why there is no response when uploading the file.

**Comment by wkh237** [comment]
Would you mind paste android logs? I'll take some time tracking it 👍

**Comment by smilechun** [comment]
Android Logs:
![screen shot 2016-08-16 at 12 59 31 am](https://cloud.githubusercontent.com/assets/5795291/17672043/c705328c-634c-11e6-8bc3-6169e7d5cbd3.png)

iOS Logs (Too much, just a snippet):
![screen shot 2016-08-16 at 1 04 02 am](https://cloud.githubusercontent.com/assets/5795291/17672145/6e14420c-634d-11e6-9fe7-b9e79d196759.png)

As you can see, In iOS, The Firebase User is authenticated, but there is nothing in Android.

**Comment by wkh237** [comment]
@smilechun , I've reproduced the issue, looks like it only happens when you running the app in Debug Mode, this is due to the JS runtime difference between two modes (JSC vs V8). I'' try to fix this issue. Besides, you can still see debug information via `logcat` though.

**Comment by smilechun** [comment]
@wkh237 I don't why...but it suddenly works now....

**Comment by wkh237** [comment]
I think it'd be helpful if you enable both `Blob` and `XMLHttpRequest` logs and copy logs (in text), then paste here 😄 

<img width="721" alt="2016-08-16 7 10 52" src="https://cloud.githubusercontent.com/assets/5063785/17697069/2d802bc8-63e5-11e6-9165-4efcfb848e5e.png">

**Comment by smilechun** [comment]
@wkh237 After made some test, I found that if the connected android device is in "Debug JS Remotely" mode, the image could not be uploaded to firebase successfully. And it the "Debug JS Remotely" is turned off, it works as expected 👍
