### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by lty900301** [wkh237/react-native-fetch-blob#96]
I am using react-native-fetch-blob as an dependency and run into build issue. 

I root caused the problem and found an syntax missing ',' at here: https://github.com/wkh237/react-native-fetch-blob/blob/master/src/types.js#L50-L51

**Comment by wkh237** [comment]
Thanks for the information, I've added the missing comma to 0.9.2 branch, this fix will be included in next release 👍
